// Loaded with the collection lesson, never from the island render loop.
// Sep 28 2026 curriculum: 80 different key ideas with a core on space and time (creating space, timing, team shape),
// plus breaking lines, zones and thirds, the final third, transitions and defending space. Easy-to-find balls (level 1)
// use 7v7 words; rooftop/wall/manhole balls (level 2) 9v9 words; the hardest balls (level 3) 11v11 ideas (docs/quiz-design.md §5).
import {SCENES,LANDSCAPE,ballLessonFrame,ballLessonFrames,diagramLayout,motionPoint,pitchMap,type DiagramKind,type DiagramFrame,type DiagramLayout,type DiagramNode} from './ballLessonScenes';
export {SCENES,LANDSCAPE,ballLessonFrame,ballLessonFrames,diagramLayout,motionPoint,pitchMap};
export type {DiagramKind,DiagramFrame,DiagramLayout,DiagramNode};
export type LessonFamily='Creating space'|'Timing'|'Team shape'|'Breaking lines'|'Zones and thirds'|'Final third'|'Transitions'|'Defending space'|'On the ball'|'Set pieces'|'Goalkeeping';
export type BallLesson={kind:DiagramKind;family:LessonFamily;level:1|2|3;steps:[string,string,string];actions:[string,string]};
const L=(level:1|2|3,family:LessonFamily)=>(kind:DiagramKind,a:string,b:string,c:string,x:string,y:string):BallLesson=>({kind,family,level,steps:[a,b,c],actions:[x,y]});
const space1=L(1,'Creating space'),time1=L(1,'Timing'),shape1=L(1,'Team shape'),ball1=L(1,'On the ball'),final1=L(1,'Final third'),trans1=L(1,'Transitions'),def1=L(1,'Defending space');
const space2=L(2,'Creating space'),time2=L(2,'Timing'),shape2=L(2,'Team shape'),lines2=L(2,'Breaking lines'),zones2=L(2,'Zones and thirds'),final2=L(2,'Final third'),trans2=L(2,'Transitions'),def2=L(2,'Defending space'),ball2=L(2,'On the ball'),set2=L(2,'Set pieces'),keep2=L(2,'Goalkeeping');
const space3=L(3,'Creating space'),shape3=L(3,'Team shape'),lines3=L(3,'Breaking lines'),zones3=L(3,'Zones and thirds'),final3=L(3,'Final third'),trans3=L(3,'Transitions'),def3=L(3,'Defending space'),keep3=L(3,'Goalkeeping');

export const BALL_HUNT_LESSONS:Record<string,BallLesson>={
 // Level 1: ground balls near the paths.
 store:time1('scan-shoulder','The pass is coming. You don’t know a defender is behind you.','Look over your shoulder while the ball travels. Now you see them.','Turn away into the free side. Looking early gave you time.','Look over your shoulder','Turn into space'),
 coaches:final1('open-corner','The keeper stands in the middle of the goal.','The corners are the space the keeper can’t reach. Pick the far one.','Pass the ball low into the corner. Aim first, power second.','Find the open corner','Shoot low and calm'),
 garden:shape1('go-wide','Everyone stands in the middle. Two defenders block the pass forward.','The outside players run wide, near the sidelines. The defenders follow them.','A gap opens in the middle. Pass through it to the striker.','Run wide','Pass through the gap'),
 market:space1('dribble-angle','A defender stands between you and your teammate. The pass is blocked.','Dribble a few steps sideways. The angle to your teammate changes.','The lane is clear now. Pass before the defender slides across.','Dribble sideways','Pass through the lane'),
 museum:shape1('spread-out','Everyone runs to the ball. One defender can stop the whole crowd.','Three teammates run away from the crowd into open spaces.','Now you have three choices. Pass to the freest teammate.','Spread into space','Pass to a free teammate'),
 ferry:time1('pass-ahead','Your teammate is running. A pass to their feet makes them stop.','Look where they are going. Aim at the empty space ahead of them.','They meet the ball at full speed and keep going.','Aim ahead','Meet it running'),
 beach:space1('give-and-go','A defender blocks your way forward. There is space behind them.','Pass to your teammate, then sprint past the defender.','Your teammate passes it back into your run. The defender is beaten.','Pass and sprint','Take the return'),
 north:time1('arrive-late','You stand still in the space. The defender walks over and marks you.','Wait outside the space. Watch the passer get ready.','Run in as the pass is played. You and the ball arrive together.','Wait outside','Run in on time'),
 'wall-right':space1('touch-into-space','You stop the ball dead under your feet. The defender is on you.','Try again. Spot the open space before the ball arrives.','Touch the ball into that space. Now you have time.','Spot the space','Touch it away'),
 'garden-cafe':space1('pass-and-move','You pass and stand still. A defender steps in front of you.','Pass, then move to a new spot the defender isn’t blocking.','Your teammate has a clear pass back to you.','Move to a new spot','Get it back'),
 'market-north':shape1('triangle','Three teammates stand in a straight line. One defender blocks the pass.','One teammate moves forward, one moves wide. Now it’s a triangle.','You have two passes. The defender can’t block both.','Make three corners','Use the open pass'),
 northwest:space1('leave-shadow','You stand right behind a defender. The passer can’t reach you.','Take a few steps sideways, out of the defender’s shadow.','Now there is a clear line from the ball to you.','Step sideways','Show for the pass'),
 pier:shape1('depth','Everyone stands level with the ball. No forward pass, no pass back.','One teammate runs ahead. Another drops behind the ball.','Now there is a forward pass and a safe pass back.','Add depth','Play forward'),
 'west-market':space1('change-pace','You jog at one speed. The defender stays right beside you.','Slow down. The defender slows down and relaxes too.','Burst away fast! A gap opens and the pass comes.','Slow down','Burst away'),
 library:space1('check-away','Your marker is right next to you. There is no room.','Run away from the ball. The marker follows you.','Stop and check back toward the ball. The space you made is yours.','Move away','Check back'),
 'parcel-north':space1('two-v-one','Two of you, one defender. Standing close lets them guard both.','Spread apart, then dribble straight at the defender.','The defender comes to you. Pass to your free teammate.','Spread and dribble','Pass as they come'),
 'parcel-west':trans1('recover-inside','An attacker runs at your goal. You are behind the play.','Sprint back toward your own goal, not toward the ball.','Now you are between the attacker and the goal. Face them.','Sprint to your goal','Get in the way'),
 'parcel-south':def1('jockey','You dive in to tackle. The attacker dodges past you.','Try again. Stop an arm’s length away, knees bent, on your toes.','Back off with them. When the ball runs loose, poke it away.','Stay on your toes','Poke it away'),

 // Level 2: roofs, trucks, walls, grass hatches and manholes.
 terrace:ball2('half-turn','You face the passer, so you can’t see the space behind you.','Stand side-on, half turned. You see the ball and the space ahead.','Let the ball come across your body and touch it forward.','Turn side-on','Receive facing forward'),
 roof:shape2('three-lines','Defenders stay deep and attackers stay high. The middle is a huge gap.','Midfielders step into the gap, so each line can reach the next.','The ball goes up in short passes: defence, midfield, attack.','Fill the middle','Pass line to line'),
 school:shape2('hide-behind','Two teammates stand one behind the other. One defender blocks both passes.','The back player moves across to a new angle with its own lane.','Two different lanes. The defender can only block one.','Find your own lane','Pass the open lane'),
 club:lines2('run-behind','The defenders stand in a line. The biggest space is behind them.','Stay level with the last defender until the passer looks up.','Sprint in behind as the ball is played through the line.','Stay level','Sprint in behind'),
 'dock-entry':def2('danger-zone','The ball is out wide and every defender runs to it.','That leaves the middle in front of goal empty. Most goals come from there.','One defender presses the ball. The others tuck in and guard the middle.','See the danger','Guard the middle'),
 'store-roof':trans2('second-ball','A long ball goes up. Everyone stands and watches it.','Guess where it will drop and move around that spot early.','The header bounces loose. You are already there to win it.','Move to the drop zone','Win the loose ball'),
 'arcade-roof':space2('overlap','Your winger has the ball. One defender blocks the way down the line.','Run around the outside of the winger, down the sideline.','The defender can’t stop both of you. The winger passes into your run.','Run around the outside','Receive down the line'),
 'junior-roof':shape2('diamond','Four teammates stand flat, side by side. Few passes are safe.','Make a diamond: one behind, one on each side, one ahead.','The defender can’t cover every corner. Pass to the open one.','Build the diamond','Pick the open corner'),
 'books-roof':lines2('between-lines','The other team defends in two lines. You stand in front of both.','Check your shoulder and slip into the pocket between the lines.','The pass beats the first line. Turn and face the last defenders.','Slip into the pocket','Receive and turn'),
 'museum-roof':space2('drag-away','Your marker stands in the lane between the passer and your teammate.','Run wide. Your marker follows you and leaves the middle.','Your teammate drops into the space you made and gets the ball.','Take your marker away','Let a mate use it'),
 'grass-west':time2('passer-sees','You sprint too early. The passer is looking down and can’t see you.','Wait. The ball is under control and the passer looks up.','Now go! The passer sees your run and plays the ball.','Watch the passer','Go on the look'),
 'grass-junior':keep2('use-keeper','Two opponents press your defender. The forward pass is blocked.','Pass back to your keeper. Nobody is marking the keeper.','The keeper passes to your free defender on the other side.','Pass back to the keeper','Switch to the free side'),
 'grass-garden':final2('follow-shot','A teammate shoots. Everyone stops to watch the ball.','Keep running toward goal. The keeper might not catch it.','The keeper pushes it out. You are first to the rebound.','Run in after the shot','Score the rebound'),
 'grass-community':time2('curved-run','A straight run takes you past the last defender too early: offside.','Bend your run. Go across the line first, still level with it.','Turn forward just as the pass is played. You stay onside.','Run across first','Bend in on the pass'),
 'wall-books':lines2('dribble-line','A line of midfielders stands in front of you. Nobody is free.','Dribble at the gap between two of them and make them choose.','Burst through the gap. The whole line is behind you now.','Dribble at the gap','Burst through'),
 'wall-nova':time2('time-or-pressure','The ball is coming and the nearest defender is far away.','Lots of time: control it, turn and look forward.','Now a defender is close. No time: pass it first time.','Take your time','Play it quickly'),
 'wall-garden':space2('pin','The defender steps up and squeezes your midfielder. No room to turn.','Stand high, right next to that defender. Now they must stay back.','Your midfielder has room to receive and turn.','Stay high','Use the room in front'),
 'wall-library':ball2('talk','Your teammate can’t see the defender running up behind them.','Shout “Man on!” before the ball arrives.','They hear you and play it back safely. The ball is not lost.','Shout early','Play it safe'),
 'wall-arts':final2('shoot-early','You can see the goal. A defender is running over to block.','No extra touch. The shooting window is closing.','Shoot now, before the window shuts. Goal!','See the window','Shoot early'),
 'parcel-school':ball2('shield','A defender is right behind you and there is no pass yet.','Turn side-on. Your body goes between the defender and the ball.','Keep it on your far foot until a teammate arrives. Then pass.','Body in the way','Wait for support'),

 // Manholes: seen from above.
 "manhole-promenade":ball2('free-player','Three teammates want the ball. Who has no defender near them?','Count: one marked on the left, one in the middle. The right one is alone.','Pass to the free teammate. They have time to look up.','Count the defenders','Pass to the free one'),
 "manhole-rua-90":lines2('split-gap','Two defenders stand side by side with a gap between them.','Your teammate moves behind the gap, so the passer sees them through it.','A firm ground pass splits them. Two defenders beaten at once.','Line up the gap','Split them'),
 "manhole-cafe-mare":lines2('forward-first','A sideways pass is easy, but it beats nobody.','Look up first. The forward pass goes past three defenders.','Play forward when it’s on. Go sideways only when forward is shut.','Look up first','Play forward'),
 "manhole-visitor-centre":trans2('rest-defence','Your team attacks and everyone runs forward. Nobody is left back.','You stay back for safety, level with their striker.','The ball is lost, but you block the fast break.','Stay back','Block the break'),
 "manhole-classrooms":zones2('own-lane','Picture long lanes. Two teammates share one lane, so one defender guards both.','One stays wide. The other moves into the next lane in.','Two lanes, two options. A diagonal pass finds the inside player.','Take your own lane','Pass across lanes'),
 "manhole-rua-nova":zones2('thirds','From your goal to theirs, the pitch splits into three thirds.','Near your own goal, losing the ball is dangerous. Play safe and simple.','Near their goal, be brave: dribble, cross and shoot.','Play safe at the back','Be brave up front'),
 "manhole-fish-market":space2('blind-side','The defender watches the ball. They can see you too.','Drift behind their shoulder, onto the side they cannot see.','Step into the space as the pass is played. They turn too late.','Drift out of sight','Arrive for the pass'),
 "manhole-park-library":def2('defend-2v1','Two attackers run at you alone. Rush one and the other is free.','Stay between them and back off slowly. Make the pass hard.','You win time. A teammate sprints back: now it’s two against two.','Stay between','Wait for help'),
 "manhole-island-market":def2('show-outside','An attacker dribbles at you through the middle.','Stand a little inside them, at an angle. Leave the outside path open.','They go wide. The sideline works like an extra defender.','Angle your body','Steer them wide'),
 "manhole-courtside":final2('box-runs','A winger is about to cross. All three attackers run to the same spot.','Split up: one to the near post, one to the far post, one to the penalty spot.','The crosser picks the free runner. Spreading out makes the defence choose.','Split the runs','Cross to the free runner'),
 "manhole-west-market":final2('cutback','Your winger dribbles toward the end line.','The defenders sprint back toward their goal. Space opens behind them.','The winger pulls the ball back. A teammate arrives facing the goal.','Reach the end line','Pull it back'),
 "manhole-corner-deli":trans2('counter','The other team is attacking. Most of their players are near your goal.','You win the ball and look up. The space behind them is wide open.','One quick forward pass to a running teammate starts the counter-attack.','Win it and look up','Go forward fast'),
 "manhole-west-end-books":set2('build-out','Your keeper has a goal kick. Opponents stand close to your defenders.','In many 7v7 leagues, they must wait behind the build-out line.','Your defenders spread wide into the free space for a safe first pass.','Watch them retreat','Spread and pass'),
 "manhole-junior-club":set2('thrower-free','Throw-in. Your teammates are all marked, but nobody marks the thrower.','Throw to a teammate’s feet, then step onto the pitch.','They pass straight back to you. You are free with the ball.','Throw to feet','Get it back'),
 "manhole-arcade":def2('block-lane','The ball carrier wants to pass to the striker behind you.','Draw a line from the ball to the striker. You are beside it.','Step onto the line. The pass is blocked without a tackle.','Draw the passing line','Step into the lane'),
 "manhole-nursery":lines2('tempo','The defence is set. There is no gap between the two defenders.','Two quick passes across. The defenders have to slide with the ball.','A gap opens where they were. Play through it before it closes.','Move the ball quickly','Play through the gap'),
 "manhole-high-school":def2('press-trigger','A pass goes to an opponent. You wait close enough to jump in.','Their first touch is heavy. The ball rolls away from their feet.','That’s your signal. Press fast and win the loose ball.','Watch the first touch','Press the loose ball'),
 "manhole-community-hall":def2('slide-across','The ball goes out wide. Only the nearest defender moves.','Big gaps open between the defenders near the ball.','Everyone slides across together, like players tied with a rope.','See the gaps','Slide together'),
 "manhole-garden-cafe":ball2('run-with-ball','Open grass ahead and nobody close. Don’t stop the ball.','Push it ahead with big touches and sprint after it.','You gained lots of ground. Now look up for the next pass.','Push it into space','Look up'),
 "manhole-arts-wing":zones2('switch','The defenders all crowd the side where the ball is.','Look across: your teammate on the far side is all alone.','Switch it across fast, before the defenders slide over.','Look across','Switch the play'),
 "manhole-courtyard":keep2('keeper-angle','The keeper stays on the goal line. The shooter sees lots of goal.','Step out toward the ball, in line with the middle of the goal.','Now the keeper covers most of the goal. There is less to aim at.','Step out','Close the angle'),
 "manhole-pier-bakery":set2('wall-keeper','The other team has a free kick near your goal.','Players line up in a wall to block one side of the goal.','The keeper guards the other side. Together they cover the whole goal.','Build the wall','Guard the other side'),
 "manhole-humanities":trans2('delay-recover','Your team loses the ball and everyone chases it. The goal is left empty.','The nearest player slows the attacker. The others sprint back behind the ball.','The attack slows down and your team is back in shape.','Delay the attacker','Recover behind the ball'),
 "manhole-school-offices":set2('quick-free-kick','Your team wins a free kick. Opponents are arguing and walking back.','Look up while they aren’t ready. A teammate is free in space.','Take it quickly and pass to them before the defence is set.','Spot the free teammate','Restart quickly'),
 "manhole-history-museum":final2('square-pass','You are near goal at a tight angle. The keeper covers your shot.','Look across: your teammate in the middle sees the whole goal.','Pass across to them. They have a much easier finish.','Look across','Pass for the finish'),

 // Level 3: sky balls, the rooftop ramp, hidden walls and the high spacing targets.
 "sky-north":final3('cross-gap','The winger is ready to cross. The keeper and the defenders both guard the goal.','Find the gap between the keeper and the defenders. The keeper can’t easily come for it.','A low, fast cross into the gap. The striker arrives and taps it in.','Find the gap','Cross low and fast'),
 "sky-west":keep3('sweeper-keeper','Your defenders play high up the pitch. There is a lot of space behind them.','The keeper steps off the line to the edge of the box, watching the ball.','A long ball goes over the defence. The keeper gets there first.','Step off the line','Sweep behind'),
 "sky-plaza":shape3('big-small','Your team has the ball. Spread wide and long: make the pitch big.','The ball is lost. Now the other team has lots of room.','Squeeze together toward the ball. Small and tight, their passes have nowhere to go.','Make it big','Make it small'),
 "sky-east":zones3('overload-isolate','Your team gathers on the left. The defenders move over to help.','Your far winger stays wide and waits. Only one defender is left over there.','Switch it fast. The winger goes one-on-one with lots of space.','Overload one side','Switch to the winger'),
 "sky-pier":zones3('zone-14','Defenders guard the penalty box. The space just outside it, in the middle, is empty.','Drop into that pocket at the top of the box, facing goal.','From there you can shoot, slip a pass through, or play wide.','Find the pocket','Choose the best option'),
 "ramp-gap":trans3('counter-press','You lose the ball. The opponent is looking down and not ready yet.','The nearest three players press at once and block the passes out.','They win it back high up the pitch, close to the other goal.','Press straight away','Win it back high'),
 "wall-community":space3('underlap','The winger has the ball out wide. Their defender blocks the sideline.','Run inside the winger, into the half-space next to that defender.','The winger slips the pass inside. You are running at goal.','Run inside','Take the inside pass'),
 "high-humanities":def3('compact-lines','When defending, there is a big gap between your midfielders and your defenders.','An opponent drops into that gap. They can receive there and turn.','Defenders step up and a midfielder drops in. The gap and the pass are gone.','See the gap','Close it together'),
 "high-school":space3('third-man','A cannot pass to C. A defender blocks the lane.','A passes to B. As the ball travels, C starts running.','B plays it first time into C’s run. The third player arrives free.','Pass to B, C runs','Find the third player'),
 "high-classrooms":def3('cover-balance','All three defenders rush the ball. Beat one and you beat them all.','One defender presses the ball. The next covers just behind, at an angle.','The far defender tucks in to guard the middle. That is balance.','Press and cover','Tuck in for balance'),
 "high-visitor":space3('drop-drag','The centre-back marks your striker. There is no space behind them.','The striker drops toward the ball to receive. The centre-back follows.','Space opens behind. A winger runs inside into it and gets the pass.','Drop to receive','Run into the space'),
 "high-mercado":lines3('up-back-through','Your striker is tightly marked and can’t turn with the ball.','Pass up to the striker. They play it back to a midfielder facing forward.','The midfielder slips it through to a runner behind the defence.','Play up and back','Play it through'),
 "high-nova":zones3('half-space','Cut the pitch into five lanes. The half-spaces sit between the wide lanes and the middle.','Drift into the half-space, between their full-back and centre-back.','Both defenders hesitate over who should mark you. Receive, turn and face goal.','Find the half-space','Receive and turn'),
 "high-deli":space3('short-long','Two attackers stand together. Two defenders mark them easily.','One comes short toward the ball. The other runs long behind the defence.','The markers are pulled apart. Pass to whoever is free.','One short, one long','Pass to the free runner'),
 "high-apartments":def3('curved-press','Two opponents pass the ball between them. You want to press.','A straight run at the ball leaves the pass to the other opponent wide open.','Curve your run so your body blocks that pass. The carrier has fewer choices.','See the open pass','Curve your press'),
 "high-clubgrounds":def3('track-runner','The ball is out wide. You watch it, and your attacker sneaks behind you.','Turn your head, see the run and go with the runner.','The cross comes in, but you are there first to clear it.','Check your runner','Go with them'),
 "high-promenade":def3('squeeze-up','Your defenders stand in a straight line near your goal.','The opponents pass backward. Their attack moves away from your goal.','Step up together and keep the line straight. The attackers have less space.','Watch the back pass','Step up together'),
};

/** Prediction prompts are loaded only with the lesson modal, never by the island. */
export const BALL_HUNT_PRACTICE:Record<string,string>={
 store:'Before the pass arrives, where is the defender? Guess the free side, then reveal the look.',
 coaches:'Where is the keeper standing? Pick the corner that is hardest for them to reach.',
 garden:'Which two teammates should run wide, and where will a gap open?',
 market:'Keep your teammate still. Which way could you dribble to open the pass?',
 museum:'Everyone is chasing the ball. Where should three teammates go instead?',
 ferry:'Your teammate is running. Where should the pass go: their feet or the space ahead?',
 beach:'After you pass, where should you sprint to get the ball back?',
 north:'Where should you wait so you can arrive in the space as the ball does?',
 'wall-right':'Before the ball arrives, where would your first touch go?',
 'garden-cafe':'You just passed. Which new spot gives your teammate a clear pass back?',
 'market-north':'Move two teammates in your mind to make a triangle. How many passes are open now?',
 northwest:'Which way should you step to get out of the defender’s shadow?',
 pier:'Everyone is level. Who should go ahead, and who should drop behind?',
 'west-market':'Your marker is close. When would a sudden burst help you most?',
 library:'Which way do you run first, so you can come back into space?',
 'parcel-north':'When should you pass: before the defender comes, or once they commit to you?',
 'parcel-west':'An attacker runs at your goal. Which way do you sprint first?',
 'parcel-south':'Dive in, or stay on your feet? Decide how far away to stand.',
 terrace:'How would you stand to see the passer and the space ahead at the same time?',
 roof:'Find the three lines. Where is the gap, and who should fill it?',
 school:'Two options hide behind each other. Where should the back player move?',
 club:'When should you sprint behind the line: now, or when the passer looks up?',
 'dock-entry':'The ball is wide. Which space in front of goal must be guarded first?',
 'store-roof':'The long ball is in the air. Where will it drop, and where will it bounce next?',
 'arcade-roof':'Which way do you run around your winger to make the defender choose?',
 'junior-roof':'Turn the flat line into a diamond. Which corner will the defender leave open?',
 'books-roof':'Find the pocket between the two lines. What should you check before you go there?',
 'museum-roof':'If you run wide and your marker follows, who can use the space?',
 'grass-west':'Watch the passer. What must happen before you start your run?',
 'grass-junior':'You are pressed near your goal. Who on your team is nobody marking?',
 'grass-garden':'Your teammate shoots. Where would you run in case the keeper drops it?',
 'grass-community':'Trace a run that stays onside and still goes forward on the pass.',
 'wall-books':'Where is the gap in the midfield line? Could you dribble through it?',
 'wall-nova':'Is the defender near or far? Decide: take a touch, or pass first time?',
 'wall-garden':'Where could you stand so the defender can’t step up on your midfielder?',
 'wall-library':'Your teammate can’t see behind them. What would you shout, and when?',
 'wall-arts':'You can see the goal and a defender is coming. Touch or shoot?',
 'parcel-school':'There is no pass yet. Where does your body go, and where does the ball go?',
 'manhole-promenade':'Count the defenders near each teammate. Which one is standing alone?',
 'manhole-rua-90':'Where is the gap between the two defenders? Where should your teammate stand?',
 'manhole-cafe-mare':'How many defenders does each pass beat: the sideways one or the forward one?',
 'manhole-visitor-centre':'If everyone attacks, who stops a quick counter? Choose your safety player.',
 'manhole-classrooms':'Two teammates share a lane. Which lane should one of them move into?',
 'manhole-rua-nova':'Which third is the ball in? Should this player play safe or be brave?',
 'manhole-fish-market':'The defender watches the ball. Where is the side they cannot see?',
 'manhole-park-library':'Two attackers against you. Where do you stand so the pass is hard?',
 'manhole-island-market':'Where should you stand to steer the dribbler toward the sideline?',
 'manhole-courtside':'Send one runner to each space: near post, far post and penalty spot. Who will be free?',
 'manhole-west-market':'When the defenders run back toward goal, where does the space open?',
 'manhole-corner-deli':'You just won the ball. Where is the space the other team left behind?',
 'manhole-west-end-books':'Where must opponents wait at a 7v7 goal kick? Where should your defenders go?',
 'manhole-junior-club':'Everyone is marked at the throw-in. Who is always free?',
 'manhole-arcade':'Draw a line from the ball to the striker. Where should you stand?',
 'manhole-nursery':'After two quick passes, where does a gap open between the defenders?',
 'manhole-high-school':'Watch the first touch. Is it close to their feet, or is this the moment to press?',
 'manhole-community-hall':'The ball goes wide. Which gaps open if only one defender moves?',
 'manhole-garden-cafe':'Nobody is near you and there is open grass. Stop, pass or run with it?',
 'manhole-arts-wing':'Everyone crowds one side. Where is your free teammate?',
 'manhole-courtyard':'Where should the keeper stand to leave the least goal to shoot at?',
 'manhole-pier-bakery':'The wall covers one side of the goal. Where should the keeper stand?',
 'manhole-humanities':'The ball is lost. Who slows the attacker, and where do the others run?',
 'manhole-school-offices':'The defence is not ready yet. Who is free for a quick restart?',
 'manhole-history-museum':'Shoot from the tight angle, or pass? Find the teammate with the clearer view.',
 'sky-north':'Where is the gap between the keeper and the defenders? Aim your cross there.',
 'sky-west':'Your defenders are high. Where should the keeper stand before the long ball?',
 'sky-plaza':'Your team just lost the ball. Should your shape get bigger or smaller?',
 'sky-east':'Your team crowds one side. Who is left one-on-one on the far side?',
 'sky-pier':'Find the space at the top of the box. What three things could you do from there?',
 'ramp-gap':'You just lost the ball. Who presses first, and which passes do you block?',
 'wall-community':'The defender blocks the sideline. Which run gets you past them on the inside?',
 'high-humanities':'Find the gap between your two lines. Who steps up and who drops in?',
 'high-school':'A can’t reach C. Which pass comes first, and when should C run?',
 'high-classrooms':'Three defenders: who presses, who covers, and who balances?',
 'high-visitor':'If your striker drops deep and their defender follows, where does space open?',
 'high-mercado':'The striker is marked tight. Where should they play the ball next?',
 'high-nova':'Find the half-space between the full-back and the centre-back.',
 'high-deli':'Two attackers, two markers. What happens if one comes short and one goes long?',
 'high-apartments':'Which way should you curve your press to block the pass to the other opponent?',
 'high-clubgrounds':'The ball is wide. Where is the runner you are marking going?',
 'high-promenade':'They just passed backward. What should your whole defensive line do?',
};
