import type {LearningId} from './learningJourneys';
import {CORAL_CAY_SPOTS} from './coralCayBalls';
export const COIN_REWARD_ID='matchday-fox',COIN_STORAGE_KEY='fi2-matchday-coins-v1';
export type CoinSpot={id:string;name:string;x:number;y:number;z:number;kind:'hidden'|'kick'|'landing';parachute?:boolean;grass?:boolean;truck?:number;ramp?:string;wall?:{x:number;y:number;z:number;high?:boolean;round?:boolean;facing?:'south'|'east'};clue:string;detail:string;teaching:string;lesson:LearningId;manhole?:boolean;
 /** A ball resting on a floating buoy in the sea (Coral Cay): kick it from `kickFrom` on the deck (a shot heading at the buoy
  *  collects it), or glide to it with the parachute. The buoy and the chalk mark are drawn in its packed parcel. */
 buoy?:boolean;kickFrom?:{x:number;z:number}};
/** Landing radius around a manhole centre. The drawn cover is 1 m wide with a 1.22 m rim. */
export const MANHOLE_RADIUS=1.5;
const manhole=(slug:string,x:number,z:number,near:string,place:'crossroads'|'junction'|'corner',lesson:LearningId,teaching:string):CoinSpot=>({id:'manhole-'+slug,name:`Manhole · ${near} ${place}`,x,y:0,z,kind:'landing',manhole:true,clue:`Look down on the ${place} by ${near}. A football pattern marks the cover in the middle of the road.`,detail:`Fly above the middle of the ${place} by ${near}, right over the manhole cover. Then choose Walk to drop straight down onto it. Walking or driving over the cover will not open it.`,teaching,lesson});
/**
 * One football manhole at the centre of every road junction (world.ts roadJunctions, checked by tests/manhole-balls.cjs).
 * Each ball teaches a "from above" idea: vision, scanning, shape and finding space, seen the way a flyer sees the island.
 */
const MANHOLE_SPOTS:CoinSpot[]=[
 manhole('promenade',-16,65,'Promenade Café','junction','support',"Find the free teammate. From above, it is easy to spot the one player with no opponent close by. Before you pass, count the defenders near each teammate and look for the one standing alone."),
 manhole('rua-90',-16,-118,'Rua 90','junction','support',"Stand behind the gap. Looking down on the pitch, you can see the gap between two defenders. If a teammate stands in line with that gap, one firm ground pass splits both defenders."),
 manhole('cafe-mare',-16,-37.5,'Café Maré','crossroads','support',"Look forward first. A bird’s-eye view shows how many defenders each pass beats. A sideways pass beats nobody; a forward pass through the line can beat three. Play forward when it is on."),
 manhole('visitor-centre',-16,-159,'Park Visitor Centre','junction','support',"Keep someone back. From above, you can see what happens when everyone runs forward: nobody is left to stop a quick counter-attack. When your team attacks, one teammate stays back for safety."),
 manhole('classrooms',48,65,'Classrooms','junction','support',"One player per lane. Picture the pitch from above cut into long lanes. Two teammates in the same lane block each other and one defender can guard both. Spread into different lanes."),
 manhole('rua-nova',48,-118,'Rua Nova','junction','support',"Know your third. Picture the pitch from above in three bands: defending, middle and attacking. Near your own goal, choose safe passes; in the attacking third, be brave with dribbles, crosses and shots."),
 manhole('fish-market',48,-37.5,'Fish Market','junction','movement',"Move on the blind side. A defender watching the ball cannot see a runner behind their shoulder. From above you can see that blind spot; drift into it quietly, then step into view as the pass is played."),
 manhole('park-library',48,-159,'Park Library','junction','width',"Defend two against one. From above, you can see why rushing the ball is a mistake when two attackers run at you: the other one is left free. Stay between them, back off slowly and wait for help."),
 manhole('island-market',48,-80,'Island Market','junction','support',"Show them the sideline. Seen from above, the middle is the most dangerous place for an attacker to reach. As a defender, stand at an angle that steers the dribbler toward the touchline."),
 manhole('courtside',48,-12,'Courtside','junction','movement',"Fill three spaces in the box. From above, a cross is easy to defend when every attacker runs to the same spot. Spread out: one runner to the near post, one to the far post and one to the penalty spot."),
 manhole('west-market',-45,65,'West Market','corner','width',"Pull it back from the end line. When a winger reaches the end line, defenders rush back toward their goal. From above you can see the space they leave; a pass pulled back finds a teammate facing goal."),
 manhole('corner-deli',-45,-37.5,'Corner Deli','junction','movement',"Look forward when you win it. The moment your team wins the ball, the other team is still spread out from attacking. Lift your head, see the space they left behind and move the ball there quickly."),
 manhole('west-end-books',-45,-159,'West End Books','corner','width',"Use the build-out line. In many 7v7 leagues, when your keeper has a goal kick, opponents must go back behind the build-out line until the ball is played. From above, you can see the free space: defenders spread wide for a safe first pass."),
 manhole('junior-club',124,-159,'Junior Club','junction','movement',"The thrower is often free. From above, notice that nobody marks the player taking a throw-in. Throw to a teammate’s feet, step onto the pitch, and they can pass straight back to you."),
 manhole('arcade',124,-61,'Arcade','junction','support',"Stand in the passing lane. Looking down, you can draw a line from the ball to the most dangerous attacker. As a defender, stand on that line: you do not need to tackle to stop the pass."),
 manhole('nursery',124,-80,'The Nursery','junction','width',"Pass quickly to move the defence. From above, you can watch defenders slide across every time the ball moves. Quick, simple passes make them shift until a gap opens between them."),
 manhole('high-school',124,-12,'Island High School','corner','support',"Press on a heavy touch. From above you can see the moment an opponent’s touch pushes the ball away from their feet. That is the signal to press: close them down quickly while the ball is loose."),
 manhole('community-hall',196,-159,'Community Hall','corner','support',"Slide across together. From above, a good defending team looks like players tied together with a rope. When the ball goes to one side, everyone slides across together so no big gaps open near the ball."),
 manhole('garden-cafe',196,-61,'The Garden Café','corner','movement',"Run with the ball into space. From above, you may see a big empty space in front of you. Push the ball ahead with longer touches, sprint after it, then look up for the next pass."),
 manhole('arts-wing',88,65,'Arts Wing','junction','support',"Switch to the free side. From above, you can see when defenders crowd one side of the pitch. Move the ball quickly to the other side, where a teammate has space, before the defence can slide over."),
 manhole('courtyard',88,34,'Courtside Courtyard','junction','support',"Keeper: close the angle. Picture the shooter and the two posts from above: a triangle. When the keeper steps out along the line toward the ball, less of the goal is left to shoot at."),
 manhole('pier-bakery',88,165,'Pier Bakery','corner','support',"Share the goal with the wall. At a free kick near goal, the wall blocks one side of the goal and the keeper guards the other. Looking down, you can see how they work together so no part of the goal is open."),
 manhole('humanities',88,-12,'Humanities','junction','movement',"Delay, then recover. When your team loses the ball, look at what happens from above if everyone chases it. Instead, the nearest player slows the attacker while the others sprint back behind the ball."),
 manhole('school-offices',182,34,'School Offices','corner','movement',"Take a quick free kick. Right after a foul, many opponents are still walking back. From above you can spot an unmarked teammate; a quick, simple restart can find them before the defence is ready, unless the referee asks you to wait."),
 manhole('history-museum',182,165,'History Museum','corner','support',"Look for a better-placed teammate. Before you shoot from a tight angle, picture the pitch from above: a teammate may have a clear view of the goal. A simple pass to them can be the smartest way to score."),
];
export const COIN_QUEST:CoinSpot[]=[
 {id:'store',name:'Store gardens',x:78,y:0,z:-46,kind:'hidden',clue:'Start where island players choose their gear.',detail:'Look beside the small training bag west of the Store entrance.',teaching:"Look before it arrives. Check over your shoulder while the pass is on its way. If you already know where the defender is, you can turn away from them and you have more time on the ball.",lesson:'support'},
 {id:'coaches',name:'Soccer wall · left target',x:150,y:0,z:-27.7,kind:'kick',wall:{x:150,y:1.02,z:-29.27},clue:'A coach has left a target near the practice wall.',detail:'Kick the left target on the soccer practice wall. Then collect the ball in front of it.',teaching:"Pick the open corner. The keeper stands in the middle of the goal, so the corners are the hardest places to reach. A calm, low shot into the far corner beats a hard shot straight at the keeper.",lesson:'support'},
 {id:'garden',name:'Garden entrance',x:208,y:0,z:8,kind:'hidden',clue:'Look where the island grows its greens.',detail:'Check the training bag just south of the community garden entrance.',teaching:"Make the pitch wide. When your team has the ball, spread out toward the sidelines. Defenders have to follow you, and a gap opens in the middle for a forward pass.",lesson:'width'},
 {id:'market',name:'Market midpoint',x:224,y:0,z:98,kind:'kick',clue:'Halfway through the market, look for a football instead of fruit.',detail:'A marked parcel sits east of the central market sign. Find a clear lane to its target.',teaching:"Dribble to open a lane. If a defender blocks your pass, a few touches sideways change the angle. Your teammate stays still, but now the pass is open.",lesson:'support'},
 {id:'museum',name:'Museum frontage',x:155,y:0,z:188,kind:'hidden',clue:'Every club has a story. This clue is beside the museum.',detail:'Look behind the matchday trunk at the western end of the museum front.',teaching:"Don’t all chase the ball. When everyone runs to the ball, nobody is left to pass to. Spread into open spaces so the player with the ball has choices.",lesson:'support'},
 {id:'terrace',name:'Café terrace',x:198,y:9.23,z:156,kind:'landing',clue:'Coffee below the clouds, on the lower terrace.',detail:'Land on the padded box on the lower café terrace, or kick its front target.',teaching:"Open up on the half-turn. If you face the passer, you can’t see the space behind you. Stand side-on so you see the ball and the pitch ahead, then take your first touch forward.",lesson:'movement'},
 {id:'roof',name:'Café rooftop',x:200,y:18.23,z:136.5,kind:'hidden',clue:'Climb above the café to see the whole pitch.',detail:'Follow both stair flights. A small tactics board hides the rooftop ball.',teaching:"Keep the team connected. A team has three lines: defenders, midfielders and attackers. If a huge gap opens between them, passes get cut out. Keep each line close enough to pass to the next.",lesson:'width'},
 {id:'ferry',name:'Ferry approach',x:228,y:0,z:198,kind:'kick',clue:'The matchday ferry has a parcel waiting on shore.',detail:'Kick the target on the dock parcel west of the boarding ramp.',teaching:"Pass into the space ahead. A running teammate is not standing still. Aim at the empty space in front of them so they can keep running onto the ball.",lesson:'support'},
 {id:'beach',name:'Beach sidelines',x:57,y:0,z:198,kind:'kick',clue:'Near the sand court, football practice stays outside the lines.',detail:'Find the low target west of the volleyball court and send a ground pass into it.',teaching:"Give and go. Pass to a teammate, then sprint past the defender. Your teammate passes it straight back into the space behind them. Two quick passes beat one defender.",lesson:'support'},
 {id:'north',name:'North beach clearing',x:135,y:0,z:-204,kind:'landing',clue:'A padded delivery waits near the northern ramps.',detail:'Look south of the north beach ramp lane. Land on its padded lid or kick its target.',teaching:"Arrive, don’t wait. A player standing still in space is easy to mark. Wait outside the space, then run in as the pass is played, so you and the ball arrive together.",lesson:'movement'},
 {id:'wall-right',name:'Soccer wall · right target',x:162,y:0,z:-27.7,kind:'kick',wall:{x:162,y:1.02,z:-29.27},clue:'The soccer wall has a second surprise.',detail:'Kick the right target to break it open. Walk forward to collect the revealed ball.',teaching:"First touch into space. Stopping the ball dead under your feet lets the defender close you down. Spot the open space early and push your first touch into it.",lesson:'support'},
 {id:'garden-cafe',name:'Garden Café patio',x:221,y:0,z:-35,kind:'kick',clue:'Look beside the café where the community garden begins.',detail:'A marked training parcel waits south of the outdoor seating.',teaching:"Pass, then move. After you pass, don’t stand and watch. Move to a new spot the defender isn’t blocking, so your teammate can pass back to you.",lesson:'movement'},
 {id:'market-north',name:'Northern market stalls',x:222,y:0,z:42,kind:'kick',clue:'The first market stalls have more than produce.',detail:'Find the football-marked parcel on the promenade between the northern stalls.',teaching:"Make a triangle. Three teammates in a straight line are easy to block. Stand at the corners of a triangle and the player with the ball always has two passes.",lesson:'support'},
 {id:'school',name:'Palm Street Futsal · west target',x:-1,y:0,z:49,kind:'kick',wall:{x:-1,y:6.7,z:46.95,high:true,round:true},clue:'Look up at the west end of the Palm Street Futsal sign.',detail:'From the south walkway, face the round football target to the left of the Palm Street Futsal sign. Hold Kick for a high shot, then collect the ball that drops onto the walkway.',teaching:"Don’t hide behind a teammate. When two supporting players stand one behind the other, one defender can block both passes. Move to a different angle so each of you has your own lane.",lesson:'movement'},
 {id:'northwest',name:'Northwest beach',x:-34,y:0,z:-210,kind:'hidden',clue:'Follow the north shore toward its quieter western end.',detail:'Find the small equipment bag south of the beach umbrellas.',teaching:"Step out of the shadow. If a defender stands between you and the ball, you are hiding in their shadow. A few steps sideways put you back in view for a pass.",lesson:'support'},
 {id:'pier',name:'Southern pier',x:108,y:0,z:211,kind:'hidden',clue:'Look where the wooden pier faces the open water.',detail:'Check the matchday bag on the southern boardwalk, below the pier cafés.',teaching:"One ahead, one behind. If every teammate stands level with the ball, there is no forward pass and no safe pass back. Put one player ahead of the ball and one behind it.",lesson:'width'},
 {id:'club',name:'Teal pickup truck',x:48,y:.98,z:-40,kind:'hidden',truck:7,clue:'A teal pickup is touring the island roads.',detail:'Fly near the pickup until its outline turns green, then choose Walk. You will glide into the bed and collect the ball automatically. Release the joystick after landing, then use it to steer across roads, grass and open plazas. Tap Hop off to leave.',teaching:"Run in behind the defence. The space behind the last defenders is the most dangerous space on the pitch. Stay level with them until the passer looks up, then sprint in behind as the ball is played.",lesson:'movement'},
 {id:'dock-entry',name:'Gold pickup truck',x:218,y:.98,z:110,kind:'hidden',truck:8,clue:'Watch for a gold pickup exploring the island roads.',detail:'Look for the green outline near the truck and choose Walk. The landing assist follows the moving pickup and guides you into its bed. Release the joystick after landing, then steer across roads, grass and open plazas. Tap Hop off to leave, or choose Flight to take off.',teaching:"Protect the middle. Most goals come from the space right in front of goal. When the ball is out wide, one defender presses it while the others tuck in to guard the middle.",lesson:'support'},
 {id:'west-market',name:'West market courtyard',x:-62,y:0,z:59,kind:'landing',clue:'The western courtyard has a soft football delivery.',detail:'Land on its padded box or kick the target, away from the café tables.',teaching:"Slow, then fast. A defender can easily follow a player who jogs at one speed. Slow down so they relax, then burst away fast. The sudden change opens a gap for the pass.",lesson:'movement'},
 {id:'library',name:'Library square',x:87,y:0,z:-100,kind:'landing',clue:'A training delivery waits near the park library.',detail:'Check the east side of Library Square. Land on the pad or kick its target.',teaching:"Go away to come back. To lose a tight marker, first run away from the ball so the defender follows you. Then check back toward the ball into the space you made.",lesson:'movement'},
 {id:'store-roof',name:'Konbini rooftop',x:70,y:4.72,z:-58,kind:'hidden',clue:"Look above the place where you choose your gear.",detail:"Fly onto the Konbini roof. Look for a small training bag away from the edge.",teaching:"Be first to the second ball. After a long kick or a header, the ball often bounces loose. Players who move early to where it will drop win it far more often than players who stand and watch.",lesson:'movement'},
 {id:'arcade-roof',name:'Arcade rooftop',x:107,y:6.43,z:-58,kind:'hidden',clue:"The arcade has a surprise above its games.",detail:"Explore the middle of the Arcade roof.",teaching:"Overlap around the outside. When a teammate has the ball out wide, run around the outside of them and down the line. Their defender can’t stop both of you.",lesson:'movement'},
 {id:'junior-roof',name:'Junior Club rooftop',x:137,y:7.23,z:-177,kind:'hidden',clue:"Head north to the youngest club on the island.",detail:"Fly onto the Junior Club roof and look around before moving.",teaching:"Play in a diamond. Four players can make a diamond: one behind, one on each side and one ahead. The player with the ball then has a pass back, left, right and forward.",lesson:'movement'},
 {id:'books-roof',name:'West End Books rooftop',x:-64,y:10.23,z:-109,kind:'hidden',clue:"A western rooftop has a new chapter to discover.",detail:"Explore the roof of West End Books, west of the park.",teaching:"Find the pocket between the lines. Opponents defend in lines: midfielders in front, defenders behind. The space between those lines is a pocket. Check your shoulder, receive there and turn to face goal.",lesson:'movement'},
 {id:'museum-roof',name:'Museum rooftop',x:168,y:5.23,z:181,kind:'hidden',clue:"Football history has a view of the sea.",detail:"Land on the middle of the History Museum roof to find the training bag.",teaching:"Drag a defender away. A run helps even if you never get the ball. Run away from the space and take your marker with you, so a teammate can use the space you emptied.",lesson:'movement'},
 {id:'grass-west',name:'West End grass hatch',x:-74,y:0,z:-109,kind:'landing',grass:true,clue:"Look down from West End Books for a marked patch of grass.",detail:"Drop from the west edge of the bookshop roof onto the gold-marked grass lid. Landing opens it; kicks do not.",teaching:"Run when the passer can see you. A great run is wasted if the passer is looking down or is not ready. Wait until the ball is under control and they look up, then go.",lesson:'movement'},
 {id:'grass-junior',name:'Junior Club grass hatch',x:137,y:0,z:-187,kind:'landing',grass:true,clue:"A landing mark hides in the grass north of Junior Club.",detail:"Step off the north edge of the Junior Club roof and aim for the gold football on the grass.",teaching:"Use your keeper. When opponents press your defenders, the keeper is often the free player behind them. Pass back to the keeper, who can switch the ball to your free defender on the other side.",lesson:'movement'},
 {id:'grass-garden',name:'Garden House grass hatch',x:100,y:0,z:-138,kind:'landing',grass:true,clue:"Look just west of Garden House for a football in the grass.",detail:"Drop from the west edge of Garden House onto the marked grass lid to open the buried box.",teaching:"Follow your shot. Keepers often push shots out instead of catching them. When you or a teammate shoots, keep running toward goal so you are first to the rebound.",lesson:'movement'},
 {id:'grass-community',name:'Community Hall grass hatch',x:191,y:0,z:-177,kind:'landing',grass:true,clue:"The Community Hall has a secret beside its eastern wall.",detail:"Fall from the east roof edge onto the gold-marked grass patch. Collect the ball after the lid opens.",teaching:"Curve your run to stay onside. A straight run can take you past the last defender too early. Bend your run: go across the line first, then turn forward just as the pass is played.",lesson:'movement'},
 {id:'ramp-gap',name:'Rooftop finale jump',x:47.8333333333,y:16.0,z:-20.3,kind:'hidden',ramp:'roof-ramp-finale',clue:"The ball floats between the third rooftop ramp and the fourth landing ramp.",detail:"Ride a bike, scooter or moped along the rooftop ramp chain. The third ramp launches you through this ball toward the landing ramp.",teaching:"Win it back straight away. Right after your team loses the ball, the new attacker is not ready yet. The nearest players press together at once and block the passes out, to win it back near the other goal.",lesson:'movement'},
 {id:'wall-books',name:'West End Books high target',x:-54.2,y:0,z:-109,kind:'kick',wall:{x:-56.6,y:4.3,z:-109,high:true,facing:'east'},clue:'Look up at the east wall of West End Books.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Dribble past a line. When a line of midfielders stands in front of you, dribble at the gap between two of them. Burst through and the whole line is out of the game.",lesson:'support'},
 {id:'wall-nova',name:'Rua Nova high target',x:43.2,y:0,z:-134,kind:'kick',wall:{x:41.9,y:5.56,z:-134,high:true,facing:'east'},clue:'Look up at the east wall of Rua Nova.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Know how much time you have. If the defender is far away, you have time to control, turn and look. If a defender is close, pass it first time. Check before the ball arrives.",lesson:'support'},
 {id:'wall-garden',name:'Garden House high target',x:112,y:0,z:-129.8,kind:'kick',wall:{x:112,y:3.04,z:-131.38,high:true},clue:'Look up at the south wall of Garden House.',detail:'Find the raised box with a muted brass football mark. Face the wall and use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Pin a defender. If you stand high, right next to the last defender, they can’t step up without leaving space behind them. By staying put, you give a teammate room in front of that defender.",lesson:'support'},
 {id:'wall-library',name:'Local Library high target',x:220,y:0,z:-117,kind:'kick',wall:{x:217.9,y:2.83,z:-117,high:true,facing:'east'},clue:'Look up at the east wall of Local Library.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Tell a teammate what you see. A player receiving the ball often can’t see behind them. Shout early: “Man on!” when a defender is close, “Time!” when they have space.",lesson:'support'},
 {id:'wall-arts',name:'Arts Wing high target',x:72,y:0,z:57.2,kind:'kick',wall:{x:72,y:4.72,z:55.62,high:true},clue:'Look up at the south wall of Arts Wing.',detail:'Find the raised box with a muted brass football mark. Face the wall and use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Shoot when the window is open. When you can see the goal and nobody is blocking, shoot. An extra touch gives a defender time to close the window.",lesson:'support'},
 {"id":"wall-community","name":"Pier Bakery · hidden wall target","x":107.5,"y":0,"z":181,"kind":"kick","wall":{"x":105.4,"y":3.8,"z":181,"high":true,"facing":"east"},"clue":"Look closely at the east wall of Pier Bakery. A small weathered futbol mark blends into the wall.","detail":"Approach Pier Bakery from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Run inside the winger. An underlap is a run on the inside of the teammate with the ball, into the half-space. The defender blocking the winger can’t also track your run toward goal.","lesson":"support"},
 {id:'parcel-north',name:'North shore delivery',x:80,y:0,z:-205,kind:'kick',clue:'Explore the north shore delivery for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"Two against one. With two attackers against one defender, spread apart and dribble straight at the defender. When they come to you, pass to your free teammate.",lesson:'support'},
 {id:'parcel-west',name:'Western promenade',x:-80,y:0,z:25,kind:'kick',clue:'Explore the western promenade for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"Get between them and your goal. When an attacker gets past you, sprint back toward your own goal, not toward the ball. Get between the attacker and the goal, then face them.",lesson:'support'},
 {id:'parcel-school',name:'Palm Street Futsal · east target',x:23,y:0,z:49,kind:'kick',wall:{x:23,y:6.7,z:46.95,high:true,round:true},clue:'The parking P points to a second target above it.',detail:'Stand south of the parking garage and look above the P marking, to the right of the Palm Street Futsal sign. Hold Kick for a high shot at the round target, then collect the ball on the walkway.',teaching:"Shield the ball. When a defender is close and you have no pass, turn side-on and put your body between them and the ball. Keep it on your far foot until a teammate arrives.",lesson:'support'},
 {id:'parcel-south',name:'South beach delivery',x:143,y:0,z:204,kind:'kick',clue:'Explore the south beach delivery for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"Stay on your feet. Diving in to tackle is easy to dodge. Stop an arm’s length away with your knees bent, back off with the attacker and poke the ball away when it runs loose.",lesson:'support'},
 {"id": "high-humanities", "name": "Humanities · high spacing target", "x": 111.8, "y": 0, "z": 25.4, "kind": "kick", "wall": {"x": 111.8, "y": 10.5, "z": 22.9, "high": true, "round": true}, "clue": "Look high on the south face of Humanities. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Humanities. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Stay compact between the lines. When defending, keep the gap between your defenders and midfielders small. If it grows, an opponent can receive in it and turn. Step up or drop in together to close it.", "lesson": "support"},
 {"id":"high-school","name":"Dining Hall · hidden wall target","x":81.8,"y":0,"z":105,"kind":"kick","wall":{"x":79.4,"y":8.5,"z":105,"high":true,"round":true,"facing":"east"},"clue":"Look closely at the east wall of Dining Hall. A small weathered futbol mark blends into the wall.","detail":"Approach Dining Hall from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"The third-player run. When A cannot pass straight to C, A passes to B, and C starts running while the ball travels. B plays it first time into C’s run, and the third player arrives free.","lesson":"support"},
 {"id": "high-classrooms", "name": "Eastern Classrooms · high spacing target", "x": 165.8, "y": 0, "z": 25.4, "kind": "kick", "wall": {"x": 165.8, "y": 10.5, "z": 22.9, "high": true, "round": true}, "clue": "Look high on the south face of Eastern Classrooms. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Eastern Classrooms. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Press, cover, balance. Defenders share three jobs. The nearest presses the ball, the next covers behind in case the presser is beaten, and the farthest tucks in to guard the middle.", "lesson": "support"},
 {"id": "high-visitor", "name": "Park Visitor Centre · high spacing target", "x": -1, "y": 0, "z": -124.9, "kind": "kick", "wall": {"x": -1, "y": 10.5, "z": -126.6, "high": true, "round": true}, "clue": "Look high on the south face of Park Visitor Centre. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Park Visitor Centre. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Drop deep to drag a defender. When a striker drops toward midfield to receive, the centre-back often follows. That leaves space behind them, and a winger can run inside into it.", "lesson": "width"},
 {"id": "high-mercado", "name": "Park Library \u00b7 hidden wall target", "x": 77.5, "y": 0, "z": -137.3, "kind": "kick", "wall": {"x": 77.5, "y": 5.8, "z": -139.6, "high": true, "round": true}, "clue": "Look closely at the south wall of Park Library. A small weathered futbol mark blends into the wall.", "detail": "Approach Park Library from the south. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.", "teaching": "Up, back, through. A pass to a tightly marked striker can still be useful. The striker plays it back to a midfielder facing forward, who slips a pass through to a runner behind the defence.", "lesson": "support"},
 {"id":"high-nova","name":"School Offices · hidden wall target","x":200,"y":0,"z":61.3,"kind":"kick","wall":{"x":200,"y":10.5,"z":58.9,"high":true,"round":true},"clue":"Look closely at the south wall of School Offices. A small weathered futbol mark blends into the wall.","detail":"Approach School Offices from the south. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Use the half-spaces. Cut the pitch into five lanes. The lanes between the wide lanes and the middle are the half-spaces. A player there is hard to mark: the full-back and the centre-back both wonder whose job it is.","lesson":"width"},
 {"id": "high-deli", "name": "Corner Deli · high spacing target", "x": -54.2, "y": 0, "z": -55, "kind": "kick", "wall": {"x": -56.6, "y": 7.1, "z": -55, "high": true, "round": true, "facing": "east"}, "clue": "Look high on the east face of Corner Deli. A football target marks a lesson about team spacing.", "detail": "Find the round muted brass-rimmed target high above Corner Deli. Back away along the clear east approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "One short, one long. When two attackers make the same run, one defender can handle both. If one comes short toward the ball while the other runs long behind, the defenders are pulled apart and one attacker is free.", "lesson": "movement"},
 {"id":"high-apartments","name":"The Grocer · hidden wall target","x":-54.2,"y":0,"z":2,"kind":"kick","wall":{"x":-56.6,"y":7.5,"z":2,"high":true,"round":true,"facing":"east"},"clue":"Look closely at the east wall of The Grocer. A small weathered futbol mark blends into the wall.","detail":"Approach The Grocer from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Curve your press. A straight run at the ball carrier leaves the easy pass open behind you. Run in a curve instead, so your body blocks the pass to their teammate while you close them down.","lesson":"width"},
 {"id": "high-clubgrounds", "name": "Club Grounds · high spacing target", "x": 159, "y": 0, "z": -167.2, "kind": "kick", "wall": {"x": 159, "y": 7.1, "z": -169.6, "high": true, "round": true}, "clue": "Look high on the south face of Club Grounds. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Club Grounds. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Track your runner. When you defend, don’t only watch the ball. If the player you mark runs behind you, turn your head, see the run and go with them.", "lesson": "movement"},
 {"id": "high-promenade", "name": "Cafe By The Sea \u00b7 hidden wall target", "x": 211.8, "y": 0, "z": 136.5, "kind": "kick", "wall": {"x": 209.4, "y": 14, "z": 136.5, "high": true, "round": true, "facing": "east"}, "clue": "Look closely at the east wall of the tall north wing at Cafe By The Sea.", "detail": "Stand on the eastern boardwalk and look high on the north wing for a small weathered futbol mark. Back away, hold Kick for a high shot, and collect the ball below.", "teaching": "Step up together. A defensive line works like a piece of string. When the other team passes backward, every defender moves up at the same time, so the line stays straight and the attackers have less space.", "lesson": "support"},
 {"id": "sky-north", "name": "North shore sky", "x": 62, "y": 60, "z": -207, "kind": "hidden", "parachute": true, "clue": "Look above north shore. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Cross into the gap. The most dangerous cross flies low and fast into the space between the keeper and the defenders. The keeper can’t easily come for it, the defenders are running back, and your striker attacks it.", "lesson": "movement"},
 {"id": "sky-west", "name": "West coast sky", "x": -50, "y": 80, "z": -76, "kind": "hidden", "parachute": true, "clue": "Look above west coast. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "The keeper sweeps behind. When your defenders play high up the pitch, there is space behind them. A keeper who stands at the edge of the box can run out and reach a long ball before the striker.", "lesson": "movement"},
 {"id": "sky-plaza", "name": "Plaza sky", "x": 112, "y": 120, "z": -12, "kind": "hidden", "parachute": true, "clue": "Look above plaza. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Big with the ball, small without it. When your team has the ball, spread wide and long to make the pitch big. The moment you lose it, squeeze together to make it small, so the other team has no room.", "lesson": "movement"},
 {"id": "sky-east", "name": "Garden sky", "x": 219, "y": 100, "z": 22, "kind": "hidden", "parachute": true, "clue": "Look above garden. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Crowd one side, attack the other. Put lots of players near the ball on one side and the defenders move over to help. Then switch fast to your winger on the far side, who is now one-on-one.", "lesson": "movement"},
 {"id": "sky-pier", "name": "Pier sky", "x": 119, "y": 140, "z": 195, "kind": "hidden", "parachute": true, "clue": "Look above pier. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "The pocket at the top of the box. The space just outside the penalty area, in the middle, is where many goals are made. A player who receives there facing goal can shoot, slip a pass through or play wide.", "lesson": "movement"},
 ...MANHOLE_SPOTS,
 // Sep 29 2026: twenty Coral Cay balls take the hunt to 100 (coralCayBalls.ts). Always appended, so saved IDs keep their order.
 ...CORAL_CAY_SPOTS,
];
const CORAL_CAY_IDS=new Set(CORAL_CAY_SPOTS.map(spot=>spot.id));
export type CoinProgress={version:5;allCostumesUnlocked?:boolean;rewardUnlocked:boolean;revealed:string[];collected:string[];hint:string|null;celebrated:boolean};
export const emptyCoinProgress=():CoinProgress=>({version:5,rewardUnlocked:false,revealed:[],collected:[],hint:null,celebrated:false});
const ids=new Set(COIN_QUEST.map(c=>c.id));
// The original forty IDs stay in their original order. Old completed saves keep their earned outfit.
const originalRewardIds=COIN_QUEST.slice(0,40).map(spot=>spot.id);
// The fifty-five balls from before the manhole covers. A pre-version-4 save with all of them keeps its fox and costumes.
const preManholeIds=COIN_QUEST.filter(spot=>!spot.manhole&&!CORAL_CAY_IDS.has(spot.id)).map(spot=>spot.id);
// The eighty balls from before Coral Cay (Sep 29 2026). A pre-version-5 save that found all eighty keeps the Matchday Fox and
// every costume it had, even though "every ball" now means 100; its 80-ball finale stays unseen until the new 100-ball one.
export const PRE_CORAL_CAY_IDS=COIN_QUEST.filter(spot=>!CORAL_CAY_IDS.has(spot.id)).map(spot=>spot.id);
export function sanitizeCoinProgress(raw:unknown):CoinProgress{
 const r=raw as (Omit<Partial<CoinProgress>,'version'>&{version?:number})|null;if(!r||typeof r!=='object')return emptyCoinProgress();
 const clean=(v:unknown)=>Array.isArray(v)?[...new Set(v.filter((id):id is string=>typeof id==='string'&&ids.has(id)))]:[];
 const version=r.version??1,collected=clean(r.collected),legacyReward=version<2&&originalRewardIds.every(id=>collected.includes(id)),legacyFiftyFive=version<4&&preManholeIds.every(id=>collected.includes(id)),legacyEighty=version<5&&PRE_CORAL_CAY_IDS.every(id=>collected.includes(id));
 const rewardUnlocked=r.rewardUnlocked===true||legacyReward||legacyFiftyFive||legacyEighty||collected.length===COIN_QUEST.length;
 const allCostumesUnlocked=r.allCostumesUnlocked===true||(version<3&&COIN_QUEST.slice(0,50).every(s=>collected.includes(s.id)))||legacyFiftyFive||legacyEighty||collected.length===COIN_QUEST.length;
 return{version:5,allCostumesUnlocked,rewardUnlocked,revealed:[...new Set([...clean(r.revealed),...collected])],collected,hint:typeof r.hint==='string'&&ids.has(r.hint)?r.hint:null,celebrated:r.celebrated===true&&collected.length===COIN_QUEST.length};
}
export const coinRewardEarned=(s:CoinProgress)=>s.rewardUnlocked===true||s.collected.length===COIN_QUEST.length;
export function applyCoinEvent(s:CoinProgress,id:string,kind:'reveal'|'collect'):CoinProgress{if(!ids.has(id))return s;const spot=COIN_QUEST.find(c=>c.id===id)!;if(kind==='collect'&&spot.kind!=='hidden'&&!s.revealed.includes(id))return s;if(s[kind==='collect'?'collected':'revealed'].includes(id))return s;return{...s,revealed:[...new Set([...s.revealed,id])],collected:kind==='collect'?[...s.collected,id]:s.collected,hint:kind==='collect'&&s.hint===id?null:s.hint};}

export const allCostumesEarned=(s:CoinProgress)=>s.allCostumesUnlocked===true||COIN_QUEST.every(spot=>s.collected.includes(spot.id));

// ── Costume unlocks (user, Sep 25 2026: "after every 10 balls it unlocks three costumes"). Edit the order here: each run of three
// unlocks together at 10, 20, 30 … balls collected; a mix of countries and animals in every group; the Matchday Fox (the gold
// "you found them all" costume) is last, at every ball. Unlocks only grow with collected balls, and the saved all-costumes / fox
// flags from the old all-balls rule still unlock everything they did, so nothing is ever re-locked.
export const BALLS_PER_COSTUME_MILESTONE=10,COSTUMES_PER_MILESTONE=3;
export const COSTUME_UNLOCK_ORDER=[
 'barcelona','bayern','flamengo',
 'arsenal','juventus','kashima',
 'psg','dortmund','santos',
 'liverpool','roma','pumas',
 'benfica','koln','river-plate',
 'chelsea','palmeiras','nagoya',
 'leicester','atletico-mineiro','cerezo',
 'botafogo','sutton',COIN_REWARD_ID,
] as const;
/** Balls needed for a costume: its group's milestone (the fox always needs every ball). */
export function costumeUnlockBalls(id:string){if(id===COIN_REWARD_ID)return COIN_QUEST.length;const i=(COSTUME_UNLOCK_ORDER as readonly string[]).indexOf(id);
 return i<0?COIN_QUEST.length:Math.min(COIN_QUEST.length,(Math.floor(i/COSTUMES_PER_MILESTONE)+1)*BALLS_PER_COSTUME_MILESTONE);}
export function costumeEarned(s:CoinProgress,id:string){
 if(id===COIN_REWARD_ID)return coinRewardEarned(s);
 return s.allCostumesUnlocked===true||s.collected.length>=costumeUnlockBalls(id);}
/** Every ball count that unlocks something (Sep 29 2026, 100 balls: three club costumes at 10 … 70, the last two at 80 and the
 *  Matchday Fox at every ball, 100). 90 unlocks nothing, so it is never announced or promised as "next". */
export const costumeMilestones=()=>[...new Set(COSTUME_UNLOCK_ORDER.map(costumeUnlockBalls))].sort((a,b)=>a-b);
/** The highest milestone reached (0 before the first), and the next one (null once every costume is unlocked). */
export const costumeMilestoneReached=(balls:number)=>costumeMilestones().filter(m=>m<=balls).pop()??0;
export function nextCostumeMilestone(balls:number){return costumeMilestones().find(m=>m>balls)??null;}
/** How many costumes unlock at a milestone. */
export const costumesAtMilestone=(balls:number)=>COSTUME_UNLOCK_ORDER.filter(id=>costumeUnlockBalls(id)===balls).length;
