import type {LearningId} from './learningJourneys';
export const COIN_REWARD_ID='matchday-fox',COIN_STORAGE_KEY='fi2-matchday-coins-v1';
export type CoinSpot={id:string;name:string;x:number;y:number;z:number;kind:'hidden'|'kick'|'landing';parachute?:boolean;grass?:boolean;truck?:number;ramp?:string;wall?:{x:number;y:number;z:number;high?:boolean;round?:boolean;facing?:'south'|'east'};clue:string;detail:string;teaching:string;lesson:LearningId};
export const COIN_QUEST:CoinSpot[]=[
 {id:'store',name:'Store gardens',x:78,y:0,z:-46,kind:'hidden',clue:'Start where island players choose their gear.',detail:'Look beside the small training bag west of the Store entrance.',teaching:"Scan before receiving. A quick look over your shoulder can reveal pressure before the ball arrives. Try spotting one teammate and one open space before your next touch.",lesson:'support'},
 {id:'coaches',name:'Soccer wall · left target',x:150,y:0,z:-27.7,kind:'kick',wall:{x:150,y:1.02,z:-29.27},clue:'A coach has left a target near the practice wall.',detail:'Kick the left target on the soccer practice wall. Then collect the ball in front of it.',teaching:"Inside-foot accuracy. The broad inside of your foot gives you a useful surface for a short pass. Point your standing foot toward the target and follow through along the passing line.",lesson:'support'},
 {id:'garden',name:'Garden entrance',x:208,y:0,z:8,kind:'hidden',clue:'Look where the island grows its greens.',detail:'Check the training bag just south of the community garden entrance.',teaching:"Make the pitch wide. Width spreads defenders across more space. When a teammate has the ball, look for a wide position where they can see you without a defender blocking the pass.",lesson:'width'},
 {id:'market',name:'Market midpoint',x:224,y:0,z:98,kind:'kick',clue:'Halfway through the market, look for a football instead of fruit.',detail:'A marked parcel sits east of the central market sign. Find a clear lane to its target.',teaching:"Move the ball to open a lane. When a defender blocks your pass, a controlled sideways dribble can change the angle. Keep looking up for the moment the route opens.",lesson:'support'},
 {id:'museum',name:'Museum frontage',x:155,y:0,z:188,kind:'hidden',clue:'Every club has a story. This clue is beside the museum.',detail:'Look behind the matchday trunk at the western end of the museum front.',teaching:"Football belongs to communities. A club is more than its first team: supporters, youth teams and local traditions help shape its identity. Explore a club story in the Store and find one thing that makes it special.",lesson:'support'},
 {id:'terrace',name:'Café terrace',x:198,y:9.23,z:156,kind:'landing',clue:'Coffee below the clouds, on the lower terrace.',detail:'Land on the padded box on the lower café terrace, or kick its front target.',teaching:"Balance for the next touch. A balanced stance helps you change direction after receiving. Keep your knees relaxed and take a first touch that leaves you ready to move.",lesson:'movement'},
 {id:'roof',name:'Café rooftop',x:200,y:18.23,z:136.5,kind:'hidden',clue:'Climb above the café to see the whole pitch.',detail:'Follow both stair flights. A small tactics board hides the rooftop ball.',teaching:"Recognise the team lines. Look for defenders, midfielders and attackers when watching from above. Useful team shape connects those groups so the ball can move through the pitch.",lesson:'width'},
 {id:'ferry',name:'Ferry approach',x:228,y:0,z:198,kind:'kick',clue:'The matchday ferry has a parcel waiting on shore.',detail:'Kick the target on the dock parcel west of the boarding ramp.',teaching:"Weight your pass. The weight of a pass means how firmly it is played. Aim to reach your teammate before pressure arrives while leaving them a ball they can control.",lesson:'support'},
 {id:'beach',name:'Beach sidelines',x:57,y:0,z:198,kind:'kick',clue:'Near the sand court, football practice stays outside the lines.',detail:'Find the low target west of the volleyball court and send a ground pass into it.',teaching:"Keep it on the ground. A ground pass avoids the extra challenge of controlling a bouncing ball. For a short pass, try striking through the middle of the ball with a steady ankle.",lesson:'support'},
 {id:'north',name:'North beach clearing',x:135,y:0,z:-204,kind:'landing',clue:'A padded delivery waits near the northern ramps.',detail:'Look south of the north beach ramp lane. Land on its padded lid or kick its target.',teaching:"Arrive with the pass. A useful run is about timing as well as speed. Watch the passer, then arrive in the open space as the ball reaches you.",lesson:'movement'},
 {id:'wall-right',name:'Soccer wall · right target',x:162,y:0,z:-27.7,kind:'kick',wall:{x:162,y:1.02,z:-29.27},clue:'The soccer wall has a second surprise.',detail:'Kick the right target to break it open. Walk forward to collect the revealed ball.',teaching:"Train both feet. Being comfortable with either foot gives you more passing choices. Try five gentle passes with each foot, aiming at the same small target.",lesson:'support'},
 {id:'garden-cafe',name:'Garden Café patio',x:221,y:0,z:-35,kind:'kick',clue:'Look beside the café where the community garden begins.',detail:'A marked training parcel waits south of the outdoor seating.',teaching:"Pass, then move. Your job continues after you release the ball. Move to a fresh angle so the teammate receiving your pass has a return option.",lesson:'movement'},
 {id:'market-north',name:'Northern market stalls',x:222,y:0,z:42,kind:'kick',clue:'The first market stalls have more than produce.',detail:'Find the football-marked parcel on the promenade between the northern stalls.',teaching:"Update your picture. Players keep moving after your first look. Scan again while the ball travels so your next decision matches the space that is available now.",lesson:'support'},
 {id:'school',name:'Palm Street Futsal · west target',x:-1,y:0,z:49,kind:'kick',wall:{x:-1,y:6.7,z:46.95,high:true,round:true},clue:'Look up at the west end of the Palm Street Futsal sign.',detail:'From the south walkway, face the round football target to the left of the Palm Street Futsal sign. Hold Kick for a high shot, then collect the ball that drops onto the walkway.',teaching:"A first touch with purpose. Your first touch can prepare your next action. Try receiving slightly into space instead of stopping the ball directly under your feet.",lesson:'movement'},
 {id:'northwest',name:'Northwest beach',x:-34,y:0,z:-210,kind:'hidden',clue:'Follow the north shore toward its quieter western end.',detail:'Find the small equipment bag south of the beach umbrellas.',teaching:"Open your body. Receiving side-on can help you see both the passer and your next option. Check for pressure first, then turn your body toward the space you want to use.",lesson:'support'},
 {id:'pier',name:'Southern pier',x:108,y:0,z:211,kind:'hidden',clue:'Look where the wooden pier faces the open water.',detail:'Check the matchday bag on the southern boardwalk, below the pier cafés.',teaching:"Switch the play. Switching play moves the ball from one side of the pitch to the other. Look across the field when defenders crowd your side; a teammate may have more room there.",lesson:'width'},
 {id:'club',name:'Teal pickup truck',x:48,y:.98,z:-40,kind:'hidden',truck:7,clue:'A teal pickup is touring the island roads.',detail:'Fly near the pickup until its outline turns green, then choose Walk. You will glide into the bed and collect the ball automatically. Release the joystick after landing, then use it to steer across roads, grass and open plazas. Tap Hop off to leave.',teaching:"Meet a moving teammate. A pass into space lets a teammate receive while running. Look at their direction and pace, then choose a spot ahead of them rather than where they were.",lesson:'movement'},
 {id:'dock-entry',name:'Gold pickup truck',x:218,y:.98,z:110,kind:'hidden',truck:8,clue:'Watch for a gold pickup exploring the island roads.',detail:'Look for the green outline near the truck and choose Walk. The landing assist follows the moving pickup and guides you into its bed. Release the joystick after landing, then steer across roads, grass and open plazas. Tap Hop off to leave, or choose Flight to take off.',teaching:"Support from behind. A teammate behind the ball provides a way out when forward routes close. Offer a clear return pass so your team can keep possession and choose a new route.",lesson:'support'},
 {id:'west-market',name:'West market courtyard',x:-62,y:0,z:59,kind:'landing',clue:'The western courtyard has a soft football delivery.',detail:'Land on its padded box or kick the target, away from the café tables.',teaching:"Change your pace. A change of speed can help create separation from a marker. Try a short slow approach followed by a quick move into a clear passing lane.",lesson:'movement'},
 {id:'library',name:'Library square',x:87,y:0,z:-100,kind:'landing',clue:'A training delivery waits near the park library.',detail:'Check the east side of Library Square. Land on the pad or kick its target.',teaching:"Change your direction. Running straight is not always the best way to get free. Move one way, plant your foot, then cut toward a different space where the passer can find you.",lesson:'movement'},
 {id:'store-roof',name:'Store rooftop',x:89,y:7.43,z:-58,kind:'hidden',clue:"Look above the place where you choose your gear.",detail:"Fly onto the Store roof. Look for a small training bag away from the edge.",teaching:"Use the far foot. Receiving with the foot farther from pressure can help protect the ball. Scan first and choose the foot that lets your first touch move away from the defender.",lesson:'movement'},
 {id:'arcade-roof',name:'Arcade rooftop',x:107,y:6.43,z:-58,kind:'hidden',clue:"The arcade has a surprise above its games.",detail:"Explore the middle of the Arcade roof.",teaching:"Give-and-go. A give-and-go uses a pass followed by a run to receive the return. After passing, move beyond the defender into a lane your teammate can reach.",lesson:'movement'},
 {id:'junior-roof',name:'Junior Club rooftop',x:137,y:7.23,z:-177,kind:'hidden',clue:"Head north to the youngest club on the island.",detail:"Fly onto the Junior Club roof and look around before moving.",teaching:"Make a triangle. Three teammates at different angles can form a passing triangle. Avoid standing directly behind another player, where one defender could block both of you.",lesson:'movement'},
 {id:'books-roof',name:'West End Books rooftop',x:-64,y:10.23,z:-109,kind:'hidden',clue:"A western rooftop has a new chapter to discover.",detail:"Explore the roof of West End Books, west of the park.",teaching:"Look between the lines. Defensive lines are groups of opponents across the pitch. Space between midfield and defence can be useful, but check your shoulders before receiving there.",lesson:'movement'},
 {id:'museum-roof',name:'Museum rooftop',x:168,y:5.23,z:181,kind:'hidden',clue:"Football history has a view of the sea.",detail:"Land on the middle of the History Museum roof to find the training bag.",teaching:"Create space for someone else. An off-ball run can help even if you never receive the pass. By taking a marker with you, you may open a lane for a teammate.",lesson:'movement'},
 {id:'grass-west',name:'West End grass hatch',x:-74,y:0,z:-109,kind:'landing',grass:true,clue:"Look down from West End Books for a marked patch of grass.",detail:"Drop from the west edge of the bookshop roof onto the gold-marked grass lid. Landing opens it; kicks do not.",teaching:"Lose your marker. A short movement away before checking back can create room to receive. Watch the passer so your return run happens while they can still find you.",lesson:'movement'},
 {id:'grass-junior',name:'Junior Club grass hatch',x:137,y:0,z:-187,kind:'landing',grass:true,clue:"A landing mark hides in the grass north of Junior Club.",detail:"Step off the north edge of the Junior Club roof and aim for the gold football on the grass.",teaching:"Time a run behind. A run behind a defender works best when the passer is ready to release the ball. Check the defensive line and time your movement to stay onside.",lesson:'movement'},
 {id:'grass-garden',name:'Garden House grass hatch',x:100,y:0,z:-138,kind:'landing',grass:true,clue:"Look just west of Garden House for a football in the grass.",detail:"Drop from the west edge of Garden House onto the marked grass lid to open the buried box.",teaching:"The third-player option. Sometimes the clearest route uses another teammate. Player A passes to B, then B finds C in a better position; watch how C moves before the second pass.",lesson:'movement'},
 {id:'grass-community',name:'Community Hall grass hatch',x:191,y:0,z:-177,kind:'landing',grass:true,clue:"The Community Hall has a secret beside its eastern wall.",detail:"Fall from the east roof edge onto the gold-marked grass patch. Collect the ball after the lid opens.",teaching:"Move out of the shadow. Standing directly behind a defender hides you from the passer. Step to one side until a clear line connects you to the ball.",lesson:'movement'},
 {id:'ramp-gap',name:'Rooftop finale jump',x:47.8333333333,y:16.0,z:-20.3,kind:'hidden',ramp:'roof-ramp-finale',clue:"The ball floats between the third rooftop ramp and the fourth landing ramp.",detail:"Ride a bike, scooter or moped along the rooftop ramp chain. The third ramp launches you through this ball toward the landing ramp.",teaching:"React to the second ball. A block or rebound changes where the ball is going. Watch its new direction and move toward the space it will reach, rather than following the original shot.",lesson:'movement'},
 {id:'wall-books',name:'West End Books high target',x:-54.2,y:0,z:-109,kind:'kick',wall:{x:-56.6,y:4.3,z:-109,high:true,facing:'east'},clue:'Look up at the east wall of West End Books.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Choose the pass height. A lofted pass can travel over an opponent, while a ground pass is often easier to control. Choose the height that fits the space and your teammate’s position.",lesson:'support'},
 {id:'wall-nova',name:'Rua Nova high target',x:43.2,y:0,z:-134,kind:'kick',wall:{x:41.9,y:5.56,z:-134,high:true,facing:'east'},clue:'Look up at the east wall of Rua Nova.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"First-time passing. A one-touch pass can move the ball before defenders adjust. Decide where it should go before it arrives; take an extra touch when you need control.",lesson:'support'},
 {id:'wall-garden',name:'Garden House high target',x:112,y:0,z:-129.8,kind:'kick',wall:{x:112,y:3.04,z:-131.38,high:true},clue:'Look up at the south wall of Garden House.',detail:'Find the raised box with a muted brass football mark. Face the wall and use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Cushion a firm pass. Give slightly with your receiving foot at contact to soften the ball’s arrival. Aim to keep it close enough for your next action.",lesson:'support'},
 {id:'wall-library',name:'Local Library high target',x:220,y:0,z:-117,kind:'kick',wall:{x:217.9,y:2.83,z:-117,high:true,facing:'east'},clue:'Look up at the east wall of Local Library.',detail:'Find the raised box with a muted brass football mark. Stand east of the building and face the wall. Use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Request a receiving foot. Help the passer aim by pointing or calling for the foot you want to use. Choose the side away from pressure when that gives you safer control.",lesson:'support'},
 {id:'wall-arts',name:'Arts Wing high target',x:72,y:0,z:57.2,kind:'kick',wall:{x:72,y:4.72,z:55.62,high:true},clue:'Look up at the south wall of Arts Wing.',detail:'Find the raised box with a muted brass football mark. Face the wall and use a high shot or wall juggle. The ball drops to the ground after the box breaks.',teaching:"Disguise your pass. Players can make one passing option look likely before choosing another. Try looking at one target, then passing accurately to a second without rushing your technique.",lesson:'support'},
 {"id":"wall-community","name":"Pier Bakery · hidden wall target","x":107.5,"y":0,"z":181,"kind":"kick","wall":{"x":105.4,"y":3.8,"z":181,"high":true,"facing":"east"},"clue":"Look closely at the east wall of Pier Bakery. A small weathered futbol mark blends into the wall.","detail":"Approach Pier Bakery from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Use a curved run. A curved run changes your angle while you move forward. It can help you stay available for a pass instead of running directly behind a defender.","lesson":"support"},
 {id:'parcel-north',name:'North shore delivery',x:80,y:0,z:-205,kind:'kick',clue:'Explore the north shore delivery for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"Keep useful distances. Too close and one defender may cover two attackers; too far and the pass may be difficult. Adjust your support distance to the pressure and the passer’s options.",lesson:'support'},
 {id:'parcel-west',name:'Western promenade',x:-80,y:0,z:25,kind:'kick',clue:'Explore the western promenade for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"The ball travels faster. A pass can move play across an area faster than one player dribbling the whole way. Look for a teammate in a better position before deciding to carry the ball.",lesson:'support'},
 {id:'parcel-school',name:'Palm Street Futsal · east target',x:23,y:0,z:49,kind:'kick',wall:{x:23,y:6.7,z:46.95,high:true,round:true},clue:'The parking P points to a second target above it.',detail:'Stand south of the parking garage and look above the P marking, to the right of the Palm Street Futsal sign. Hold Kick for a high shot at the round target, then collect the ball on the walkway.',teaching:"Talk early. A short call before the pass arrives can help a teammate decide. Use clear information such as “time” when they have space or “man on” when pressure is close.",lesson:'support'},
 {id:'parcel-south',name:'South beach delivery',x:143,y:0,z:204,kind:'kick',clue:'Explore the south beach delivery for a football-marked box.',detail:'Find a clear passing lane to the gold target and kick the box open. Collect the ball that appears.',teaching:"React when possession changes. After losing the ball, the nearest player can delay the attacker while teammates recover toward their goal. Work together rather than all chasing the same opponent.",lesson:'support'},
 {"id": "high-humanities", "name": "Humanities · high spacing target", "x": 111.8, "y": 0, "z": 25.4, "kind": "kick", "wall": {"x": 111.8, "y": 10.5, "z": 22.9, "high": true, "round": true}, "clue": "Look high on the south face of Humanities. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Humanities. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Give your team depth. Useful spacing goes forward and backward as well as sideways. Offer a player ahead of the ball to stretch the defence and another behind it for a safe return.", "lesson": "support"},
 {"id":"high-school","name":"Dining Hall · hidden wall target","x":81.8,"y":0,"z":105,"kind":"kick","wall":{"x":79.4,"y":8.5,"z":105,"high":true,"round":true,"facing":"east"},"clue":"Look closely at the east wall of Dining Hall. A small weathered futbol mark blends into the wall.","detail":"Approach Dining Hall from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Stagger your support. Two teammates on the same horizontal line can be covered together. Stand at different depths and angles so the passer can choose a short option or a forward one.","lesson":"support"},
 {"id": "high-classrooms", "name": "Eastern Classrooms · high spacing target", "x": 165.8, "y": 0, "z": 25.4, "kind": "kick", "wall": {"x": 165.8, "y": 10.5, "z": 22.9, "high": true, "round": true}, "clue": "Look high on the south face of Eastern Classrooms. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Eastern Classrooms. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Defend together. Compact defending means reducing the useful gaps between teammates, not all chasing the ball. The closest player presses while the next players cover the space behind and inside.", "lesson": "support"},
 {"id": "high-visitor", "name": "Park Visitor Centre · high spacing target", "x": -1, "y": 0, "z": -124.9, "kind": "kick", "wall": {"x": -1, "y": 10.5, "z": -126.6, "high": true, "round": true}, "clue": "Look high on the south face of Park Visitor Centre. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Park Visitor Centre. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Stretch the last line. A high attacker can make defenders protect the space behind them. That can create room underneath for a teammate; keep the high position useful and onside.", "lesson": "width"},
 {"id": "high-mercado", "name": "Park Library \u00b7 hidden wall target", "x": 77.5, "y": 0, "z": -137.3, "kind": "kick", "wall": {"x": 77.5, "y": 5.8, "z": -139.6, "high": true, "round": true}, "clue": "Look closely at the south wall of Park Library. A small weathered futbol mark blends into the wall.", "detail": "Approach Park Library from the south. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.", "teaching": "Make a two-against-one. An overload is a local numbers advantage. Keep enough distance from your teammate that one defender cannot close both of you, then pass when the defender commits.", "lesson": "support"},
 {"id":"high-nova","name":"School Offices · hidden wall target","x":200,"y":0,"z":61.3,"kind":"kick","wall":{"x":200,"y":10.5,"z":58.9,"high":true,"round":true},"clue":"Look closely at the south wall of School Offices. A small weathered futbol mark blends into the wall.","detail":"Approach School Offices from the south. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Share the channels. Think of the pitch as outside, inside and central lanes. If a teammate stays wide, an inside supporting position can give them a diagonal pass without taking their space.","lesson":"width"},
 {"id": "high-deli", "name": "Corner Deli · high spacing target", "x": -54.2, "y": 0, "z": -55, "kind": "kick", "wall": {"x": -56.6, "y": 7.1, "z": -55, "high": true, "round": true, "facing": "east"}, "clue": "Look high on the east face of Corner Deli. A football target marks a lesson about team spacing.", "detail": "Find the round muted brass-rimmed target high above Corner Deli. Back away along the clear east approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Keep the triangle alive. A passing triangle is not a fixed spot to stand. When the ball moves, adjust your angle so the new ball carrier still has two clear options.", "lesson": "movement"},
 {"id":"high-apartments","name":"The Grocer · hidden wall target","x":-54.2,"y":0,"z":2,"kind":"kick","wall":{"x":-56.6,"y":7.5,"z":2,"high":true,"round":true,"facing":"east"},"clue":"Look closely at the east wall of The Grocer. A small weathered futbol mark blends into the wall.","detail":"Approach The Grocer from the east. Look for a small muted target high on the wall. Back away and hold Kick for a high shot, then collect the ball on the ground below.","teaching":"Switch through support. If the direct cross-field pass is blocked, a supporting teammate behind the ball may have a clearer angle. Use two connected passes to reach the far side.","lesson":"width"},
 {"id": "high-clubgrounds", "name": "Club Grounds · high spacing target", "x": 159, "y": 0, "z": -167.2, "kind": "kick", "wall": {"x": 159, "y": 7.1, "z": -169.6, "high": true, "round": true}, "clue": "Look high on the south face of Club Grounds. A football target marks a lesson about team spacing.", "detail": "Find the round brass-rimmed target high above Club Grounds. Back away along the clear south approach, hold Kick for a long, high shot, then collect the ball from the ground in front of the building.", "teaching": "Leave space for the next player. If a teammate is arriving into your pocket, move to another useful position. One player leaving and another arriving can keep a small space usable.", "lesson": "movement"},
 {"id": "high-promenade", "name": "Cafe By The Sea \u00b7 hidden wall target", "x": 211.8, "y": 0, "z": 136.5, "kind": "kick", "wall": {"x": 209.4, "y": 14, "z": 136.5, "high": true, "round": true, "facing": "east"}, "clue": "Look closely at the east wall of the tall north wing at Cafe By The Sea.", "detail": "Stand on the eastern boardwalk and look high on the north wing for a small weathered futbol mark. Back away, hold Kick for a high shot, and collect the ball below.", "teaching": "Protect the route to goal. When defending, recover between your opponent and your goal. Adjust as the attacker moves while keeping sight of the ball; spacing matters without possession too.", "lesson": "support"},
 {"id": "sky-north", "name": "North shore sky", "x": 62, "y": 60, "z": -207, "kind": "hidden", "parachute": true, "clue": "Look above north shore. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Place your finish. Look for the open corner instead of aiming straight at the keeper. Use a controlled shot toward the open corner. Accuracy matters more than power.", "lesson": "movement"},
 {"id": "sky-west", "name": "West coast sky", "x": -50, "y": 80, "z": -76, "kind": "hidden", "parachute": true, "clue": "Look above west coast. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "A keeper\u2019s ready stance. Set your feet apart with soft knees and hands ready before the shot. A balanced ready stance helps the keeper push sideways toward the ball.", "lesson": "movement"},
 {"id": "sky-plaza", "name": "Plaza sky", "x": 112, "y": 120, "z": -12, "kind": "hidden", "parachute": true, "clue": "Look above plaza. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Shield without pushing. Turn your body between the opponent and the ball, keeping it within playing distance. Keep your balance and arms relaxed. Protect the ball without shoving the opponent.", "lesson": "movement"},
 {"id": "sky-east", "name": "Garden sky", "x": 219, "y": 100, "z": 22, "kind": "hidden", "parachute": true, "clue": "Look above garden. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Reset after a mistake. Take one slow breath and let your shoulders relax. Choose one helpful next action, such as encouraging a teammate. One mistake does not define your game.", "lesson": "movement"},
 {"id": "sky-pier", "name": "Pier sky", "x": 119, "y": 140, "z": 195, "kind": "hidden", "parachute": true, "clue": "Look above pier. A ball floats away from the rooftops.", "detail": "Use your flight launch to rise above this high floating ball, then steer down through it with your parachute open. Only an open parachute can collect it; you have room around it to line up your descent.", "teaching": "Respect after a challenge. When play has stopped and it is safe, check whether they are okay. Offer a hand if they want help. Competing hard and showing care belong together.", "lesson": "movement"},
];
export type CoinProgress={version:3;allCostumesUnlocked?:boolean;rewardUnlocked:boolean;revealed:string[];collected:string[];hint:string|null;celebrated:boolean};
export const emptyCoinProgress=():CoinProgress=>({version:3,rewardUnlocked:false,revealed:[],collected:[],hint:null,celebrated:false});
const ids=new Set(COIN_QUEST.map(c=>c.id));
// The original forty IDs stay in their original order. Old completed saves keep their earned outfit.
const originalRewardIds=COIN_QUEST.slice(0,40).map(spot=>spot.id);
export function sanitizeCoinProgress(raw:unknown):CoinProgress{
 const r=raw as (Omit<Partial<CoinProgress>,'version'>&{version?:number})|null;if(!r||typeof r!=='object')return emptyCoinProgress();
 const clean=(v:unknown)=>Array.isArray(v)?[...new Set(v.filter((id):id is string=>typeof id==='string'&&ids.has(id)))]:[];
 const collected=clean(r.collected),legacyReward=(r.version??1)<2&&originalRewardIds.every(id=>collected.includes(id));
 const rewardUnlocked=r.rewardUnlocked===true||legacyReward||collected.length===COIN_QUEST.length;
 const allCostumesUnlocked=r.allCostumesUnlocked===true||((r.version??1)<3&&COIN_QUEST.slice(0,50).every(s=>collected.includes(s.id)))||collected.length===COIN_QUEST.length;
 return{version:3,allCostumesUnlocked,rewardUnlocked,revealed:[...new Set([...clean(r.revealed),...collected])],collected,hint:typeof r.hint==='string'&&ids.has(r.hint)?r.hint:null,celebrated:r.celebrated===true&&collected.length===COIN_QUEST.length};
}
export const coinRewardEarned=(s:CoinProgress)=>s.rewardUnlocked===true||s.collected.length===COIN_QUEST.length;
export function applyCoinEvent(s:CoinProgress,id:string,kind:'reveal'|'collect'):CoinProgress{if(!ids.has(id))return s;const spot=COIN_QUEST.find(c=>c.id===id)!;if(kind==='collect'&&spot.kind!=='hidden'&&!s.revealed.includes(id))return s;if(s[kind==='collect'?'collected':'revealed'].includes(id))return s;return{...s,revealed:[...new Set([...s.revealed,id])],collected:kind==='collect'?[...s.collected,id]:s.collected,hint:kind==='collect'&&s.hint===id?null:s.hint};}

export const allCostumesEarned=(s:CoinProgress)=>s.allCostumesUnlocked===true||COIN_QUEST.every(spot=>s.collected.includes(spot.id));
