import type {NpcDefinition} from './npcDialogues';
import {BEACH_COURT as K,COURT_SCOREBOARD,CAY_PLAZA} from './coralCay';
/**
 * Coral Cay islanders (Sep 29 2026). Every fact below was checked on Sep 29 2026 against:
 *  - FIFA Beach Soccer Laws of the Game 2024-25 (Law 1 pitch/flags/goals, 2 ball, 3 players/substitutions, 4 equipment,
 *    7 duration, 10 extra time/penalties, 12 goalkeeper and overhead kicks, 13 free kicks, 15 kick-in):
 *    https://www.the-aiff.com/media/uploads/2024/11/Beach-Soccer-Laws-of-the-Game-2024-25.pdf
 *  - FIFA, "Amendments made to Beach Soccer Laws of the Game" (5-kick shoot-out since 2021) and "Brief guide to beach
 *    soccer rules" (no draws in FIFA competitions): inside.fifa.com
 *  - FIFA Training Centre, 2024 Beach Soccer World Cup analysis: 37 bicycle-kick goals, 17% of all goals.
 *  - Lejeune et al. 1998, J Exp Biol 201 (sand running ≈1.6× the energy cost of firm ground); Binnie et al. 2014,
 *    J Sports Sci 32 (sand training: lower impact, less muscle soreness than grass).
 *  - FIFA Beach Soccer World Cup history (first FIFA edition 2005, Copacabana, France beat Portugal on penalties; Brazil
 *    has the most titles) — cross-checked on Wikipedia only, so worded without a title count.
 *  - Cape Verde's nickname Tubarões Azuis (Blue Sharks) and 2026 as its first World Cup: CAF, "Cape Verde name historic
 *    World Cup squad as Blue Sharks prepare for debut" (cafonline.com); Olympics.com, "Africa at FIFA World Cup 2026".
 *  - Manta rays (Nia, Sep 30 2026): NOAA Fisheries, "Giant Manta Ray" (fisheries.noaa.gov/species/giant-manta-ray):
 *    filter feeders on zooplankton, no stinging barb (unlike stingrays), harmless to people, and they breach (leap out
 *    of the water). The first-touch link is a coaching metaphor, not a claim about manta biology.
 * Coaching tips (how to practise, safety) are advice, not rules, and are phrased that way.
 * Farm (fuelling for football), kept to general, positive guidance, with no diet rules and nothing about weight:
 *  - FIFA, "Nutrition for Football" (digitalhub.fifa.com): carbohydrate foods are the main fuel for football.
 *  - Better Health Channel (Victoria, AU), "Sporting performance and food": a high-carbohydrate meal about 3–4 hours
 *    before exercise, a small snack 1–2 hours before; drink fluids before, during and after.
 *  - Sports Dietitians Australia, "What to eat before, during and post exercise": choose familiar foods high in
 *    carbohydrate before exercise; recover afterwards with carbohydrate, protein and fluids.
 * Hostel (travelling to play): sleep amounts from the American Academy of Sleep Medicine consensus (Paruthi et al.,
 *  J Clin Sleep Med 2016; endorsed by the American Academy of Pediatrics): 6–12 years 9–12 h, 13–18 years 8–10 h per 24 h;
 *  a calm, screen-free wind-down before bed is standard sleep-hygiene advice (CDC, "About Sleep"). Away days, team spirit
 *  and respect for hosts are values, phrased as advice.
 */
export const CORAL_CAY_NPCS:NpcDefinition[]=[
 {id:'cay-marina',name:'Coach Marina',role:'Beach soccer coach',pursuit:'COACHING BEACH SOCCER',x:K.x,z:K.z+17.8,character:'female',face:'deep',clothing:'coast',greeting:'Welcome to Sharks Beach! You will have spotted our friendly sharks along the causeway on the way here. We play barefoot here: beach soccer is five against five on sand, and the ball hardly ever rolls smoothly. What would you like to know?',topics:[
  {id:'format',question:'How many players are on a beach soccer team?',answer:'Five on the sand, and one of them is the goalkeeper. Substitutions are unlimited: players can swap at any time, even while the ball is moving, through the zone in front of the benches.',followUp:{question:'Why do teams swap so often?',answer:'Sprinting on sand is tiring. Rotating players keeps fresh legs on the pitch for pressing and running.'}},
  {id:'time',question:'How long is a match?',answer:'Three periods of 12 minutes, with breaks of no more than 3 minutes between them.',followUp:{question:'What happens if it is a draw?',answer:'In FIFA tournaments someone must win. If it is level, there are 3 minutes of extra time. Still level? A penalty shoot-out: five kicks each, then sudden death.'}},
  {id:'golden',question:'Does the first goal in extra time win?',answer:'No, there is no golden goal. Extra time lasts the full 3 minutes, even if someone scores.',followUp:{question:'Can you score from anywhere?',answer:'Not straight from a kick-off, a kick-in or a goal clearance. And there is no offside, so attackers can wait anywhere on the pitch.'}}
 ]},
 {id:'cay-kofi',name:'Kofi',role:'Beach soccer goalkeeper',pursuit:'GUARDING THE WEST GOAL',x:K.x-22,z:K.z+2,workYaw:Math.PI/2,character:'male',face:'warm',clothing:'sunset',greeting:'I guard the west goal. On sand a keeper has to be quick with their hands and their feet. Ask me about keeping!',topics:[
  {id:'four',question:'How long can a keeper hold the ball?',answer:'Only 4 seconds in their own half. Hold it longer and the other team gets a free kick from the centre of the pitch.',followUp:{question:'Can a keeper throw it into the other goal?',answer:'A throw straight into the other goal does not count: it becomes a goal clearance. A quick, accurate throw to a teammate is still a great way to attack.'}},
  {id:'punt',question:'Can the keeper kick the ball out of their hands?',answer:'No. A beach soccer keeper may not drop the ball and kick it before it touches the sand, so there are no punts or volleys from the hands.',followUp:{question:'So how do keepers start attacks?',answer:'With fast throws. A throw to a free teammate can start a counter-attack before the other team is back in position.'}},
  {id:'goal',question:'How big is a beach soccer goal?',answer:'5.5 metres wide and 2.2 metres high. An 11-a-side goal is bigger: 7.32 metres by 2.44 metres.',followUp:{question:'Does a smaller goal change shooting?',answer:'Placement matters. With a smaller target and a bouncing ball, a shot you control is usually better than one you just hit hard.'}}
 ]},
 {id:'cay-lua',name:'Lua',role:'Beach keep-ups',pursuit:'KEEP-UPS ON SAND',x:K.x+8,z:K.z-17.5,freestyle:1,freestyleClip:'0i-uapFLwAM',workYaw:-.6,character:'female',face:'light',clothing:'sunset',greeting:'Sand makes a rolling ball slow down or hop, so I practise keeping it up before it lands. Soft touches with both feet!',topics:[
  {id:'air',question:'Why practise keep-ups on the beach?',answer:'Soft, uneven sand can slow a rolling ball or make it hop. Many beach players lift the ball with a little flick and play it in the air, so gentle keep-ups build that control.',followUp:{question:'How do I start?',answer:'One touch and a catch, then two touches. Point your toes up a little and lift gently so the ball stays close.'}}
 ]},
 {id:'cay-tavi',name:'Tavi',role:'Overhead-kick practice',pursuit:'KNEE TOUCHES FOR OVERHEAD KICKS',x:K.x-8,z:K.z-17.5,freestyle:2,freestyleClip:'ZFzAz084LTk',workYaw:.6,character:'male',face:'deep',clothing:'classic',greeting:'I use knee touches to set the ball up for an overhead kick. In beach soccer the rules even protect players who try them!',topics:[
  {id:'bicycle',question:'Are bicycle kicks allowed?',answer:'Yes! The beach soccer laws say scissor kicks and overhead kicks are part of the game and must be protected, so an opponent may not unfairly stop a player trying one.',followUp:{question:'Do they really score many goals?',answer:'At the 2024 FIFA Beach Soccer World Cup, FIFA counted 37 goals from bicycle kicks: about 17% of all the goals.'}},
  {id:'safe',question:'How should I practise an overhead kick?',answer:'Only on soft sand, with a coach, and away from other players. Learn to land on your back and arms first, then add the kick slowly.',followUp:{question:'What should I watch in a real match?',answer:'Watch how the player sets the ball up first, often with a flick or a knee touch, before the overhead kick.'}}
 ]},
 {id:'cay-sol',name:'Tiago',role:'Coconut Café server',pursuit:'SERVING COLD DRINKS',x:543,z:-167.8,activity:'serving',workYaw:0,character:'male',face:'light',clothing:'coast',greeting:'Cold drinks for tired legs! Everyone from the court stops here after a game. Want a football chat?',topics:[
  {id:'sand',question:'Why is running on sand so tiring?',answer:'Your feet sink and slip, so every step takes more work. Scientists measured that running on sand uses about 1.6 times the energy of running on a firm surface.',followUp:{question:'Is sand bad for my legs, then?',answer:'It is harder work but softer. A study found sand training had lower impact and caused less muscle soreness than training on grass.'}},
  {id:'sun',question:'How do I look after myself playing in the sun?',answer:'Drink water, take breaks in the shade and wear sun cream. Ask an adult before playing if the sand is very hot.',followUp:{question:'Why do beach games have breaks?',answer:'A beach match has three periods, with short breaks between them: a good moment to drink and hear the coach.'}}
 ]},
 {id:'cay-reef',name:'Reef',role:'Surf Shop owner',pursuit:'WAXING SURFBOARDS',x:565,z:-167.6,character:'female',face:'warm',clothing:'classic',greeting:'Boards for the waves, bare feet for the pitch! Beach soccer players do not wear boots at all. Ask me why!',topics:[
  {id:'barefoot',question:'Do beach soccer players really play barefoot?',answer:'Yes. Footwear is not allowed. Players may wear stretchy foot or ankle wraps, as long as they do not cover the heels or toes.',followUp:{question:'What else can players wear?',answer:'Sports glasses are allowed, and goalkeepers may wear long trousers and gloves. Everything must be safe for the other players.'}},
  {id:'ball',question:'Is the beach soccer ball different?',answer:'It is the same size as a normal football, size 5, but a bit lighter and much softer, because it is pumped to a lower pressure.',followUp:{question:'How do I control a soft, bouncing ball?',answer:'Cushion it: meet the ball with a relaxed foot and let it drop close to you, ready for your next touch.'}}
 ]},
 {id:'cay-ana',name:'Ana',role:'Beach soccer historian',pursuit:'KEEPING THE COURT HISTORY',x:COURT_SCOREBOARD.x+7.5,z:COURT_SCOREBOARD.front+2,character:'female',face:'deep',clothing:'sunset',greeting:'I keep the scores and the history of this court. Did you know FIFA’s Beach Soccer World Cup began on a famous beach in Brazil?',topics:[
  {id:'history',question:'When did the Beach Soccer World Cup start?',answer:'The first FIFA Beach Soccer World Cup was played in 2005 on Copacabana beach in Rio de Janeiro. France won it, beating Portugal on penalties.',followUp:{question:'Which country has won it the most?',answer:'Brazil has won more Beach Soccer World Cup titles than any other country.'}},
  {id:'flags',question:'Why are there flags around the pitch?',answer:'The lines are blue tape on the sand, but the halfway line and the penalty-area line are imaginary. Red flags mark halfway and the corners; yellow flags mark the penalty area, 9 metres from each goal.',followUp:{question:'Is there a line between the goalposts?',answer:'No. Beach soccer has no painted line between the posts, and no painted centre spot either.'}}
 ]},
 {id:'cay-pita',name:'Pita',role:'Plaza care crew',pursuit:'SWEEPING SAND OFF THE PLAZA',x:587,z:-167,activity:'sweeping',workYaw:0,character:'male',face:'warm',clothing:'classic',greeting:'I sweep the sand off the plaza so nobody slips. Then it is my turn on the court. Ask me about restarts!',topics:[
  {id:'free',question:'How do free kicks work in beach soccer?',answer:'If you are fouled, you usually take the free kick yourself, and the other team may not build a wall. You may even make a little sand mound to lift the ball.',followUp:{question:'How quickly must I take it?',answer:'Within 4 seconds. Beach soccer restarts are fast, so look up and decide early.'}}
 ]},
 {id:'sandbar-nia',name:'Nia',role:'Starfish Sandbar lifeguard',pursuit:'WATCHING THE WATER',x:346,z:-219,character:'female',face:'light',clothing:'coast',greeting:'This sandbar is my lookout. I watch the swimmers, the friendly sharks along the causeway, the manta rays gliding round the sandbars and the beach soccer players on their way to the cay. Everyone plays barefoot out here!',topics:[
  {id:'sharks',question:'Are those sharks safe?',answer:'Our island sharks are friendly and stay out in the deep water. Football has sharks too: Cape Verde’s national team is nicknamed the Tubarões Azuis, the Blue Sharks, and 2026 was their first World Cup.',followUp:{question:'What can a beach player learn from a shark?',answer:'Keep watching behind you! Beach soccer has no offside, so an attacker can lurk anywhere, just like a shark. Check your shoulder and talk to your teammates.'}},
  {id:'mantas',question:'What are the big flat fish gliding round the sandbar?',answer:'Manta rays! They are harmless to people: they have no stinging barb and eat tiny plankton. They swim by slowly flapping their huge fins like wings, and sometimes one leaps right out of the water.',followUp:{question:'What can a footballer learn from a manta?',answer:'Watch how smoothly they glide: small, gentle wing movements keep them steady and in control. Your first touch works the same way. A soft, small touch keeps the ball close, so you stay in control too.'}},
  {id:'feet',question:'What can protect my feet on the sand?',answer:'Beach soccer laws allow stretchy wraps on the feet or ankles, as long as the heels and toes stay uncovered. Boots and shoes are not allowed.',followUp:{question:'How do I make the sand safe to play on?',answer:'Walk the pitch first and look for shells, litter or hidden holes. Tell an adult about anything sharp or unsafe.'}},
  {id:'subs',question:'What if I get tired during a game?',answer:'Beach soccer has rolling substitutions: you can come off and a teammate can come on at any time, through the substitution zone.',followUp:{question:'Can I go back on later?',answer:'Yes. Substitutions are unlimited, so players can come back on as often as the team needs.'}}
 ]},
 {id:'sandbar-joa',name:'Joa',role:'Turtle Sandbar restart coach',pursuit:'PRACTISING KICK-INS',x:449,z:-101,character:'male',face:'light',clothing:'sunset',greeting:'I practise restarts out here. When the ball goes out on the side in beach soccer, you get to choose how to bring it back!',topics:[
  {id:'kickin',question:'Kick-in or throw-in?',answer:'Your choice! You can kick the ball in or throw it in from the touchline. You have 4 seconds, and opponents must stand at least 5 metres away.',followUp:{question:'Can I score straight from a kick-in?',answer:'No. If it goes straight into the goal, it becomes a goal clearance for the other team. Aim for a teammate instead.'}},
  {id:'offside',question:'Is there offside in beach soccer?',answer:'No offside! Attackers can stand anywhere, so defenders must keep talking and watch who is free.',followUp:{question:'How do defenders cope?',answer:'Stay between your player and your goal, and tell teammates who you are marking. Clear talking covers the gaps.'}}
 ]},
 {id:'cay-runner',name:'Kalea',role:'Causeway runner',pursuit:'SAND SPRINTS',x:CAY_PLAZA.x+7,z:CAY_PLAZA.z+9,travel:'run',character:'female',face:'warm',clothing:'coast',greeting:'I run the causeway, then do short sprints on the beach. Sand makes every step harder work!',topics:[
  {id:'sprint',question:'How do beach players train on sand?',answer:'Short sprints with rests between them. Running on sand takes much more energy than on a firm path, so quality beats distance.',followUp:{question:'Why short sprints?',answer:'Beach soccer is full of quick bursts: winning the ball, a run into space, then a rolling substitution to recover.'}}
 ]},
 {id:'farm-lani',name:'Lani',role:'Coral Cay farmer',pursuit:'WATERING THE CROPS',x:632,z:-118.5,activity:'watering',workYaw:Math.PI,character:'female',face:'warm',clothing:'coast',greeting:'Welcome to the farm! Everything growing here is fuel for football. Want to know which foods give your legs energy?',topics:[
  {id:'carbs',question:'Which foods give me energy to play?',answer:'Carbohydrate foods are football’s main fuel: rice, pasta, bread, potatoes, maize and sweet potatoes like these rows, and fruit such as bananas.',followUp:{question:'When should I eat before a match?',answer:'A proper meal a few hours before, about 3 to 4, gives your body time to use it. Closer to kick-off, a small snack like a banana is easier on your tummy.'}},
  {id:'veg',question:'Why grow so many vegetables?',answer:'Fruit and vegetables give you vitamins and minerals that help your body stay healthy and recover after training. Lots of colours on your plate means lots of different ones.',followUp:{question:'Do I have to eat the same as a pro?',answer:'No. Eat familiar food you enjoy and that sits well before playing. Food is fuel, not a test, and a grown-up can help you plan.'}}
 ]},
 {id:'farm-bo',name:'Bo',role:'Orchard keeper',pursuit:'PICKING MANGOES',x:659.5,z:-121,activity:'watering',workYaw:0,character:'male',face:'deep',clothing:'classic',greeting:'Mangoes, citrus, papayas and bananas: our orchard is a fruit bowl for the whole island team. Ask me about snacks for football!',topics:[
  {id:'snack',question:'What is a good snack before playing?',answer:'Something small and familiar with carbohydrate, eaten an hour or two before: a banana, a piece of fruit or some toast. Big, heavy meals are better earlier.',followUp:{question:'And after the game?',answer:'Refuel and recover with a meal or snack that has carbohydrate and some protein, like a sandwich, yoghurt and fruit, plus plenty of water.'}},
  {id:'fruit',question:'Why do you grow so many different fruits?',answer:'Different fruits bring different vitamins. Citrus, mango and papaya are bright and juicy, and bananas are an easy energy snack to carry in a kit bag.',followUp:{question:'Can fruit help on a hot day?',answer:'Juicy fruit like watermelon is mostly water, so it is a refreshing snack, but water is still the main drink to keep you going.'}}
 ]},
 {id:'farm-mele',name:'Mele',role:'Farm produce stand',pursuit:'SELLING THE HARVEST',x:611,z:-103.6,activity:'serving',workYaw:0,character:'female',face:'light',clothing:'sunset',greeting:'Fresh from the fields! The beach soccer players stop here after games. On a hot beach, I always ask: have you had your water?',topics:[
  {id:'water',question:'What should I drink when I play?',answer:'Water! Drink before you play, at the breaks and afterwards. On a hot, sunny beach you lose more sweat, so keep your bottle close.',followUp:{question:'How do I know I need a drink?',answer:'Do not wait until you feel very thirsty. Take sips at every break, and tell your coach if you feel dizzy or unwell.'}},
  {id:'harvest',question:'What is on the stand today?',answer:'Bananas, tomatoes, peppers, mangoes and melons. A mix of colours on your plate gives your body a mix of vitamins to help you train and recover.',followUp:{question:'Is the Community Garden on the main island like this?',answer:'Yes! The Community Garden grows vegetables too. Everyone helps with the watering, just like a team shares the work on the pitch.'}}
 ]},
 {id:'hostel-ari',name:'Ari',role:'Coral Cay Hostel receptionist',pursuit:'WELCOMING VISITING TEAMS',x:556,z:-113.6,activity:'serving',workYaw:0,character:'female',face:'deep',clothing:'sunset',greeting:'Welcome to the Coral Cay Hostel! Youth teams stay here when they come for the beach soccer tournaments. Travelling to play is part of the adventure.',topics:[
  {id:'away',question:'What is an away day?',answer:'Playing at another team’s ground, or travelling to a tournament. You pack your kit, travel together and play somewhere new. Sticking together as a team helps everyone feel ready.',followUp:{question:'How do we make a good impression on our hosts?',answer:'Say thank you, tidy up after yourselves and shake hands after the game, win or lose. Respect for your hosts is how a team gets invited back.'}},
  {id:'sleep',question:'Does sleep really matter before a match?',answer:'Yes! Sleep is when your body recovers and your brain stores what you practised. Children your age usually need about 9 to 12 hours a night, and teenagers about 8 to 10.',followUp:{question:'What if I am too excited to sleep?',answer:'Keep your normal bedtime and a calm routine: screens off a while before bed and a quiet, dark room. Resting still helps, even if sleep takes a while.'}}
 ]},
 {id:'home-koa',name:'Koa',role:'Neighbourhood kid',pursuit:'PRACTISING IN THE YARD',x:566.5,z:-86.4,character:'male',face:'warm',clothing:'coast',greeting:'I practise with my mini goal every afternoon. When teams stay at the hostel, their players often join in!',topics:[
  {id:'mix',question:'How do visiting teams make friends here?',answer:'We play mixed teams: a few players from each club on each side. You learn new names fast when you have to pass to each other!',followUp:{question:'What is team spirit?',answer:'Helping each other: cheering a good try, picking a teammate up after a mistake and sharing the ball. It travels with you wherever you play.'}}
 ]},
 {id:'home-lina',name:'Lina',role:'Neighbourhood gardener',pursuit:'WATERING THE HIBISCUS',x:569.6,z:-101.9,activity:'watering',workYaw:Math.PI,character:'female',face:'light',clothing:'classic',greeting:'I grow hibiscus and bananas in my garden, and I cheer for every team at the tournaments.',topics:[
  {id:'fans',question:'How should fans behave at a tournament?',answer:'Cheer for good play from both teams, never shout at the referee or players, and say well played at the end. Young players learn best with positive people around them.',followUp:{question:'Can we cheer for both teams?',answer:'Of course! Applauding a great goal or save from the other team shows respect for the game.'}}
 ]},
];
