import type {NpcDefinition} from './npcDialogues';
export const COURT_FREESTYLERS:NpcDefinition[]=[
 {id:'court-nico',name:'Teo',role:'Freestyle · Around the world',pursuit:'AROUND THE WORLD',x:82,z:-61.5,character:'male',face:'warm',clothing:'sunset',freestyle:0,workYaw:.4,greeting:'I am linking an around-the-world with a soft landing touch. Watch the foot circle the ball, then come back underneath it.',topics:[{id:'circle',question:'How do I start?',answer:'Build steady keep-ups first. Try one small lift, circle your foot around the ball, and catch it. Practise the circle slowly before linking touches.',followUp:{question:'What should I watch in the clip?',answer:'Follow Erlend and Brynjar Fagerli’s support foot. The next move starts with a balanced landing, not just a fast circling foot.'}}]},
 {id:'court-zuri',name:'Zuri',role:'Freestyle · Soft touches',pursuit:'ALTERNATING KEEP-UPS',x:90,z:-61.5,character:'female',face:'deep',clothing:'coast',freestyle:1,workYaw:-.4,greeting:'My challenge is to make each touch gentle enough for the next one. Both feet get a turn! Want to watch Andrew Henderson’s control?',topics:[{id:'soft',question:'How do I keep the ball close?',answer:'Start with one touch and a catch. Point your toes slightly up and lift gently. Add a second touch when the first becomes repeatable.',followUp:{question:'Why practise both feet?',answer:'Either foot can help you receive a pass. Freestyle builds comfort with the ball; in a match, choose the touch that gives your team the next option.'}}]},
 {id:'court-kei',name:'Kei',role:'Freestyle · Knee control',pursuit:'KNEE-TO-FOOT COMBOS',x:81,z:-56.5,character:'male',face:'light',clothing:'classic',freestyle:2,workYaw:.8,greeting:'I am moving the ball from my feet to my thighs and back down. The trick is to cushion it, not send it chasing the clouds.',topics:[{id:'knee',question:'Where does the ball touch?',answer:'Use the broad part of your thigh above the knee. Meet the falling ball gently, then lower your leg a little to absorb its speed.',followUp:{question:'How does that help in football?',answer:'A gentle thigh touch can settle a bouncing pass. Keep your balance and guide it toward your next pass or dribble.'}}]},
 {id:'court-iza',name:'Iza',role:'Freestyle · Upper-body balance',pursuit:'SHOULDER-TO-HEAD FLOW',x:91,z:-56.5,character:'female',face:'warm',clothing:'sunset',freestyle:3,workYaw:-.8,videoTopic:'garnier-freestyle',videoPrompt:'Watch Séan Garnier’s standing foot and how softly he cushions the ball. Which touch keeps it closest to him?',greeting:'I am practising balance and upper-body control. Watch how the body adjusts underneath the ball. You can start with foot touches and catches.',topics:[{id:'garnier',question:'Who is Séan Garnier?',answer:'A famous French freestyler. In 2008 he won the first Red Bull Street Style world final, in São Paulo, Brazil. He also plays street football, futsal and panna.',followUp:{question:'What can I learn from his clips?',answer:'Look at how balanced he is before each touch. In a match, that same calm first touch keeps the ball close so you can pass or dribble next.'}},{id:'balance',question:'What should I notice?',answer:'Watch the small adjustments underneath the ball. A balanced body makes the next touch easier. You do not need to copy advanced tricks to learn from them.',followUp:{question:'What is a simple challenge?',answer:'Try five gentle alternating foot touches with a catch between each. Keep your shoulders relaxed and give yourself room to move.'}}]},
];
export const FREESTYLE_CLIPS=[
 {id:'3Iq0Rtxt6K4',title:'Erlend vs Brynjar Fagerli · Street Style final',source:'Flair20 TV',prompt:'Watch the support foot and the recovery between combinations.'},
 {id:'2hvClyF2j0I',title:'Andrew Henderson · Freestyle control',source:'The FA · FATV',prompt:'Watch how a soft touch sets up the next movement.'},
] as const;
