import {CLUB_COSTUMES} from './costumes';
export type PlayerCard={id:string;name:string;era:'Current star'|'Club legend';position:string;bio:string;watch:string;question:string;choices:string[];answer:number;explanation:string;source:string};
export type ClubJourney={id:string;title:string;skill:string;players:PlayerCard[];challenge:{prompt:string;choices:string[];answer:number;explanation:string;beats:string[]};rewards:{itemId:string;badge:string;connection:string}[]};
export const PLAYER_REVIEWED='13 September 2026';
export const CLUB_JOURNEYS:ClubJourney[]=[
 {id:'barcelona',title:'Find the next pass',skill:'Support angles',players:[
  {id:'yamal',name:'Lamine Yamal',era:'Current star',position:'Right winger',bio:'A La Masia graduate who became a Barcelona first-team forward. His journey connects the academy to the club’s next generation.',watch:'Watch the space around a winger. A wide starting position can stretch a defender; an angled teammate offers a way out when the defender closes.',question:'Your winger is being closed down. Where can you help?',choices:['Hide directly behind the defender','Move to a clear diagonal passing angle','Stand beside the winger and bring another defender'],answer:1,explanation:'A diagonal angle opens a passing lane. Support the player on the ball without crowding them.',source:'https://www.fcbarcelona.com/en/football/first-team/players/129404/lamine-yamal'},
  {id:'messi',name:'Lionel Messi',era:'Club legend',position:'Forward / playmaker',bio:'Barcelona’s record goalscorer also created chances for teammates. His club legacy connects scoring with combination play.',watch:'After a short pass, follow the passer. A new angle can create a return pass beyond the opponent: a give-and-go.',question:'After passing to a teammate, what helps a give-and-go?',choices:['Move into an open return lane','Stay still behind your marker','Run toward your own teammate’s feet'],answer:0,explanation:'Pass, move and offer a new angle. The movement makes the return pass possible.',source:'https://players.fcbarcelona.com/en/player/548-messi-lionel-andres-messi-cuccitini'}
 ],challenge:{prompt:'Gold A is passing to B. The defender will block the straight return. Tap the space A should move into next.',choices:['Space 1: directly behind the defender','Space 2: beside B','Space 3: a new diagonal angle'],answer:2,explanation:'A changes direction into space 3. B can now pass around the defender instead of through them. The two players stay connected by an open lane.',beats:['A passes to B; the defender closes the straight lane.','A changes direction to offer a diagonal angle.','B returns the ball through the new passing lane.']},rewards:[{itemId:'ball:cosmic',badge:'Pass & move',connection:'Earn this badge by recognizing a new passing angle.'},{itemId:'scooter:mint',badge:'Support explorer',connection:'Your ride between football lessons; this badge records your support-angle learning.'}]},
 {id:'arsenal',title:'Make room on the wing',skill:'Width and timing',players:[
  {id:'saka',name:'Bukayo Saka',era:'Current star',position:'Right winger',bio:'An Arsenal academy graduate who became a key forward. His pathway shows how a club’s youth development can shape its first team.',watch:'Watch the winger and the supporting fullback together. An overlap works when the supporting player runs outside and the winger recognizes the space.',question:'What is an overlapping run?',choices:['A teammate running outside and beyond the ball carrier','Two players standing on the same spot','A goalkeeper holding the ball'],answer:0,explanation:'An overlap adds an option outside the ball carrier and asks the defender to cover two threats.',source:'https://www.arsenal.com/news/bukayo-saka-signs-new-long-term-contract-aFcin3f65ht4'},
  {id:'henry',name:'Thierry Henry',era:'Club legend',position:'Striker',bio:'Arsenal’s record goalscorer is a lasting part of the club’s history. Studying a striker includes their movement before the shot, not only the finish.',watch:'Watch when the runner accelerates. A curved run can open a passing lane while staying onside until the pass is played.',question:'When is an attacker’s offside position judged?',choices:['Only when they receive the ball','When their teammate plays or touches the ball','Only after a goal'],answer:1,explanation:'The relevant moment is the teammate’s touch. Timing the run matters; being in an offside position alone is not automatically an offence.',source:'https://www.arsenal.com/news/news-archive/heroes-together-no-3-thierry-henry'}
 ],challenge:{prompt:'Gold A carries the ball toward a defender. B supports from behind. Which run gives A an outside option?',choices:['Space 1: overlap outside A','Space 2: into the defender','Space 3: stop behind A'],answer:0,explanation:'B runs outside and beyond A. A draws the defender inward, then releases the pass into the outside lane. The timing keeps the two players connected.',beats:['A carries inward and draws the defender.','B curves outside A into the wide lane.','A releases the pass ahead of B.']},rewards:[{itemId:'bike:road',badge:'Wide runner',connection:'A football timing badge for your trips between pitches.'},{itemId:'moped:delivery',badge:'Chance creator',connection:'Deliver the next learning mission; your badge celebrates creating a passing option.'}]},
 {id:'bayern',title:'Arrive in scoring space',skill:'Movement off the ball',players:[
  {id:'kane',name:'Harry Kane',era:'Current star',position:'Striker',bio:'The England striker joined Bayern in 2023. A centre-forward can help connect an attack as well as finish it.',watch:'Look for a striker checking toward the ball to offer a pass, then moving again. Pulling a defender out can create room for another runner.',question:'Why might a striker drop toward midfield?',choices:['To stay permanently away from goal','To stop teammates running forward','To link a pass and draw a defender out'],answer:2,explanation:'Dropping short can connect teammates and create space beyond the defender. The next movement is just as important.',source:'https://fcbayern.com/en/teams/first-team/harry-kane'},
  {id:'muller',name:'Gerd Müller',era:'Club legend',position:'Striker',bio:'Bayern remembers Müller as a prolific goalscorer central to its success in the late 1960s and 1970s. His story is a window into the club’s historic teams.',watch:'Watch the space in front of goal before a cross. A quick change of direction can separate a striker from a marker and create a short finishing opportunity.',question:'What helps a striker escape a close marker?',choices:['Standing still beside the defender','Checking away, then changing direction into space','Always running straight toward the ball carrier'],answer:1,explanation:'A change of direction can unbalance the marker. Time the second movement to the delivery.',source:'https://fcbayern.com/en/club/hall-of-fame/gerd-muller'}
 ],challenge:{prompt:'Gold A is wide with the ball. B is closely marked. Where should B arrive for the low pass?',choices:['Space 1: stay beside the marker','Space 2: the open finishing lane','Space 3: crowd A near the touchline'],answer:1,explanation:'B checks away first, then changes direction into space 2. A times the low pass to B’s arrival. The move creates separation rather than relying on speed alone.',beats:['B checks away; the defender follows.','B changes direction into the finishing lane.','A plays a low pass for B’s arrival.']},rewards:[{itemId:'jetpack:helicopter',badge:'Space spotter',connection:'An aerial view helps you notice space. This badge records your off-ball movement lesson.'}]}
];
export type PassportEvidence={stories:string[];players:string[];pitches:string[]};
export const emptyPassport=():PassportEvidence=>({stories:[],players:[],pitches:[]});
const clubs=new Set(CLUB_COSTUMES.map(c=>c.id)),playerIds=new Set(CLUB_JOURNEYS.flatMap(c=>c.players.map(p=>p.id))),journeys=new Set(CLUB_JOURNEYS.map(c=>c.id));
export function sanitizePassport(value:unknown):PassportEvidence{const v=value&&typeof value==='object'?value as Record<string,unknown>:{};const clean=(key:string,allowed:Set<string>)=>Array.isArray(v[key])?[...new Set((v[key] as unknown[]).filter((x):x is string=>typeof x==='string'&&allowed.has(x)))]:[];return {stories:clean('stories',clubs),players:clean('players',playerIds),pitches:clean('pitches',journeys)};}
export function journeyProgress(journey:ClubJourney,e:PassportEvidence){const story=e.stories.includes(journey.id),players=journey.players.map(p=>e.players.includes(p.id)),pitch=e.pitches.includes(journey.id);const count=Number(story)+players.filter(Boolean).length+Number(pitch);return {story,players,pitch,count,total:4,earned:count===4};}
export function awardPassportAnswer(e:PassportEvidence,kind:'story'|'player'|'pitch',id:string,answer:number):PassportEvidence{
 const question=kind==='story'?CLUB_COSTUMES.find(c=>c.id===id):kind==='player'?CLUB_JOURNEYS.flatMap(c=>c.players).find(p=>p.id===id):CLUB_JOURNEYS.find(c=>c.id===id)?.challenge;
 if(!question||question.answer!==answer)return e;
 const key=kind==='story'?'stories':kind==='player'?'players':'pitches';return e[key].includes(id)?e:{...e,[key]:[...e[key],id]};
}
export function itemJourney(itemId:string){return CLUB_JOURNEYS.find(c=>c.rewards.some(r=>r.itemId===itemId));}
