import type {NpcDefinition} from './npcDialogues';
// Dispersed destinations; final positions use the existing walkable placement search.
const desks:[string,string,number,number,string,string,string,string,string][]=[
 ['celeste','Celeste',-42,-198,'uefa-scanning','UEFA scanning guide','READING THE NEXT PASS','Before a pass arrives, I watch the receiver look over a shoulder. Shall we look for that in a UEFA clip?','Count the looks before the first touch. What did the player learn about pressure?'],
 ['idriss','Idriss',35,-205,'uefa-support','UEFA support guide','SKETCHING PASSING ANGLES','I sketch triangles in my notebook. UEFA teaching clips can help us see how a teammate changes the passing angle.','Pause before a pass and find a second option. Which small movement opens it?'],
 ['suki','Suki',160,-195,'uefa-pressing','UEFA pressing guide','SPOTTING PRESSING CUES','I am studying when a team presses together. A poor touch can be a cue, but the nearest player still needs cover.','Watch who closes the ball and who protects the space behind.'],
 ['dario','Dario',218,-145,'uefa-finishing','UEFA finishing guide','STUDYING SHOT CHOICES','I collect finishing ideas, not just spectacular goals. Let’s notice the keeper and the space before a shot.','Was placement, power or one more pass the useful choice? Explain what you saw.'],
 ['anika','Anika',-79,-133,'espn-goals','ESPN FC goal watcher','REWINDING THE BUILDUP','A goal is the ending of a longer story. I watch recent ESPN FC clips for the work before the finish.','Follow one teammate without the ball. Did that run help the scorer?'],
 ['bruno','Bruno',-82,17,'espn-analysis','ESPN FC discussion host','QUESTIONING THE ANALYSIS','I like discussing ESPN FC’s latest futbol analysis. An expert opinion is a starting point; we can ask what evidence supports it.','Separate a visible event from an opinion about it. Would another explanation fit?'],
 ['keiko','Keiko',230,58,'espn-skills','ESPN FC skill spotter','NOTICING USEFUL SKILLS','I am looking for a skill that helps the team, not just a flashy touch. Let’s watch for that in a recent ESPN FC clip.','Did the skill create space, keep possession or find a teammate?'],
 ['sol','Sol',228,155,'ucl-final-result','Champions League final desk','TRACING THE FINAL','I follow Champions League finals. A final recap should identify the match and date clearly, so we never confuse an older final with a new result.','Look at how the match changed after a goal. What did each team adjust?'],
 ['malik','Malik',129,212,'ucl-final-discussion','CBS Sports Golazo discussion host','COMPARING FINAL DECISIONS','I enjoy CBS Sports Golazo’s discussion after a Champions League final. Let’s examine a decision rather than blame a player for the whole result.','What options did the player have at that moment, before knowing the outcome?'],
 ['inesa','Inesa',69,78,'uefa-teamwork','UEFA teamwork guide','LISTENING FOR TEAMWORK','I look for quiet teamwork: a helpful call, a covering run, an offer to receive. A teaching clip can make those small contributions easier to see.','Choose one action that helps someone else. Where could you try it in your next game?'],
];
export const VIDEO_NEIGHBORS:NpcDefinition[]=desks.map(([id,name,x,z,videoTopic,role,pursuit,greeting,videoPrompt],i)=>({id:`video-${id}`,name,x,z,videoTopic,videoPrompt,role,pursuit,greeting,character:i%2?'male':'female',face:(['warm','deep','light'] as const)[i%3],clothing:(['classic','coast','sunset'] as const)[i%3],topics:[{id:`${id}-watch`,question:'What should I look for?',answer:videoPrompt,followUp:{question:'How can I use that idea?',answer:`Try this observation from ${name}: ${videoPrompt} Choose one moment, describe your decision to a teammate, then try it in a small game.`}}]}));
