import {createBallSparkles} from './ballSparkles';
import * as T from 'three';
import type {CharacterCustomization} from '../town/customization';
export function createBallEffects(){
 const root=new T.Group();root.name='ball-shot-effects';const sparkles=createBallSparkles();root.add(sparkles.root);
 const points=Array.from({length:20},()=>new T.Vector3()),positions=new Float32Array(60),geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3));
 const material=new T.LineBasicMaterial({color:'#fff1b3',transparent:true,opacity:.6,depthWrite:false});const trail=new T.Line(geometry,material);trail.frustumCulled=false;root.add(trail);
 const ghostGeometry=new T.SphereGeometry(.16,8,6),ghostMaterial=new T.MeshBasicMaterial({color:'#fff1b3',transparent:true,opacity:.42,depthWrite:false}),ghosts=Array.from({length:14},()=>{const ghost=new T.Mesh<T.BufferGeometry,T.MeshBasicMaterial>(ghostGeometry,ghostMaterial);root.add(ghost);return ghost;});
 const shardGeometry=new T.IcosahedronGeometry(.16,0);
 const starShape=new T.Shape();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?.06:.16;i?starShape.lineTo(Math.cos(a)*r,Math.sin(a)*r):starShape.moveTo(Math.cos(a)*r,Math.sin(a)*r);}starShape.closePath();const starGeometry=new T.ShapeGeometry(starShape);
 const ringGeometry=new T.RingGeometry(.8,1,24),rings=Array.from({length:5},()=>{const material=new T.MeshBasicMaterial({color:'#fff3c2',transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide});const mesh=new T.Mesh(ringGeometry,material);mesh.visible=false;root.add(mesh);return{mesh,material,age:1,power:0};});let cursor=0,wasShot=false,clock=0,hidden=false,lastColor="";
 const solarMaterial=new T.MeshBasicMaterial({color:'#ffd36b',transparent:true,opacity:.35,depthWrite:false,side:T.DoubleSide}),solarRings=Array.from({length:3},()=>{const ring=new T.Mesh(ringGeometry,solarMaterial);ring.name='solar-ball-trail-ring';root.add(ring);return ring;});
 const chargeMaterial=new T.MeshBasicMaterial({color:'#ffdc79',transparent:true,opacity:0,depthWrite:false,side:T.DoubleSide,blending:T.AdditiveBlending}),chargeRing=new T.Mesh(ringGeometry,chargeMaterial);chargeRing.name='ball-charge-glow';root.add(chargeRing);
 const energyMaterial=new T.MeshBasicMaterial({color:'#fff2a6',transparent:true,opacity:0,depthWrite:false,blending:T.AdditiveBlending}),energy=Array.from({length:8},()=>{const mesh=new T.Mesh(ghostGeometry,energyMaterial);mesh.name='ball-charge-energy';root.add(mesh);return mesh;});
 return {root,impact(x:number,y:number,z:number){const ring=rings[cursor++%rings.length];ring.age=0;ring.power=0;ring.material.color.set('#fff3c2');ring.mesh.position.set(x,y,z);},launch(x:number,y:number,z:number,power:number){if(power<=.05)return;for(let i=0;i<3;i++){const ring=rings[cursor++%rings.length];ring.age=-i*.065;ring.power=power;ring.material.color.set(i%2?'#fff8db':'#ffce67');ring.mesh.position.set(x,y,z);}},update(dt:number,p:{x:number;y:number;z:number},shot:boolean,reduced:boolean,camera:T.Camera,power=0,charging=-1,color='#eee4c4',style:CharacterCustomization['ball']='classic'){
  sparkles.update(dt,p,shot,root.visible,reduced,color);
  if(!root.visible){if(!hidden){hidden=true;wasShot=false;for(const ring of rings){ring.age=1;ring.mesh.visible=false;}chargeRing.visible=trail.visible=false;for(const mesh of [...energy,...ghosts,...solarRings])mesh.visible=false;}return;}hidden=false;
  clock+=dt;chargeRing.visible=charging>=0;chargeRing.position.set(p.x,p.y,p.z);chargeRing.quaternion.copy(camera.quaternion);chargeRing.scale.setScalar(.27+Math.max(0,charging)*.13+(reduced?0:Math.sin(clock*12)*.025));chargeMaterial.opacity=charging>=0?.3+charging*.35:0;material.opacity=.6+power*.3;ghostMaterial.opacity=.42+power*.2;if(color!==lastColor){lastColor=color;material.color.set(color);ghostMaterial.color.copy(material.color);solarMaterial.color.set(color);chargeMaterial.color.set(color);energyMaterial.color.set(color);}
  energyMaterial.opacity=charging>=0?.4+charging*.5:0;energy.forEach((mesh,i)=>{mesh.visible=charging>=0&&!reduced;if(!mesh.visible)return;const phase=(clock*(.8+Math.max(0,charging)*.7)+i/8)%1,angle=i*Math.PI*.75+clock*1.4,radius=.2+(1-phase)*(.45+Math.max(0,charging)*.3);mesh.position.set(p.x+Math.cos(angle)*radius,p.y+Math.sin(angle)*radius*.65,p.z+Math.sin(angle+.8)*radius);mesh.scale.setScalar(.1+phase*.17);});
  if(!shot||!wasShot)points.forEach(v=>v.set(p.x,p.y,p.z));else if(dt>0){for(let i=points.length-1;i>0;i--)points[i].copy(points[i-1]);points[0].set(p.x,p.y,p.z);}wasShot=shot;trail.visible=shot&&!reduced;
  ghosts.forEach((ghost,i)=>{ghost.visible=shot&&!reduced;if(!ghost.visible)return;ghost.position.copy(points[i+1]);ghost.geometry=style==='frost'?shardGeometry:style==='cosmic'?starGeometry:ghostGeometry;ghost.scale.setScalar((1-i/15)*(1+power*.65));if(style==='frost'){ghost.scale.set(.45*(1-i/15),1.5*(1-i/15),.45*(1-i/15));ghost.rotation.set(clock*2+i,i*.7,clock+i);}else if(style==='cosmic'){const radius=(1-i/15)*.18,angle=clock*8+i*.9;ghost.position.x+=Math.cos(angle)*radius;ghost.position.y+=Math.sin(angle)*radius;ghost.quaternion.copy(camera.quaternion);}else ghost.rotation.set(0,0,0);});
  solarRings.forEach((ring,i)=>{ring.visible=shot&&!reduced&&style==='solar';if(!ring.visible)return;ring.position.copy(points[3+i*4]);ring.quaternion.copy(camera.quaternion);ring.scale.setScalar(.15+((clock*2+i/3)%1)*.3);});
  if(trail.visible){points.forEach((point,i)=>point.toArray(positions,i*3));geometry.attributes.position.needsUpdate=true;}
  for(const ring of rings){ring.age+=dt;const t=ring.age/.38;ring.mesh.visible=t>=0&&t<1;if(t>=0&&t<1){ring.mesh.quaternion.copy(camera.quaternion);ring.mesh.scale.setScalar(reduced?.4:.15+t*(.95+ring.power*2.2));ring.material.opacity=(1-t)*.75;}}
 },dispose(){sparkles.dispose();solarMaterial.dispose();shardGeometry.dispose();starGeometry.dispose();energyMaterial.dispose();chargeMaterial.dispose();ghostGeometry.dispose();ghostMaterial.dispose();geometry.dispose();material.dispose();ringGeometry.dispose();rings.forEach(r=>r.material.dispose());root.removeFromParent();}};
}
