import * as T from 'three';
export function createSonicBurst(){
 const root=new T.Group();root.name='jetpack-sonic-burst';root.visible=false;const geometry=new T.RingGeometry(.86,1,48);
 const softGeometry=new T.PlaneGeometry(2,2),pixels=new Uint8Array(64*64*4);
 for(let y=0;y<64;y++)for(let x=0;x<64;x++){const r=Math.hypot((x-31.5)/31.5,(y-31.5)/31.5),i=(y*64+x)*4;pixels[i]=pixels[i+1]=pixels[i+2]=255;pixels[i+3]=Math.round(255*Math.exp(-Math.pow((r-.78)/.105,2)));}
 const softTexture=new T.DataTexture(pixels,64,64,T.RGBAFormat);softTexture.magFilter=softTexture.minFilter=T.LinearFilter;softTexture.needsUpdate=true;
 const rings=Array.from({length:3},()=>{const material=new T.MeshBasicMaterial({color:'#b8fff0',transparent:true,opacity:0,side:T.DoubleSide,depthWrite:false,blending:T.AdditiveBlending});const mesh=new T.Mesh<T.BufferGeometry,T.MeshBasicMaterial>(geometry,material);root.add(mesh);return{mesh,material};});let age=2,style='classic';
 return {root,trigger(x:number,y:number,z:number,yaw:number,up=false,color='#b8fff0',soft=false,kind='classic'){root.visible=true;style=kind;rings.forEach(r=>{r.material.color.set(color);r.mesh.geometry=soft?softGeometry:geometry;const map=soft?softTexture:null;if(r.material.map!==map){r.material.map=map;r.material.needsUpdate=true;}});age=0;root.position.set(x,y+1,z);root.rotation.set(up?-Math.PI/2:0,yaw,0);},update(dt:number,reduced:boolean){if(!root.visible)return;age+=dt;if(age>=.63){root.visible=false;return;}for(let i=0;i<rings.length;i++){const {mesh,material}=rings[i],t=(age-i*.065)/.5;mesh.visible=t>=0&&t<1;if(mesh.visible){mesh.scale.setScalar(reduced?1.8:.4+t*7);mesh.position.z=-i*.7;mesh.rotation.z=reduced?0:style==='flying-car'?t*5+i:style==='helicopter'?-t*8+i:0;if(style==='flying-car')mesh.scale.y*=.45;else if(style==='helicopter')mesh.scale.x*=.7;else if(style==='ironman'){mesh.scale.multiplyScalar(.65);mesh.position.z=-i*.3-t*2;}else if(style==='rocketboard'){mesh.scale.y*=.25;mesh.rotation.z=t*7+i;}else if(style==='mini-plane'){mesh.scale.x*=1.5;mesh.scale.y*=.45;mesh.position.z=-i*1.1;}material.opacity=(1-t)*(reduced?.22:.65);}}},dispose(){root.removeFromParent();geometry.dispose();softGeometry.dispose();softTexture.dispose();rings.forEach(r=>r.material.dispose());}};
}
