const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),path=require('node:path');
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:1,target:7}}).outputText,{exports:m.exports,module:m,Math,Number,console,require:id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id)});return m.exports;}
const p=load('lib/games/soccerPinball.ts'),r=load('lib/arcade/runnerGame.ts'),t=load('lib/games/soccerTennis.ts'),g=load('lib/arcade/strikerMatch.ts');
for(const hz of [30,60,120]){
 const ball=p.createPinballState();p.launchPinball(ball);Object.assign(ball.ball,{x:180,y:630,vx:0,vy:50});p.stepPinball(ball,{left:false,right:false},1/hz);assert.equal(ball.balls,3);assert.equal(ball.cue,'rescue');
 for(let i=0;i<hz*1.1;i++)p.stepPinball(ball,{left:false,right:false},1/hz);assert.equal(ball.phase,'ready');p.launchPinball(ball);Object.assign(ball.ball,{x:180,y:630,vx:0,vy:50});p.stepPinball(ball,{left:false,right:false},1/hz);assert.equal(ball.balls,2,'grace cannot be farmed by relaunching');
 const run=r.createRunnerGame();run.spawn=99;run.nextGoal=1e6;r.runnerJump(run);while(run.vy>0||run.y>.7)r.tickRunner(run,1/hz);r.runnerSlide(run);for(let i=0;i<hz*.2;i++)r.tickRunner(run,1/hz);assert(run.slide>0,'late slide executes when feet land');
 const early=r.createRunnerGame();early.spawn=99;early.nextGoal=1e6;r.runnerJump(early);r.runnerJump(early);for(let i=0;i<hz;i++)r.tickRunner(early,1/hz);assert(!early.jumping,'early jump press expires instead of auto-hopping');
 const shot=r.createRunnerGame();shot.spawn=99;shot.nextGoal=1e6;shot.slide=.1;shot.charge=.95;shot.charging=true;assert(r.runnerRelease(shot));assert.equal(shot.balls,1);for(let i=0;i<hz*.15;i++)r.tickRunner(shot,1/hz);assert.equal(shot.balls,0);assert.equal(shot.lastBlast,.95,'buffer preserves charged power');
 const cancel=r.createRunnerGame();cancel.slide=.1;cancel.charging=true;cancel.charge=1;r.runnerRelease(cancel);r.runnerCharge(cancel,false);for(let i=0;i<hz;i++)r.tickRunner(cancel,1/hz);assert.equal(cancel.balls,1,'pause/cancel clears queued shot');
 const tennis=t.createTennis();tennis.phase='rally';tennis.bounceAge=.12;Object.assign(tennis.ball,{x:.1,y:5.2,z:.3,last:'rival',crossed:true,bounces:1});assert(t.canTennisPerfect(tennis));tennis.you.vx=4;assert(!t.canTennisPerfect(tennis));tennis.you.vx=0;tennis.bounceAge=.3;assert(!t.canTennisPerfect(tennis));
 for(const offset of [-.8,0,.8]){const match=g.createStrikerMatch(),s=match.state,keeper=s.players[7];for(const q of s.players)if(!q.keeper)q.stun=10;Object.assign(keeper,{x:22.5,z:0,think:10});Object.assign(s.ball,{owner:-1,x:22.2,z:offset,y:1.5,vx:8,vz:0,vy:0,lock:0});match.step(1/hz,g.strikerInput());assert.equal(keeper.strikeKind,'save');assert.equal(keeper.saveWide,offset!==0);assert.equal(keeper.saveSide,offset>0?-1:1);assert(keeper.saveHeight>1.4);}
}
console.log('PASS arcade polish: single opening rescue, landing/release buffering, cancellation, truthful perfect window and directional keeper stops at 30/60/120Hz');
