const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
const listeners=new Map(),sources=[],buffers=[];let context;
const param=()=>({value:0,setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}});
const node=()=>({gain:param(),frequency:param(),connect(){},disconnect(){}});
class AudioContext{constructor(){context=this;this.state='running';this.currentTime=0;this.sampleRate=100;this.destination={}}createGain(){return node()}createBiquadFilter(){return node()}createBuffer(ch,n){const b={getChannelData:()=>new Float32Array(n)};buffers.push(b);return b}createBufferSource(){const s={...node(),start(){this.started=true},stop(at){this.stopAt=at??0;this.onended?.()}};sources.push(s);return s}resume(){return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}close(){return Promise.resolve()}}
const m={exports:{}},doc={hidden:false,addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:n=>listeners.delete(n)};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/audio/islandSound.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,window:{AudioContext},navigator:{},document:doc,performance:{now:()=>0},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail}},Math,Map,Set,Number});
const sound=m.exports.createIslandSound(false,0),ocean=v=>listeners.get('fi2-bottle-ocean')({detail:v});
ocean(true);assert.equal(sources.length,0,'zero volume allocates no ocean source');sound.setVolume(.5);assert.equal(sources.length,1);assert(sources[0].loop);const allocations=buffers.length;sound.setMuted(true);sound.setMuted(false);assert.equal(sources.length,2);assert.equal(buffers.length,allocations,'unmute reuses buffer');ocean(false);assert.equal(sources[1].stopAt,1.3,'closing schedules a tail');ocean(true);assert.equal(buffers.length,allocations,'reopening reuses buffer');sound.silence(true);assert.equal(sources.at(-1).stopAt,undefined,'blur keeps ocean');doc.hidden=true;sound.visibility();assert.equal(sources.at(-1).stopAt,0,'hidden page stops ocean');sound.dispose();assert.equal(listeners.size,0);console.log('PASS ocean zero-volume sleep, buffer reuse, mute resume, fade tail, hidden cleanup');
