const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),assert=require('node:assert/strict');
const listeners=new Map(),sources=[],buffers=[];let context;
const param=()=>({value:0,setValueAtTime(v){this.value=v},linearRampToValueAtTime(v){this.value=v},exponentialRampToValueAtTime(){},cancelScheduledValues(){},setTargetAtTime(){}});
const node=()=>({gain:param(),frequency:param(),connect(){},disconnect(){}});
class AudioContext{constructor(){context=this;this.state='running';this.currentTime=0;this.sampleRate=100;this.destination={}}createOscillator(){return {...node(),start(){},stop(){this.onended?.()}}}createGain(){return node()}createBiquadFilter(){return node()}createBuffer(ch,n){const b={getChannelData:()=>new Float32Array(n)};buffers.push(b);return b}createBufferSource(){const s={...node(),start(){this.started=true},stop(at){this.stopAt=at??0;this.onended?.()}};sources.push(s);return s}resume(){return Promise.resolve()}suspend(){this.state='suspended';return Promise.resolve()}close(){return Promise.resolve()}}
const m={exports:{}},doc={hidden:false,addEventListener:(n,f)=>listeners.set(n,f),removeEventListener:n=>listeners.delete(n)};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/audio/islandSound.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,window:{AudioContext},navigator:{},document:doc,performance:{now:()=>0},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail}},Math,Map,Set,Number});
const sound=m.exports.createIslandSound(false,0),ocean=v=>listeners.get('fi2-bottle-ocean')({detail:v});
// The shore should swell and recede distinctly instead of being a steady traffic bed.
const wave=new Float32Array(16000*16);let seed=71;m.exports.fillBottleOcean(wave,16000,()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;});
const rms=(a,b)=>Math.sqrt(wave.slice(a*16000,b*16000).reduce((s,v)=>s+v*v,0)/((b-a)*16000));
assert.equal(wave[0],0);assert.equal(wave.at(-1),0);assert.ok(wave.every(Number.isFinite));
for(const [crest,quiet] of [[1.4,5.2],[6.6,10.7],[12,15.5]])assert.ok(rms(crest,crest+.2)>rms(quiet,quiet+.2)*5,'separate surf break and quiet receding water');
assert.ok(wave.every(v=>Math.abs(v)<1),'generated surf buffer never clips before the quiet playback gain');
ocean(true);assert.equal(sources.length,0,'zero volume allocates no ocean source');sound.setVolume(.5);assert.equal(sources.length,1);assert(sources[0].loop);const allocations=buffers.length;sound.setMuted(true);sound.setMuted(false);assert.equal(sources.length,2);assert.equal(buffers.length,allocations,'unmute reuses buffer');ocean(false);assert.equal(sources[1].stopAt,1.3,'closing schedules a tail');ocean(true);assert.equal(buffers.length,allocations,'reopening reuses buffer');sound.silence(true);assert.equal(sources.at(-1).stopAt,undefined,'blur keeps ocean');context.currentTime=2;assert.equal(m.exports.readBottleOceanTime(-1),2,'visual clock reads audio time');sound.ui('hover');assert.equal(m.exports.readBottleOceanTime(-1),2,'UI sounds cannot replace the ocean clock');doc.hidden=true;sound.visibility();assert.equal(m.exports.readBottleOceanTime(-1),-1,'stopped ocean releases visual clock');assert.equal(sources.at(-1).stopAt,0,'hidden page stops ocean');sound.dispose();assert.equal(listeners.size,0);console.log('PASS ocean zero-volume sleep, buffer reuse, mute resume, fade tail, hidden cleanup');
