const assert=require('node:assert/strict'),fs=require('fs'),ts=require('typescript');
require.extensions['.ts']=(m,f)=>m._compile(ts.transpileModule(fs.readFileSync(f,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true,target:ts.ScriptTarget.ES2020}}).outputText,f);
const {createArcadeWallet}=require('../lib/arcade/arcadeWalletCore.ts'),{createVendingLedger}=require('../lib/town/vendingLedger.ts'),{vendingItem}=require('../lib/town/vendingCatalog.ts'),H=require('../lib/town/homeDecor.ts');
function setup({coins=3000,legacy=[]}={}){let a={version:1,runs:Object.fromEntries(Array.from({length:Math.ceil(coins/20)},(_,i)=>['r'+i,{game:'island',paid:Math.min(20,coins-i*20),reason:'earned',at:i}])),packs:[]},v={version:1,owned:[],spend:legacy,found:[]},failCore=false,failLedger=false,queue=Promise.resolve();
 const ap={read:()=>structuredClone(a),write:n=>{if(failCore)throw Error('quota');a=structuredClone(n);},legacyVending:()=>v.spend,lock:fn=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;},valid:new Set(['A','B','C','D','E','F']),grant:()=>true,notify:()=>{},now:()=>100,id:()=>Math.random().toString(),random:()=>0};const wallet=createArcadeWallet(ap);
 const vp={read:()=>structuredClone(v),write:n=>{if(failLedger)throw Error('quota');v=structuredClone(n);},readSavedLook:()=>null,readCollection:()=>[],arcadeBalance:()=>wallet.load().balance,receipts:()=>wallet.load().vendingPurchases,payItem:item=>wallet.spend('vending:'+item.id,item.price,item.label,'vending',item.id),lock:fn=>Promise.resolve().then(fn),buyPack:p=>wallet.purchaseMysteryPack(p.size,p.legends,p.regular),now:()=>100};const ledger=createVendingLedger(vp);
 return {wallet,ledger,reload:()=>({wallet:createArcadeWallet(ap),ledger:createVendingLedger(vp)}),failCore:x=>failCore=x,failLedger:x=>failLedger=x,saved:()=>({a,v})};}
(async()=>{
 const grant=setup({coins:30});assert.equal(await grant.wallet.grantTestingCoins(),50000);assert.equal(await grant.wallet.grantTestingCoins(),0);assert.equal(grant.reload().wallet.load().balance,50030,'testing grant persists once');
 assert((await grant.ledger.buy(vendingItem('ball:telstar'))).ok);assert.equal(grant.reload().wallet.load().balance,50030-vendingItem('ball:telstar').price,'testing coins can pay through normal shared wallet');
 assert.equal(await grant.reload().wallet.grantTestingCoins(),0,'reload cannot top up spent testing coins');
 assert.equal(await grant.wallet.creditRun('ordinary','island',50000,'Normal reward'),20,'gameplay cap stays unchanged');
 const unavailable=setup({coins:30});unavailable.failCore(true);assert.equal(await unavailable.wallet.grantTestingCoins(),0);assert.equal(unavailable.wallet.load().balance,30,'failed storage must not show a temporary grant');
 const simultaneous=setup({coins:0}),other=simultaneous.reload().wallet;const grants=await Promise.all([simultaneous.wallet.grantTestingCoins(),other.grantTestingCoins()]);assert.equal(grants.reduce((n,v)=>n+v,0),50000,'shared lock grants once across wallets');
 const feature=require('../lib/town/homeFeature.ts');const hidden=setup();assert.equal(vendingItem('display:plaza:frame'),undefined,'prints, lamps and trophies are no longer sold (machines sell books)');assert((await hidden.ledger.buy(vendingItem('display:plaza:book'))).ok,'finished book works while home stays hidden');assert.equal(hidden.wallet.load().balance,2900,'books cost 100 coins');assert((await hidden.ledger.buy(vendingItem('display:plaza:book'))).ok);assert.equal(hidden.wallet.load().balance,2900,'reopening never charges twice');const soon=vendingItem('display:plaza:book:modric');if(soon&&!soon.storyId)assert(!(await hidden.ledger.buy(soon)).ok,'a book that is still being written is a preview');assert.equal(require('../lib/books/catalog.ts').readableBook(vendingItem('display:rooftop:book')),'falcao','every machine book is now a readable story');feature.HOME_DECOR_ENABLED=true;
 const book=vendingItem('display:plaza:book'),lamp=vendingItem('display:rooftop:book'),trophy=vendingItem('display:oldtown:book');
 const t=setup({coins:3000,legacy:[{id:'ball:frost',cost:15,at:1}]});assert.equal(t.wallet.load().balance,2985);await t.wallet.reconcilePacks();assert.equal(Object.keys(t.saved().a.spends).length,1,'legacy migration persists');assert(t.ledger.isOwned('ball:frost'));
 assert((await t.ledger.buy(book)).ok);assert.equal(t.wallet.load().balance,2885);assert((await t.ledger.buy(book)).ok);assert.equal(t.wallet.load().balance,2885,'owned item is not paid twice');assert(t.reload().ledger.isOwned(book.id));assert.equal(t.reload().wallet.load().balance,2885,'reload does not remigrate new receipt-backed history');
 t.failCore(true);assert(!(await t.ledger.buy(lamp)).ok);assert(!t.ledger.isOwned(lamp.id));t.failCore(false);assert.equal(t.wallet.load().balance,2885);
 t.failLedger(true);assert((await t.ledger.buy(lamp)).ok);assert(t.ledger.isOwned(lamp.id),'core receipt grants ownership if secondary history write fails');assert(t.reload().ledger.isOwned(lamp.id),'reload recovers receipt');t.failLedger(false);assert(t.reload().ledger.isOwned(lamp.id));assert.equal(t.wallet.load().balance,2785);
 const x=setup({coins:150}),l2=x.reload().ledger;const both=await Promise.all([x.ledger.buy(book),l2.buy(vendingItem('display:rooftop:book'))]);assert.equal(both.filter(r=>r.ok).length,1,'concurrent purchases cannot spend the same coins');assert.equal(x.wallet.load().balance,50);
 const mixed=setup({coins:100,legacy:[null,{id:'ball:frost',cost:15,at:'10'},{id:'ball:solar',cost:15,at:20}]});assert.equal(mixed.wallet.load().balance,70);await mixed.wallet.reconcilePacks();mixed.saved().v.spend=[{id:'ball:solar',cost:15,at:20},{id:'ball:frost',cost:15,at:10}];assert.equal(mixed.reload().wallet.load().balance,70,'reordering or sanitizing old history does not remigrate charges');
 const y=setup({coins:20,legacy:[{id:'ball:frost',cost:25,at:1}]});assert.equal(y.wallet.load().balance,0);await y.wallet.creditRun('future','island',10,'Job');assert.equal(y.wallet.load().balance,5,'legacy overdraft is preserved instead of forgetting the debit');
 const owned=new Set([book.id,lamp.id,trophy.id]);let home=H.emptyHome;assert(!H.placeHome(home,new Set(),book.id,'shelf',0).ok);assert(!H.placeHome(home,owned,book.id,'wall',0).ok);home=H.placeHome(home,owned,book.id,'shelf',0).state;assert(!H.placeHome(home,owned,trophy.id,'shelf',0).ok,'no overlap');home=H.placeHome(home,owned,book.id,'shelf',2).state;assert.equal(home.placements.length,1,'moving does not clone');assert.equal(home.placements[0].slot,2);assert.deepEqual(H.sanitizeHome(JSON.parse(JSON.stringify(home)),owned),home);assert.equal(H.sanitizeHome(home,new Set()).placements.length,0);assert.equal(H.sanitizeHome({version:1,placements:[...home.placements,{id:lamp.id,surface:'floor',slot:99}]},owned).placements.length,1);
 feature.HOME_DECOR_ENABLED=false;console.log('PASS shared vending receipts, migration, interrupted writes, reload, concurrent spending and owned-only home placement');
})().catch(e=>{console.error(e);process.exit(1)});
