const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),path=require('node:path');
const base=path.resolve(__dirname,'..'),req=require('node:module').createRequire(base+'/package.json'),cache=new Map(),storage=new Map();
function load(file){if(cache.has(file))return cache.get(file);const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,Math,console,localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)},require:id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):req(id)});cache.set(file,mod.exports);return mod.exports;}

const T=req('three'),{createPlayer}=load(base+'/lib/graphics/player.ts'),{createVehicle}=load(base+'/lib/graphics/vehicle.ts'),{CLUB_COSTUMES}=load(base+'/lib/town/costumes.ts'),{DEFAULT_CUSTOMIZATION:D}=load(base+'/lib/town/customization.ts');
const rig=createPlayer('helmet-review','home'),vehicle=createVehicle(),head=rig.root.getObjectByName('player-head'),helmet=vehicle.root.getObjectByName('ironman-helmet');
assert(helmet);assert.equal(helmet.children.filter(m=>m.name==='helmet-glowing-eye').length,2);
for(const costume of ['none',...CLUB_COSTUMES.map(c=>c.id)]){
 const value={...D,costume,jetpack:'ironman'};rig.setAppearance(value);vehicle.setCustomization(value);
 for(const t of [0,.3,.8]){rig.update(t,2,.016,1,false,{travelMode:'jetpack'});rig.root.rotation.set(.2,t,.1);vehicle.update('jetpack',1,2,t,.016,8);vehicle.syncArmor(rig.root);assert.equal(head.visible,false,'mask occludes '+costume);rig.root.updateWorldMatrix(true,true);vehicle.root.updateWorldMatrix(true,true);const a=new T.Vector3(),b=new T.Vector3();head.getWorldPosition(a);helmet.parent.getWorldPosition(b);assert(a.distanceTo(b)<1e-6,'follows animated head');helmet.traverse(n=>assert(n.matrixWorld.elements.every(Number.isFinite)));}
 vehicle.syncArmor(rig.root,false);assert.equal(head.visible,false,'parachute keeps helmet');assert(vehicle.root.getObjectByName('ironman').children.length>0);let flames=0;vehicle.root.traverse(n=>{if(['hand-repulsor','boot-repulsor'].includes(n.name)&&n.visible)flames++;});assert.equal(flames,0,'descent flames off');vehicle.root.visible=false;vehicle.syncArmor(rig.root);assert.equal(head.visible,true,'hidden parent restores head');vehicle.root.visible=true;vehicle.syncArmor(rig.root);assert.equal(head.visible,false,'visible armor covers head again');
 vehicle.update('walk',1,2,0,.016,0);vehicle.syncArmor(rig.root,false);assert.equal(head.visible,true,'landing restores '+costume+' head');assert.equal(vehicle.root.visible,false,'flight gear is hidden on foot');assert.equal(vehicle.root.getObjectByName('ironman').visible,false);vehicle.setCustomization({...value,jetpack:'classic'});vehicle.update('walk',1,2,0,.016,0);vehicle.syncArmor(rig.root);assert.equal(head.visible,true,'changing equipment restores '+costume);assert.equal(rig.root.getObjectByName('player-head'),head);
}
vehicle.setCustomization({...D,jetpack:'ironman'});vehicle.update('jetpack',0,0,0,.016,0);vehicle.syncArmor(rig.root);assert.equal(head.visible,false);vehicle.dispose();assert.equal(head.visible,true,'disposal restores head');rig.dispose();console.log('IRONMAN_HELMET_PASS: 23 mascots plus default, head occlusion/restoration, animated alignment, glowing eyes and disposal');
