const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/islandNewsServer.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,URL,Date,Map,Promise,AbortSignal,fetch,require:id=>{const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/newsLeagues.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:m.exports,module:m});return m.exports;}});
const {parseScoreboard,parseTransferRss}=mod.exports,now=Date.parse('2026-09-13T03:00:00Z');
const item=(title,link,date)=>`<item><title><![CDATA[${title}]]></title><link>${link}</link><pubDate>${date}</pubDate></item>`;
const rss='<rss><channel>'+item('Transfer gossip: A &amp; B','https://www.bbc.co.uk/sport/football/1','Sat, 12 Sep 2026 21:00:00 GMT')+item('Transfer old','https://www.bbc.co.uk/sport/football/2','Sat, 01 Aug 2026 21:00:00 GMT')+item('Transfer future','https://www.bbc.co.uk/sport/football/3','Sat, 19 Sep 2026 21:00:00 GMT')+item('Transfer unsafe','javascript:alert(1)','Sat, 12 Sep 2026 21:00:00 GMT')+item('Match preview','https://www.bbc.co.uk/sport/football/4','Sat, 12 Sep 2026 21:00:00 GMT')+'</channel></rss>';
const headlines=parseTransferRss(rss,'BBC Sport',now);assert.equal(headlines.length,1);assert.equal(headlines[0].title,'Transfer gossip: A & B');assert.equal(headlines[0].detail,'Transfer report · may include speculation');assert.throws(()=>parseTransferRss('<html>error</html>','BBC Sport',now));
const event={id:'match',date:'2026-09-13T01:00:00Z',links:[{href:'https://www.espn.com/soccer/match/_/gameId/1'}],competitions:[{status:{type:{state:'pre',shortDetail:'Scheduled'}},competitors:[{homeAway:'away',team:{displayName:'Away'},score:'0'},{homeAway:'home',team:{displayName:'Home'},score:'0'}]}]};
assert.equal(parseScoreboard({events:[event]},'League',now)[0].title,'Home vs Away');event.competitions[0].status.type.state='post';event.competitions[0].competitors[1].score='2';assert.equal(parseScoreboard({events:[event]},'League',now)[0].title,'Home 2 – 0 Away');event.date='2026-08-01T00:00:00Z';assert.equal(parseScoreboard({events:[event]},'League',now).length,0);assert.throws(()=>parseScoreboard({},'League',now));
console.log('Island news: RSS decoding, safe links, fresh dates, reports labeling, fixture/result status and malformed sources passed.');
event.date='2026-09-12T20:00:00Z';event.competitions[0].competitors[1].id='home';event.competitions[0].details=[{scoringPlay:true,team:{id:'home'},athletesInvolved:[{displayName:'Finisher'}],clock:{displayValue:"45'+2'"},penaltyKick:true},{scoringPlay:true,team:{id:'home'},athletesInvolved:[{displayName:'Defender'}],clock:{displayValue:"81'"},ownGoal:true},{scoringPlay:true,shootout:true,team:{id:'home'},athletesInvolved:[{displayName:'Shootout'}],clock:{displayValue:"120'"}},{scoringPlay:false,redCard:true}];const report=parseScoreboard({events:[event]},'League',now)[0].match;assert.equal(report.goals.length,2);assert.equal(report.goals[0].minute,"45'+2'");assert(report.goals[0].penalty&&report.goals[1].ownGoal&&report.goalsComplete);event.competitions[0].details.pop();event.competitions[0].details[0].athletesInvolved=[];assert(!parseScoreboard({events:[event]},'League',now)[0].match.goalsComplete);console.log('PASS verified scorer/minute details, stoppage time, own goals, penalties, shootout exclusion and incomplete data');

assert.equal(parseScoreboard({events:[event]},"jpn.1",now)[0].league,"jpn.1","league ID survives parsing for scoped conversations");
