const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/jetpackActions.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,Math,require:(id)=>{assert.equal(id,'./exploreActivity');return{recordExploreActivity:()=>{}};}});const {createJetpackActions}=mod.exports;
const jet=createJetpackActions(),p={x:0,z:0},env={blocked:(x,z)=>z>20,floor:()=>6};let height=28;jet.start(0,height,0,null);for(let i=0;i<60;i++)height=jet.update(1/60,p,height,env).height;assert.ok(p.z>19&&p.z<=20);assert.equal(jet.state.phase,'idle');
jet.start(1,height,0,{x:2,z:4});let top=height,seen=new Set(),landed=false;for(let i=0;i<1800&&!landed;i++){seen.add(jet.state.phase);const result=jet.update(1/60,p,height,env);height=result.height;top=Math.max(top,height);landed=result.landed;}assert.ok(seen.has('charge')&&seen.has('blast')&&seen.has('parachute'));assert.ok(top>135);assert.equal(landed,true);assert.equal(height,6);assert.ok(Math.hypot(p.x-2,p.z-4)<.01);assert.equal(jet.state.phase,'idle');console.log('Jetpack: bounded forward boost, charge, higher blast, parachute and safe touchdown passed.');

const cutJet=createJetpackActions(),cutPoint={x:0,z:0};let cutHeight=28;cutJet.start(1,cutHeight,0,{x:0,z:0});while(cutJet.state.phase!=='parachute')cutHeight=cutJet.update(1/60,cutPoint,cutHeight,env).height;cutJet.cut();assert.equal(cutJet.state.phase,'fall');let crashed=false;for(let i=0;i<600&&!crashed;i++){const result=cutJet.update(1/60,cutPoint,cutHeight,env);cutHeight=result.height;crashed=!!result.crashed;}assert.equal(crashed,true);assert.equal(cutHeight,6);console.log('Jetpack cut: chute detaches, gravity fall, crash landing passed.');

const obstacleFall=createJetpackActions(),unsafePoint={x:0,z:0};obstacleFall.crash();let fallHeight=15,impact;
for(let i=0;i<300;i++){impact=obstacleFall.update(1/60,unsafePoint,fallHeight,{blocked:()=>false,floor:(x)=>x===0?4:2,findLanding:()=>({x:3,z:0})});fallHeight=impact.height;if(impact.landed)break;}
assert(impact.landed&&impact.crashed);assert.equal(unsafePoint.x,3);assert.equal(fallHeight,2);
const noSpot=createJetpackActions(),waitingPoint={x:0,z:0};noSpot.crash();let waitingHeight=2;
for(let i=0;i<120;i++){const result=noSpot.update(1/60,waitingPoint,waitingHeight,{blocked:()=>false,floor:()=>0,findLanding:()=>null});waitingHeight=result.height;assert(!result.landed,'no unsafe touchdown when a landing cannot be found');}
console.log('FALL_OBSTACLE_PASS safe relocation, destination height and no unsafe fallback');

const playful=createJetpackActions(),point={x:0,z:0};let altitude=300;playful.start(1,altitude,0,{x:0,z:0});const clear={blocked:()=>false,floor:()=>0,steer:{x:1,z:0},findLanding:(x,z)=>({x,z}),scanHeld:true};while(playful.state.phase!=='parachute')altitude=playful.update(1/60,point,altitude,clear).height;
assert(playful.parachuteAction(0,1));const initialSpeed=playful.state.scanSpeed;for(let i=0;i<180;i++)altitude=playful.update(1/60,point,altitude,clear).height;assert(playful.state.scanSpeed>initialSpeed);assert(playful.state.scanSpeed<=4.5);assert(point.x>0,'steering stays active');clear.scanHeld=false;playful.update(.05,point,altitude,clear);assert(playful.state.scanSpeed>0&&playful.state.scanSpeed<4.5,'release eases');for(let i=0;i<120;i++)playful.update(1/60,point,altitude,clear);assert.equal(playful.state.scanAge,-1);assert(playful.parachuteAction(1,0));assert.equal(playful.state.juggleAge,0);const before=altitude;altitude=playful.update(.1,point,altitude,clear).height;assert(Math.abs(before-altitude-.9)<1e-6,'air juggling preserves descent');assert(playful.state.juggleAge>0);const frozen=playful.state.juggleAge;playful.update(0,point,altitude,clear);assert.equal(playful.state.juggleAge,frozen,'paused juggling sleeps');assert(playful.parachuteAction(1,0));assert.equal(playful.state.juggleAge,-1,'second press stops juggle');playful.parachuteAction(1,0);playful.cut();assert.equal(playful.state.juggleAge,-1);assert(!playful.parachuteAction(0,0));playful.reset();assert.equal(playful.state.scanSpeed,0);console.log('Parachute actions: hold acceleration, capped speed, eased release, juggling toggle, steering and cancellation passed.');
const lowJuggle=createJetpackActions(),lowPoint={x:0,z:0};lowJuggle.state.phase='parachute';lowJuggle.state.target={x:0,z:0};lowJuggle.parachuteAction(1,0);let lowHeight=.15,lowLanded=false;for(let i=0;i<30&&!lowLanded;i++){const r=lowJuggle.update(1/60,lowPoint,lowHeight,{blocked:()=>false,floor:()=>0});lowHeight=r.height;lowLanded=r.landed;assert(lowHeight>=0);}assert(lowLanded);assert.equal(lowJuggle.state.juggleAge,-1);console.log('Air juggling clears on safe touchdown.');

const spiral=createJetpackActions(),spiralPoint={x:0,z:0},spiralEnv={blocked:()=>false,floor:()=>0,scanHeld:true,findLanding:(x,z)=>({x,z})};spiral.state.phase='parachute';spiral.state.target={x:0,z:0};spiral.parachuteAction(0,0);let spiralHeight=200,earlyRadius=0;
for(let i=0;i<300;i++){spiralHeight=spiral.update(1/60,spiralPoint,spiralHeight,spiralEnv).height;if(i===30)earlyRadius=spiral.state.scanRadius;assert(spiral.state.scanRadius<=3.2);assert(Math.hypot(spiralPoint.x,spiralPoint.z)<=3.201,'unsteered orbit stays within radius cap');}assert(spiral.state.scanRadius>earlyRadius+1,'holding widens spiral');assert(spiral.state.scanIntensity<=1);spiralEnv.scanHeld=false;const releaseRadius=spiral.state.scanRadius;spiralHeight=spiral.update(1/60,spiralPoint,spiralHeight,spiralEnv).height;assert(spiral.state.scanRadius<releaseRadius&&spiral.state.scanRadius>releaseRadius*.8,'release eases without snapping');for(let i=0;i<180;i++)spiralHeight=spiral.update(1/60,spiralPoint,spiralHeight,spiralEnv).height;assert(Math.hypot(spiralPoint.x,spiralPoint.z)<.01,'release returns to glide center');
const narrow=createJetpackActions(),narrowPoint={x:0,z:0};narrow.state.phase='parachute';narrow.state.target={x:0,z:0};narrow.parachuteAction(0,0);let nh=90;for(let i=0;i<300;i++){nh=narrow.update(1/60,narrowPoint,nh,{...spiralEnv,scanHeld:true,blocked:(x)=>x>.3}).height;assert(narrowPoint.x<=.30001,'spiral respects wall');}
const landingSpiral=createJetpackActions(),landPoint={x:0,z:0};landingSpiral.state.phase='parachute';landingSpiral.state.target={x:0,z:0};landingSpiral.parachuteAction(0,0);let lh=35,didLand=false;for(let i=0;i<400&&!didLand;i++){const r=landingSpiral.update(1/60,landPoint,lh,{...spiralEnv,scanHeld:true});lh=r.height;didLand=r.landed;if(lh<7.8)assert.equal(landingSpiral.state.scanRadius,0,'spiral fades before touchdown');}assert(didLand);assert.equal(landingSpiral.state.scanIntensity,0);console.log('Spiral: gradual radius cap, release easing, collision clipping and near-ground landing passed.');

const stillSpin=createJetpackActions(),stillPoint={x:0,z:0};stillSpin.state.phase='parachute';stillSpin.state.target={x:0,z:0};stillSpin.parachuteAction(0,0);for(let i=0;i<120;i++)stillSpin.update(1/60,stillPoint,100,{...spiralEnv,scanHeld:true,reducedMotion:true});assert.equal(stillSpin.state.scanRadius,0);assert.equal(stillSpin.state.scanIntensity,0);assert.deepEqual(stillPoint,{x:0,z:0});console.log('Reduced motion skips the spiral while descent remains available.');
