const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/jetpackActions.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,Math});const {createJetpackActions}=mod.exports;
const jet=createJetpackActions(),p={x:0,z:0},env={blocked:(x,z)=>z>20,floor:()=>6};let height=28;jet.start(0,height,0,null);for(let i=0;i<60;i++)height=jet.update(1/60,p,height,env).height;assert.ok(p.z>19&&p.z<=20);assert.equal(jet.state.phase,'idle');
jet.start(1,height,0,{x:2,z:4});let top=height,seen=new Set(),landed=false;for(let i=0;i<1800&&!landed;i++){seen.add(jet.state.phase);const result=jet.update(1/60,p,height,env);height=result.height;top=Math.max(top,height);landed=result.landed;}assert.ok(seen.has('charge')&&seen.has('blast')&&seen.has('parachute'));assert.ok(top>135);assert.equal(landed,true);assert.equal(height,6);assert.ok(Math.hypot(p.x-2,p.z-4)<.01);assert.equal(jet.state.phase,'idle');console.log('Jetpack: bounded forward boost, charge, higher blast, parachute and safe touchdown passed.');

const cutJet=createJetpackActions(),cutPoint={x:0,z:0};let cutHeight=28;cutJet.start(1,cutHeight,0,{x:0,z:0});while(cutJet.state.phase!=='parachute')cutHeight=cutJet.update(1/60,cutPoint,cutHeight,env).height;cutJet.cut();assert.equal(cutJet.state.phase,'fall');let crashed=false;for(let i=0;i<600&&!crashed;i++){const result=cutJet.update(1/60,cutPoint,cutHeight,env);cutHeight=result.height;crashed=!!result.crashed;}assert.equal(crashed,true);assert.equal(cutHeight,6);console.log('Jetpack cut: chute detaches, gravity fall, crash landing passed.');

const obstacleFall=createJetpackActions(),unsafePoint={x:0,z:0};obstacleFall.crash();let fallHeight=15,impact;
for(let i=0;i<300;i++){impact=obstacleFall.update(1/60,unsafePoint,fallHeight,{blocked:()=>false,floor:(x)=>x===0?4:2,findLanding:()=>({x:3,z:0})});fallHeight=impact.height;if(impact.landed)break;}
assert(impact.landed&&impact.crashed);assert.equal(unsafePoint.x,3);assert.equal(fallHeight,2);
const noSpot=createJetpackActions(),waitingPoint={x:0,z:0};noSpot.crash();let waitingHeight=2;
for(let i=0;i<120;i++){const result=noSpot.update(1/60,waitingPoint,waitingHeight,{blocked:()=>false,floor:()=>0,findLanding:()=>null});waitingHeight=result.height;assert(!result.landed,'no unsafe touchdown when a landing cannot be found');}
console.log('FALL_OBSTACLE_PASS safe relocation, destination height and no unsafe fallback');
