const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),path=require('node:path');
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,Math,Map,WeakMap,require:id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id)});cache.set(file,mod.exports);return mod.exports;}
const {lessonPositions,lessonVisualFrame,lessonStepSeconds}=load('lib/town/formatLessons.ts'),{teachingMotion}=load('lib/town/teachingMotion.ts'),{venueById}=load('lib/town/venues.ts');
const lesson={id:'multi-action',fmt:'7v7',name:'Carry, pass, change direction and receive',ball:{x:50,y:350},offense:[{id:'a',label:'A',x:50,y:350},{id:'b',label:'B',x:200,y:220}],defense:[],questions:[],steps:[{desc:'Carry, pass to support, change direction and receive the return.',dur:3,ball:{x:120,y:230},moves:[{id:'a',to:{x:120,y:230}}],beats:[{label:'Carry',start:0,end:.3,moves:[{id:'a',to:{x:100,y:300}}],ball:{x:100,y:300}},{label:'Pass and change direction',start:.3,end:.65,moves:[{id:'a',to:{x:80,y:260}}],ball:{x:200,y:220}},{label:'Receive the return',start:.65,end:1}]}]};
const v=venueById('7v7');
assert.equal(lessonVisualFrame(lesson,0,.4).label,'Pass and change direction');assert.equal(lessonVisualFrame(lesson,0,.4).count,3);
for(const t of [.3,.65]){const a=lessonPositions(lesson,0,t-1e-7),b=lessonPositions(lesson,0,t+1e-7);for(const [id,p]of a.positions){const q=b.positions.get(id);assert(Math.hypot(p.x-q.x,p.y-q.y)<.001,'continuous beat junction '+id);}assert(Math.hypot(a.ball.x-b.ball.x,a.ball.y-b.ball.y)<.001,'continuous ball junction');}
const pass=teachingMotion(lesson,v,0,.4),back=teachingMotion(lesson,v,0,.8);assert.equal(pass.source,'a');assert.equal(pass.receiver,'b');assert.equal(back.source,'b');assert.equal(back.receiver,'a');assert(pass.pass&&back.pass,'two distinct passes in one step');
const a=lessonPositions(lesson,0,.1).positions.get('a'),b=lessonPositions(lesson,0,.2).positions.get('a'),c=lessonPositions(lesson,0,.4).positions.get('a'),d=lessonPositions(lesson,0,.5).positions.get('a');assert(b.x>a.x&&d.x<c.x,'actual direction change inside one step');
for(const t of [.05,.2,.4,.7,.9,1])assert.deepEqual(lessonPositions(lesson,0,t),lessonPositions(lesson,0,t),'seek deterministic');
assert.equal(JSON.stringify(lessonPositions(lesson,0,1).positions.get('a')),JSON.stringify(lesson.steps[0].moves[0].to));
let authored=0,beats=0;for(const format of ['futsal','7v7','9v9','11v11'])for(const l of JSON.parse(fs.readFileSync('public/lessons/'+format+'.json')))for(const [index,step]of l.steps.entries())if(step.beats?.length){authored++;let last=0;for(const beat of step.beats){assert.equal(beat.start,last,l.id+' continuous timing');assert(beat.end>beat.start);assert(beat.label.trim());last=beat.end;const sample=lessonPositions(l,index,(beat.start+beat.end)/2);for(const p of [...sample.positions.values(),sample.ball])assert(Number.isFinite(p.x)&&Number.isFinite(p.y));beats++;}assert.equal(last,1);assert(lessonStepSeconds(step)>=step.beats.length*2);}
assert(authored>=30);console.log('LESSON_BEATS_PASS',{authoredSteps:authored,beats,twoPasses:true,directionChange:true,continuous:true});
