const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm'),path=require('node:path');
function setup(env){const cache=new Map(),data=new Map(),events=[];function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const mod={exports:{}};cache.set(file,mod);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{esModuleInterop:true,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,process:{env:{NODE_ENV:env}},Math,Date,JSON,Set,Map,localStorage:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},window:{dispatchEvent:e=>events.push(e),addEventListener(){},removeEventListener(){}},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},require:id=>id==='react'?{useSyncExternalStore:()=>{}}:id.endsWith('.json')?JSON.parse(fs.readFileSync(path.resolve(path.dirname(file),id),'utf8')):id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id)});return mod.exports;}return {load,data,events};}
// Every path story (6 cards + 12 upcoming) resolves to a riso print: the registry lists it and lib/paths/riso/stories/<id>.ts exports a story with that id.
{const {load}=setup('development'),catalog=load('lib/paths/stories.ts'),upcoming=load('lib/paths/upcomingStories.ts'),registry=fs.readFileSync('lib/paths/riso/registry.ts','utf8');
 const ids=[...catalog.STORY_CARDS.map(c=>c.id),...Object.values(upcoming.UPCOMING_STORIES).flat().map(s=>s.id)];assert.equal(new Set(ids).size,18);
 const listed=registry.match(/RISO_STORY_IDS=\[([^\]]+)\]/)[1].match(/'[^']+'/g).map(s=>s.slice(1,-1));assert.deepEqual([...listed].sort(),[...ids].sort(),'registry lists every path story');
 const timing=JSON.parse(fs.readFileSync('lib/paths/riso/data/narrationTiming.json','utf8'));
 for(const id of ids){const file=`lib/paths/riso/stories/${id}.ts`;assert(fs.existsSync(file),`${file} exists`);const src=fs.readFileSync(file,'utf8');assert(src.includes(`id:'${id}'`)&&/export const story\s*:\s*RisoStory/.test(src),`${id} exports a RisoStory with its id`);
  if(src.includes("mode:'chapters'"))assert.equal(timing[id]?.length,6,`${id}: six chapter durations in narrationTiming.json`);else assert(/mode:'track'/.test(src),`${id}: chapters or track audio`);}
 assert(!fs.existsSync('lib/paths/films')&&!fs.existsSync('components/AnimatedPathFilm.tsx'),'old story visual system removed');}
for(const env of ['development','production']){const {load,data,events}=setup(env),catalog=load('lib/paths/stories.ts'),store=load('lib/town/learningProgress.ts');assert.equal(catalog.STORY_CARDS.length,6);for(const c of catalog.STORY_CARDS.filter(c=>c.id!=='futsl')){const node=Object.values(catalog.CHAPTER_STORIES).flat().find(n=>n.id===c.id);assert(node);assert.equal(catalog.storyAvailable(c.id,node.afterStage,[],[]),env==='development');assert(catalog.storyAvailable(c.id,node.afterStage,[node.afterStage],[]));assert(catalog.storyAvailable(c.id,node.afterStage,[],[c.id]));}
store.launchLearning('support');const before=data.get(store.LEARNING_KEY),count=events.length;store.launchLearning('support','paths-preview',5);if(env==='development'){assert(store.isLearningPreview());assert.equal(store.readLearning().journeys.support.cursor.stage,5);const quest=load('lib/town/questProgress.ts'),quiz=load('lib/town/quizProgress.ts'),manifest=JSON.parse(fs.readFileSync('lib/town/quizManifest.json'));const [lesson]=Object.keys(manifest.futsal);quest.recordQuestStep('futsal',lesson,0);quest.recordQuestVisit('futsal');quiz.recordCorrectQuizAnswer('futsal',lesson,0);assert.equal(data.get(quest.QUEST_STORAGE_KEY),undefined);assert.equal(data.get(quiz.QUIZ_STORAGE_KEY),undefined);store.answerLearning('support',5,'x',0,0,true);store.completeLearningStage('support',5);store.exposeLearning('support','x','hint');store.saveLearningCursor('support',{stage:5,step:1,quiz:true,question:0,answer:0});assert.equal(data.get(store.LEARNING_KEY),before);assert.equal(store.readLearning().journeys.support.attempts.length,0);assert.equal(store.readLearning().journeys.support.completed.length,0);store.endLearningPreview();assert.equal(JSON.stringify(store.readLearning()),before);}else{assert(!store.isLearningPreview());assert.equal(events.length,count);assert.equal(data.get(store.LEARNING_KEY),before);}}
const css=fs.readFileSync('components/StoryFilmPlayer.module.css','utf8');assert(!css.includes('infinite'));const ui=fs.readFileSync('components/QuestLearningPath.tsx','utf8');assert(ui.includes("else if(stop.story)openStory(stop.story,event.currentTarget)"));assert(ui.includes("dynamic(()=>import('./PathStoryModal')"));const modal=fs.readFileSync('components/PathStoryModal.tsx','utf8'),upcomingUi=fs.readFileSync('components/UpcomingStory.tsx','utf8');assert(!/Film from '\.\/(LoveFutsl|Grit|RegulatingEmotions|AnimatedPath)/.test(modal+upcomingUi));assert(upcomingUi.includes("loadRisoStory")&&upcomingUi.includes('StoryFilmPlayer'));console.log('PATH_STORIES_PASS: 18 riso stories registered and built, six cards with production locks, isolated local preview, no progress writes, riso-only player, finite CSS');
