const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript'),path=require('path'),T=require('three');function load(file){const m={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,Math,require:id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id)});return m.exports;}
const {createPlayer}=load('lib/graphics/player.ts'),{playerBatch}=load('lib/graphics/playerBatch.ts'),scene=new T.Scene(),batch=playerBatch(scene),rigs=Array.from({length:22},(_,i)=>createPlayer('p'+i,i%2?'away':'home',false));
function draw(order=rigs){batch.begin();for(const r of order){r.update(0,0,.033,1,false);batch.draw(r.root);}batch.end();}
draw();const meshes=scene.children.filter(o=>o.isInstancedMesh);assert.equal(meshes.length,10,'22 match players retain shared geometry batches');const versions=meshes.map(o=>o.instanceColor.version);draw();assert.deepEqual(meshes.map(o=>o.instanceColor.version),versions,'Unchanged colors never upload again');draw([...rigs].reverse());assert(meshes.some((o,i)=>o.instanceColor.version>versions[i]),'Reordered team colors upload');for(const o of meshes){const color=new T.Color();for(let i=0;i<o.count;i++){o.getColorAt(i,color);assert(Number.isFinite(color.r+color.g+color.b));}}
const reordered=meshes.map(o=>o.instanceColor.version);draw([...rigs].reverse());assert.deepEqual(meshes.map(o=>o.instanceColor.version),reordered);batch.begin();batch.end();assert(meshes.every(o=>!o.visible));draw(rigs.slice(0,2));assert(meshes.every(o=>o.count>=0));const shortBytes=meshes.reduce((sum,o)=>sum+o.instanceMatrix.updateRanges.reduce((n,r)=>n+r.count*4,0),0),capacityBytes=meshes.reduce((sum,o)=>sum+o.instanceMatrix.array.byteLength,0);assert(shortBytes<capacityBytes/10,'Small crowds do not upload unused buffer capacity');
const hiddenVersions=meshes.map(o=>o.instanceMatrix.version);batch.begin();batch.end();assert.deepEqual(meshes.map(o=>o.instanceMatrix.version),hiddenVersions,'Empty batches perform no matrix uploads');
draw(rigs);for(const o of meshes){assert.equal(o.instanceMatrix.updateRanges.length,1);assert.equal(o.instanceMatrix.updateRanges[0].start,0);assert.equal(o.instanceMatrix.updateRanges[0].count,o.count*16,'Reappearing crowd uploads every populated matrix');const matrix=new T.Matrix4();for(let i=0;i<o.count;i++){o.getMatrixAt(i,matrix);assert(matrix.elements.every(Number.isFinite));}}
console.log('PASS bounded matrix uploads: shrink, empty, and full crowd reappearance');batch.dispose();rigs.forEach(r=>r.dispose());console.log('PASS 22 players / 10 batches; stable colors skip uploads; reorder, hide and reappear remain valid');
// Cached render groups must refresh when source appearance changes.
const changedScene=new T.Scene(),changedBatch=playerBatch(changedScene,16),source=new T.Group(),part=new T.Mesh(new T.BoxGeometry(1,1,1),new T.MeshStandardMaterial({color:'#aacc88',roughness:.7}));source.add(part);
function changedDraw(){changedBatch.begin();changedBatch.draw(source);changedBatch.end();return changedScene.children.filter(o=>o.isInstancedMesh&&o.visible);}
assert.equal(changedDraw().length,1);part.material.roughness=.2;assert.equal(changedDraw()[0].material.roughness,.2,'Roughness change refreshes group');part.material.side=T.DoubleSide;assert.equal(changedDraw()[0].material.side,T.DoubleSide,'Side change refreshes group');part.geometry=new T.SphereGeometry(.4,8,6);assert.equal(changedDraw()[0].geometry.type,'SphereGeometry','Geometry change refreshes group');part.material=part.material.clone();part.material.color.set('#ee3344');const rgb=new T.Color();changedDraw()[0].getColorAt(0,rgb);assert(Math.abs(rgb.r-part.material.color.r)<1e-6,'Replacement material color reaches the current slot');source.visible=false;assert.equal(changedDraw().length,0);source.visible=true;assert.equal(changedDraw().length,1);changedBatch.dispose();part.geometry.dispose();part.material.dispose();console.log('PASS cached render bindings refresh on geometry/material changes and retain visibility');
