const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const vm=require('node:vm');
const output=ts.transpileModule(fs.readFileSync('lib/town/simulation.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const travelMod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/travelModes.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:travelMod.exports,module:travelMod});
const shoreMod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/shoreline.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:shoreMod.exports,module:shoreMod,Math});
const ferryMod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/ferryBoarding.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:ferryMod.exports,module:ferryMod,Math});
const mod={exports:{}};vm.runInNewContext(output,{exports:mod.exports,module:mod,Math,require:id=>{if(id==='./travelModes')return travelMod.exports;if(id==='./shoreline')return shoreMod.exports;if(id==='./ferryBoarding')return ferryMod.exports;throw new Error(id);}});
const {stepPlayer,blocked,districtAt,DISTRICTS}=mod.exports;
function run(input,steps=120){const pos={x:0,z:0},v={x:0,z:0};for(let i=0;i<steps;i++)stepPlayer(pos,v,input,1/60,[]);return {pos,v};}
const straight=run({x:1,z:0,sprint:false});const diagonal=run({x:1,z:1,sprint:false});
assert.ok(Math.abs(Math.hypot(diagonal.pos.x,diagonal.pos.z)-straight.pos.x)<.0001,'Diagonal movement must not be faster');
assert.ok(run({x:1,z:0,sprint:true}).pos.x>straight.pos.x,'Sprint increases speed');
const pos={x:0,z:0},velocity={x:0,z:0};for(let i=0;i<240;i++)stepPlayer(pos,velocity,{x:1,z:1,sprint:false},1/60,[{x:2,z:0,w:1,d:40}]);
assert.ok(pos.x<=1.18,'Player cannot enter a wall');assert.ok(pos.z>5,'Player slides along a wall');
for(let i=0;i<120;i++)stepPlayer(pos,velocity,{x:0,z:0,sprint:false},1/60,[]);assert.ok(Math.hypot(velocity.x,velocity.z)<.001,'Player decelerates to rest');
assert.equal(blocked(-103,0,[]),true);assert.equal(blocked(0,-260,[]),true);assert.equal(blocked(0,-206,[]),false,'Expanded north beach stays walkable');
for(const [key,value] of Object.entries(DISTRICTS))assert.equal(districtAt(value.z),key,'Destinations land in the right district');
console.log('Town simulation: diagonal speed, sprint, collision, wall sliding, braking, boundaries and travel passed.');
const {crossedGoal}=mod.exports;
assert.equal(crossedGoal({x:11,z:4},{x:11,z:3}),true,'Shot crossing goal line scores');
assert.equal(crossedGoal({x:11,z:3},{x:11,z:4}),false,'Entering from behind the goal does not score');
assert.equal(crossedGoal({x:15,z:4},{x:15,z:3}),false,'Wide shot does not score');
assert.equal(crossedGoal({x:11,z:3},{x:11,z:3}),false,'Stationary ball cannot score repeatedly');
assert.equal(crossedGoal({x:11,z:-49},{x:11,z:-50}),true,'Night court goal works');
console.log('Goal detection: forward crossing, direction, posts, stationary ball and night court passed.');
const learning=ts.transpileModule(fs.readFileSync('lib/town/learning.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
const lessonMod={exports:{}};vm.runInNewContext(learning,{exports:lessonMod.exports,module:lessonMod,Math});
const {passingLane}=lessonMod.exports;
assert.equal(passingLane({x:11,z:9}).open,false,'Defender blocks initial position');
assert.equal(passingLane({x:5,z:9}).open,true,'Left passing angle opens');
assert.equal(passingLane({x:17,z:9}).open,true,'Right passing angle opens');
assert.equal(passingLane({x:11,z:21}).open,false,'Standing on the passer is not a solution');
assert.equal(passingLane({x:11,z:18}).open,false,'Walking through the defender cannot bypass the exercise');
assert.equal(passingLane({x:-3,z:9}).open,false,'Outside the court is not a valid solution');
assert.ok(Number.isFinite(passingLane({x:11,z:21}).clearance),'Zero-length passing lane stays finite');
console.log('Learning: blocked lane, two valid angles, court bounds and invalid shortcuts passed.');
