const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript'),path=require('path'),T=require('three');
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const m={exports:{}};cache.set(file,m.exports);vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{module:m,exports:m.exports,Math,require:id=>id.startsWith('.')?load(path.resolve(path.dirname(file),id+'.ts')):require(id)});return m.exports;}
const {createVolleyballGame}=load('lib/graphics/volleyballGame.ts'),{createPlayer}=load('lib/graphics/player.ts'),{DEFAULT_CUSTOMIZATION}=load('lib/town/customization.ts'),scene=new T.Scene(),hits=new Map(),applied=[];
const game=createVolleyballGame(scene,{get:id=>hits.get(id),apply:(id,root)=>{applied.push(id);root.rotation.z=.8;}}),camera=new T.PerspectiveCamera(50,1,.1,500);
function view(x,y,z,tx,ty,tz){camera.position.set(x,y,z);camera.lookAt(tx,ty,tz);camera.updateMatrixWorld(true);}
function update(hover=null){game.update(1/30,camera,true,false,hover);}
view(72,25,224,72,1,198);for(let i=0;i<30;i++)update();assert(game.root.visible);
const meshes=game.root.getObjectByName('volleyball-player-batches').children.flatMap(g=>g.children);assert.equal(meshes.length,58);assert(meshes.every(m=>m.frustumCulled&&m.castShadow&&m.receiveShadow&&Number.isFinite(m.boundingSphere.radius)&&m.boundingSphere.radius<3));
let priorMeshes=0,priorTriangles=0;for(let i=0;i<game.entries.length;i++){const e=game.entries[i],rig=createPlayer(e.id,i<2?'home':'away');rig.setAppearance({...DEFAULT_CUSTOMIZATION,character:e.definition.character,face:e.definition.face,clothing:e.definition.clothing});rig.root.traverseVisible(o=>{if(o.isMesh){priorMeshes++;priorTriangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;}});rig.dispose();}
const triangles=meshes.reduce((n,m)=>n+m.count*(m.geometry.index?.count??m.geometry.attributes.position.count)/3,0);assert.equal(triangles,priorTriangles,'same visible body triangle count');
for(const e of game.entries){assert(!e.fallback.visible&&e.drawn.visible,'fully visible source rigs cannot double-render');const ray=new T.Raycaster(new T.Vector3(e.position.x,1,e.position.z+4),new T.Vector3(0,0,-1));assert.equal(game.pick(ray)?.id,e.id,'ray pick retains each character identity');assert.equal(game.nearest({x:e.position.x,y:0,z:e.position.z},1)?.id,e.id);}
const time=game.stats.clock,versions=meshes.map(m=>m.instanceMatrix.version),ball=game.ball.position.clone();for(let i=0;i<20;i++)update(game.entries[0].id);assert.equal(game.stats.clock,time);assert(game.ball.position.equals(ball));assert.deepEqual(meshes.map(m=>m.instanceMatrix.version),versions,'hover-frozen poses do not upload again');
const e=game.entries[0];hits.set('npc:'+e.id,{age:.3});update();assert(applied.includes('npc:'+e.id));assert.equal(e.rig.root.rotation.z,.8);assert(meshes.some((m,i)=>m.instanceMatrix.version>versions[i]),'hit pose refreshes batches');assert.equal(game.pick(new T.Raycaster(new T.Vector3(e.position.x,1,e.position.z+4),new T.Vector3(0,0,-1))),null,'stunned character is not clickable');hits.clear();update();assert(game.stats.clock>time);
const visibleTime=game.stats.clock,hiddenVersions=meshes.map(m=>m.instanceMatrix.version);view(72,25,224,72,25,324);for(let i=0;i<30;i++)update();assert(!game.root.visible);assert.equal(game.stats.clock,visibleTime);assert.deepEqual(meshes.map(m=>m.instanceMatrix.version),hiddenVersions);assert.equal(game.pick(new T.Raycaster()),null);view(72,25,224,72,1,198);update();assert(game.root.visible&&game.stats.clock>visibleTime);

// Same mobile follow camera: high-flight edge keeps baseline per-part visibility.
camera.fov=40;camera.aspect=440/760;camera.updateProjectionMatrix();view(88,52,229,72,29,196);for(let i=0;i<30;i++)update();assert(game.entries.some(e=>e.fallback.visible),'edge uses original merged rig culling');assert(game.entries.every(e=>e.drawn.visible!==e.fallback.visible),'exactly one representation per character');
const fallback=game.entries.filter(e=>e.fallback.visible),fallbackVersions=fallback.map(e=>e.drawn.children.map(m=>m.instanceMatrix.version));update();fallback.forEach((e,i)=>assert.deepEqual(e.drawn.children.map(m=>m.instanceMatrix.version),fallbackVersions[i],'fallback poses do not upload hidden batches'));
scene.updateMatrixWorld(true);const edgeFrustum=new T.Frustum().setFromProjectionMatrix(new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse));let edgeTriangles=0;game.root.traverseVisible(o=>{if(o.isMesh&&(!o.frustumCulled||edgeFrustum.intersectsObject(o)))edgeTriangles+=(o.isInstancedMesh?o.count:1)*(o.geometry.index?.count??o.geometry.attributes.position.count)/3;});assert(edgeTriangles<9000,'edge view does not submit all four bodies');camera.fov=50;camera.aspect=1;camera.updateProjectionMatrix();view(72,25,224,72,1,198);const returnClock=game.stats.clock;update(game.entries[0].id);assert.equal(game.stats.clock,returnClock);fallback.forEach((e,i)=>assert(e.drawn.children.some((m,j)=>m.instanceMatrix.version>fallbackVersions[i][j]),'return to batching uploads current pose even during hover freeze'));assert(game.entries.every(e=>e.drawn.visible&&!e.fallback.visible),'full view restores batches');
const batchCount=meshes.length;game.dispose();assert.equal(scene.children.length,0);console.log(`PASS volleyball ${priorMeshes} meshes -> ${batchCount} batches, ${triangles} unchanged body triangles; identities, hover pause, reactions, culling/resume and cleanup`);
