const assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');const mod={exports:{}};vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/town/walkBall.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports:mod.exports,module:mod,Math,Number});const {createWalkBall}=mod.exports,p={x:0,z:0,y:0,yaw:0};
for(const distance of [.8,1.5,2.5,4,6,8]){let impacts=0,strikes=0,receives=0,last='',maxHeight=0;const ball=createWalkBall(),env={floor:()=>0,blocked:(_x,z)=>z>=distance,impact:()=>impacts++,strike:()=>strikes++};ball.juggle(p,{x:0,z:distance});for(let i=0;i<1200;i++){ball.update(1/120,p,env);assert.equal(ball.state.mode,'wall-juggle','Drill continues at '+distance);assert(ball.state.z<distance,'Ball never crosses wall');assert(ball.state.y>=.2-1e-5);maxHeight=Math.max(maxHeight,ball.state.y);if(ball.state.wallPhase==='receive'&&last!=='receive')receives++;last=ball.state.wallPhase;}assert(impacts>=4&&strikes>=4&&receives>=4,'Repeated kicks, wall bounces and receives at '+distance);assert(maxHeight>1.2,'Ball visibly rises');ball.shoot(p,0);assert.equal(ball.state.mode,'windup');assert.equal(ball.state.wallTarget,null);}
for(const target of [{x:0,z:8.01},{x:0,z:.7},{x:0,z:-2},{x:NaN,z:2}]){const ball=createWalkBall();ball.juggle(p,target);assert.equal(ball.state.mode,'juggle','Invalid wall falls back to normal juggling');}
const ball=createWalkBall(),env={floor:()=>0,blocked:()=>false,impact(){},strike(){}};ball.juggle(p,{x:0,z:3});ball.updateWallTarget({...p,x:5});ball.update(.01,{...p,x:5},env);assert.equal(ball.state.mode,'juggle','Moving away keeps ordinary juggling');ball.reset(p);ball.juggle(p,{x:0,z:3});ball.updateWallTarget({...p,yaw:Math.PI});ball.update(.01,{...p,yaw:Math.PI},env);assert.equal(ball.state.mode,'juggle','Losing the wall keeps ordinary juggling');ball.reset(p);ball.juggle(p,{x:0,z:3});ball.juggle(p,{x:0,z:3});assert.equal(ball.state.mode,'attached','Juggle toggles off');ball.juggle(p,{x:0,z:3});ball.reset(p);assert.equal(ball.state.wallTarget,null);
console.log('Wall juggling: .8–8m ballistic loops, visible arcs, wall bounces, receiving, distance/facing validation, shoot/reset/toggle/movement cancellation passed.');

const adaptive=[];for(const top of [1,2.4,12]){const b=createWalkBall();let max=0,touches=0,bounces=0;const e={floor:()=>0,blocked:(_x,z)=>z>=2.81,impact:()=>bounces++,strike(){},receive:()=>touches++};b.juggle(p);for(let i=0;i<1800;i++){b.updateWallTarget(p,{x:0,z:3,top});b.update(1/120,p,e);max=Math.max(max,b.state.y);assert(['juggle','wall-juggle'].includes(b.state.mode));}assert(touches>=3&&bounces>=3);assert(max<top);adaptive.push(max);}assert(adaptive[2]>adaptive[1]+2&&adaptive[1]>adaptive[0],'Wall height changes the arc');
const approach=createWalkBall();approach.juggle(p);for(let i=0;i<360;i++){approach.updateWallTarget(p,i>120?{x:0,z:3,top:4}:undefined);approach.update(1/120,p,env);}assert.equal(approach.state.mode,'wall-juggle','Approaching while juggling activates automatically');approach.updateWallTarget(p);assert.equal(approach.state.mode,'juggle','Leaving wall never stops juggling');approach.juggle(p);assert.equal(approach.state.mode,'attached','Explicit stop still works');
console.log('Adaptive juggling: ordinary approach, low/high walls, receive callbacks and persistent fallback passed.');

const chain=createWalkBall();let chainReceives=0;const directions=new Set();chain.juggle(p);for(let i=0;i<2400;i++){const time=i/120,moving={x:Math.sin(time*.3)*.4,z:Math.sin(time*.2)*.3,y:0,yaw:time<6?0:Math.PI/2},target=time<6?{x:moving.x,z:3,top:5}:{x:3,z:moving.z,top:8};chain.updateWallTarget(moving,target);chain.update(1/120,moving,{floor:()=>0,blocked:(x,z)=>x>=2.81||z>=2.81,impact(){},strike(){},receive(){chainReceives++;}});assert(['juggle','wall-juggle'].includes(chain.state.mode));assert(Number.isFinite(chain.state.x+chain.state.y+chain.state.z));if(chain.state.wallTarget)directions.add(chain.state.wallTarget.x===3?'east':'north');}assert(chainReceives>=8&&directions.size===2,'Moving feet and adjacent walls keep the sequence going');console.log('Moving wall chain: adjacent walls, side-facing selection and continuous receiving passed.');
const feet=createWalkBall();feet.juggle(p);feet.update(0,p,env);assert(Math.abs(feet.state.y-.48)<1e-8&&Math.abs(feet.state.z-.45)<1e-8&&Math.abs(feet.state.x+.108)<1e-8,'Normal ball meets left foot above ground');feet.update(1.05,p,env);assert(Math.abs(feet.state.x-.108)<1e-8,'Next touch uses right foot');
const varied=createWalkBall(),apexes=[];varied.juggle(p,{x:0,z:3,top:10});let apex=0,firstReceive=0,wasReceive=false;for(let i=0;i<2400;i++){varied.update(1/120,p,{floor:()=>0,blocked:(_x,z)=>z>=2.81,impact(){},strike(){},receive(){}});apex=Math.max(apex,varied.state.y);assert(varied.state.y>=.48-1e-5,'Contact stays above ground');if(varied.state.wallPhase==='receive'&&!wasReceive){apexes.push(apex);apex=0;if(!firstReceive)firstReceive=i/120;}wasReceive=varied.state.wallPhase==='receive';}assert(apexes.length>=5);assert(Math.max(...apexes)-Math.min(...apexes)>3,'Repeated kicks vary near the roofline');assert(Math.max(...apexes)<9.76,'Ball keeps wall-top clearance');assert(firstReceive<1.5,'Higher gravity returns the first high kick promptly');console.log('Foot contact, alternating feet, roofline variation, clearance and faster cycle passed.');

const mix=createWalkBall(),seen=new Set();mix.juggle(p);let previous={...mix.state};for(let i=0;i<1800;i++){mix.update(1/120,p,env);seen.add(mix.state.juggleTouch);if(i>0)assert(Math.hypot(mix.state.x-previous.x,mix.state.y-previous.y,mix.state.z-previous.z)<.12,'Touch transitions stay continuous');previous={...mix.state};}assert.equal(seen.size,5,'Stationary routine includes all five touch styles');for(let i=0;i<1500;i++){mix.update(1/120,p,{...env,moving:true});assert.equal(mix.state.juggleTouch,'foot','Moving uses only foot touches');}console.log('PASS stationary mixed touches, continuous ball path, moving foot-only juggling');
for(const h of [{bottom:1.3,top:2.5,front:.7,width:.6},{bottom:1.3,top:3,front:.85,width:.8}])for(const yaw of [0,1.2,Math.PI]){const b=createWalkBall(),p2={...p,yaw};b.juggle(p2);for(let i=0;i<1800;i++){b.update(1/120,p2,{...env,juggleHead:h});const s=b.state,localX=s.x*Math.cos(yaw)-s.z*Math.sin(yaw),localZ=s.x*Math.sin(yaw)+s.z*Math.cos(yaw),height=(s.y-(h.top+h.bottom)/2)/((h.top-h.bottom)/2+.32);assert(height**2+(localX/(h.width+.32))**2+(localZ/(h.front+.32))**2>=1-1e-8,'Ball remains outside padded costume head');}b.update(.01,p2,env);assert(Number.isFinite(b.state.y),'Unequipping remains valid');}console.log('PASS costume clearance throughout full juggling routine at multiple headings');

const suited=createWalkBall(),costumeStyles=new Set(),costumeHead={bottom:1.3,top:2.5,front:.7,width:.6};suited.juggle(p);for(let i=0;i<1800;i++){suited.update(1/120,p,{...env,juggleHead:costumeHead});costumeStyles.add(suited.state.juggleTouch);}assert.deepEqual([...costumeStyles].sort(),['around-world','foot']);for(let i=0;i<900;i++){suited.update(1/120,p,{...env,juggleHead:costumeHead,moving:true});assert.equal(suited.state.juggleTouch,'foot');}console.log('PASS costumes use feet and stationary around-the-world only');
