'use client';
import {DoneButton} from './DoneButton';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { LESSONS, Lesson } from '@/lib/curriculum';
import { completeLesson, Progress, readProgress, saveProgress } from '@/lib/progress';
import shell from './ModalShell.module.css';
import { Icon } from './Icon';
const Pitch = dynamic(() => import('./Pitch'), { ssr: false, loading: () => <div className="pitch-loading">Preparing your island…</div> });
type Page = 'island' | 'learn' | 'lab' | 'progress';
export default function Academy() {
  const [page,setPage]=useState<Page>('island');
  const [active,setActive]=useState<Lesson|null>(null);
  const [beat,setBeat]=useState(0),[fraction,setFraction]=useState(0),[playing,setPlaying]=useState(false);
  const [challenge,setChallenge]=useState(false),[answer,setAnswer]=useState<string|null>(null),[attempts,setAttempts]=useState(0);
  const [progress,setProgress]=useState<Progress>({}),[filter,setFilter]=useState('All lessons'),[query,setQuery]=useState(''),[aerial,setAerial]=useState(false),[saved,setSaved]=useState(true);
  const [settings,setSettings]=useState(false);
  const timer=useRef(0);
  const fractionRef=useRef(fraction);fractionRef.current=fraction;
  useEffect(()=>{setProgress(readProgress());},[]);
  useEffect(()=>{if(!playing)return;let last=performance.now();const tick=(now:number)=>{const dt=Math.min(now-last,100);last=now;const next=Math.min(1,fractionRef.current+dt/2800);fractionRef.current=next;setFraction(next);if(next>=1){setPlaying(false);return;}timer.current=requestAnimationFrame(tick);};timer.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(timer.current);},[playing,beat]);
  useEffect(()=>{const blur=()=>setPlaying(false);const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){if(settings)setSettings(false);else if(active){setPlaying(false);setActive(null);}}};window.addEventListener('blur',blur);window.addEventListener('keydown',key);return()=>{window.removeEventListener('blur',blur);window.removeEventListener('keydown',key);};},[active,settings]);
  const completed=LESSONS.filter(l=>progress[l.id]);
  const xp=completed.reduce((total,l)=>total+progress[l.id].score,0);
  const next=LESSONS.find(l=>!progress[l.id])||LESSONS[0];
  const navigate=(to:Page)=>{setPage(to);setActive(null);setPlaying(false);};
  const start=(lesson:Lesson,test=false)=>{setActive(lesson);setBeat(0);setFraction(0);setPlaying(false);setChallenge(test);setAnswer(null);setAttempts(0);setAerial(false);};
  const choose=(id:string)=>{if(!active||answer===active.correct)return;setAnswer(id);setAttempts(n=>n+1);if(id===active.correct){const updated=completeLesson(progress,active.id,attempts===0?100:60);setProgress(updated);setSaved(saveProgress(updated));}};
  const advance=()=>{if(!active)return;if(beat<active.beats.length-1){setBeat(n=>n+1);setFraction(0);setPlaying(true);}else{setChallenge(true);setPlaying(false);setAnswer(null);setAttempts(0);}};
  const list=LESSONS.filter(l=>(filter==='All lessons'||l.category===filter)&&(l.title+' '+l.description).toLowerCase().includes(query.toLowerCase()));
  return <div className="academy">
    <aside className="rail"><button className="brand-mark" aria-label="Futbol Island home" onClick={()=>navigate('island')}>f<span>i</span></button><div className="rail-rule"/>{([{id:'island',icon:'globe',label:'My island'},{id:'learn',icon:'book',label:'Learn'},{id:'lab',icon:'target',label:'Decision lab'},{id:'progress',icon:'chart',label:'Progress'}] as const).map(item=><button key={item.id} className={'rail-item '+(page===item.id?'selected':'')} onClick={()=>navigate(item.id)} aria-label={item.label} aria-current={page===item.id?'page':undefined}><Icon name={item.icon}/><span>{item.label}</span></button>)}<div className="rail-bottom"><button className="rail-item" aria-label="About this academy" onClick={()=>setSettings(true)}><Icon name="settings"/><span>About</span></button><div className="avatar">YOU</div></div></aside>
    <main className="main-shell">
      <header className="topbar"><button className="wordmark" onClick={()=>navigate('island')}>futbol<span>island</span><small>THE FOOTBALL ACADEMY</small></button><div className="header-right"><span className="edition">A NEW WAY TO SEE THE GAME</span><span className="xp-chip"><Icon name="star" size={15}/>{xp} XP</span><button className="profile" aria-label="View your progress" onClick={()=>navigate('progress')}>Y</button></div></header>
      {active ? <section className="lesson-screen">
        <div className="lesson-top"><button className="text-button" onClick={()=>{setActive(null);setPlaying(false);}}><Icon name="back" size={17}/>Back to {page==='lab'?'decision lab':'your island'}</button><span className="eyebrow">{active.category} / {challenge?'YOUR DECISION':`BEAT ${beat+1} OF ${active.beats.length}`}</span></div>
        <div className="lesson-grid"><div className="lesson-world"><div className="world-caption"><span className="live-dot"/>TRAINING GROUND <span>01</span></div><Pitch lesson={active} beat={beat} progress={fraction} aerial={aerial} challenge={challenge} selected={answer} onSelect={choose}/><div className="world-tools"><button className={aerial?'tool active':'tool'} onClick={()=>setAerial(!aerial)}><Icon name="expand" size={16}/>{aerial?'Perspective':'Tactical view'}</button><span><i className="team-dot"/>Your team <i className="team-dot away"/>Opposition</span></div></div>
          <div className="coach-panel"><div className="lesson-number">LESSON / {active.number}</div><h1>{active.title}</h1><p className="lesson-description">{active.description}</p>
            {challenge?<><div className="coach-divider"/><span className="eyebrow">READ THE GAME</span><h2>{active.question}</h2><p className="help-text">Choose a player on the pitch or select below.</p><div className="answers">{active.answers.map((option,i)=><button key={option.id} disabled={answer===active.correct} onClick={()=>choose(option.id)} className={'answer '+(answer===option.id?(option.id===active.correct?'correct':'incorrect'):'')}><span>{String.fromCharCode(65+i)}</span>{option.label}{answer===option.id&&<Icon name={option.id===active.correct?'check':'reset'} size={18}/>}</button>)}</div>{answer&&<div className={'feedback '+(answer===active.correct?'success':'')} role="status"><b>{answer===active.correct?'You saw it.':'Look again.'}</b><p>{active.answers.find(a=>a.id===answer)?.feedback||'Look for the unmarked teammate.'}</p>{answer===active.correct&&<><span className="xp-award">{progress[active.id]?.score} XP · LESSON COMPLETED</span><p>{active.takeaway}</p><button className="primary" onClick={()=>{const index=LESSONS.indexOf(active);if(index<LESSONS.length-1)start(LESSONS[index+1]);else navigate('progress');}}> {LESSONS.indexOf(active)<LESSONS.length-1?'Next lesson':'See your progress'}<Icon name="arrow" size={18}/></button></>}</div>}</>:<><div className="beat-tabs">{active.beats.map((_,i)=><button key={i} aria-label={`Go to beat ${i+1}`} className={beat===i?'active':''} onClick={()=>{setBeat(i);setFraction(0);setPlaying(false);}}><span>{String(i+1).padStart(2,'0')}</span></button>)}</div><div className="coach-note"><span className="eyebrow">YOUR COACH</span><h2>{active.beats[beat].title}</h2><p>{active.beats[beat].body}</p></div><div className="playback"><button className="play-button" aria-label={playing?'Pause replay':fraction===1?'Replay beat':'Play beat'} onClick={()=>{if(fraction===1)setFraction(0);setPlaying(!playing);}}><Icon name={playing?'pause':fraction===1?'reset':'play'} size={19}/></button><input type="range" min="0" max="1" step=".01" value={fraction} aria-label="Replay timeline" onChange={e=>{setPlaying(false);setFraction(Number(e.target.value));}}/><span>{Math.round(fraction*100)}%</span></div><button className="primary full" onClick={advance}>{beat===active.beats.length-1?'Your turn to decide':'Next teaching beat'}<Icon name="arrow" size={18}/></button><p className="pacing-note">No rush. Replay any moment, as often as you need.</p></>}
          </div></div>
      </section>:page==='island'?<>
        <div className="welcome-line"><span><i className="live-dot"/>YOUR ISLAND IS READY</span><span>Small sessions. A bigger football brain.</span></div>
        <section className="hero"><div className="hero-copy"><span className="eyebrow">WELCOME TO YOUR FOOTBALL WORLD</span><h1>See the game.<br/><em>Change your game.</em></h1><p>Great players see what others miss.<br/>Build your football instincts, one decision at a time.</p><button className="primary hero-cta" onClick={()=>start(next)}>{completed.length?'Continue your journey':'Step onto the island'}<Icon name="arrow" size={19}/></button><div className="hero-foot"><span className="tiny-ball"><Icon name="ball" size={16}/></span><span>Your pace. Your progress. Your game.</span></div></div><div className="hero-world"><Pitch lesson={next} beat={0} progress={1} overview/><div className="island-label"><Icon name="flag" size={16}/><span>THE TRAINING GROUND<small>Where better decisions begin.</small></span><span className="label-number">01</span></div><div className="world-coordinates">35° 04′ N &nbsp; 25° 11′ E <span>IMAGINATION, NOT A DESTINATION</span></div></div></section>
        <div className="section-heading"><div><span className="eyebrow">A LITTLE BETTER, EVERY DAY</span><h2>Your next move</h2></div><button className="text-button" onClick={()=>navigate('learn')}>Explore all lessons<Icon name="arrow" size={17}/></button></div>
        <section className="next-grid"><button className="featured-card" onClick={()=>start(next)}><div className="card-top"><span className="pill">{completed.length?'CONTINUE LEARNING':'START HERE'}</span><span className="duration"><Icon name="clock" size={14}/>{next.minutes} MIN</span></div><div className="mini-pitch"><div className="mini-centre"/><i className="mini-player one"/><i className="mini-player two"/><i className="mini-player three"/><span className="mini-arrow"><Icon name="external"/></span><span className="mini-caption">LOOK. THINK. PLAY.</span></div><div className="card-bottom"><span className="eyebrow">{next.category} / LESSON {next.number}</span><h3>{next.title}</h3><p>{next.description}</p><span className="round-arrow"><Icon name="arrow" size={20}/></span></div></button>
          <button className="lab-card" onClick={()=>navigate('lab')}><div className="card-top"><span className="pill light">THE DECISION LAB</span><Icon name="target" size={21}/></div><div className="lab-art"><span>A</span><span>B</span><span>C</span><div className="lab-path"/></div><h3>Your instinct.<br/>The next pass.</h3><p>Freeze the moment. Read the pitch.<br/>Make the call.</p><span className="inline-link">Test your football brain<Icon name="arrow" size={17}/></span></button>
          <div className="journey-card"><span className="eyebrow">YOUR JOURNEY</span><div className="journey-stat"><b>{completed.length}<span> / {LESSONS.length}</span></b><Icon name="flag" size={25}/></div><p>concepts understood</p><div className="progress-track"><div style={{width:`${completed.length/LESSONS.length*100}%`}}/></div><div className="journey-note"><Icon name="sun" size={22}/><p>{completed.length?'Good decisions add up. Keep building your understanding.':'Every great player started by noticing one more thing.'}</p></div><button className="text-button" onClick={()=>navigate('progress')}>View your progress<Icon name="arrow" size={17}/></button></div></section>
        <footer className="page-footer"><Icon name="ball" size={16}/><span>FOOTBALL IS A GAME OF POSSIBILITIES. LEARN TO SEE THEM.</span><span>FUTBOL ISLAND</span></footer>
      </>:page==='progress'?<section className="library"><span className="eyebrow">YOUR FOOTBALL JOURNEY</span><h1>Small steps.<br/><em>Real understanding.</em></h1><div className="progress-overview"><div><b>{xp}</b><span>Experience earned</span></div><div><b>{completed.length}/{LESSONS.length}</b><span>Concepts completed</span></div><div><b>{completed.filter(l=>progress[l.id].score===100).length}</b><span>First-time reads</span></div></div><div className="progress-lessons">{LESSONS.map(l=><button key={l.id} onClick={()=>start(l)}><span className={'completion-icon '+(progress[l.id]?'done':'')}>{progress[l.id]?<Icon name="check" size={19}/>:l.number}</span><span><strong>{l.title}</strong><small>{l.category}</small></span><b>{progress[l.id]?`${progress[l.id].score} XP`:'Not started'}</b><Icon name="chevron" size={18}/></button>)}</div>{!saved&&<p role="status">Your browser could not save progress. Keep this tab open to retain this session.</p>}</section>:<section className="library"><span className="eyebrow">{page==='lab'?'THE DECISION LAB':'THE LEARNING GROUND'}</span><h1>{page==='lab'?<>The game pauses.<br/><em>You decide.</em></>:<>Understand the why.<br/><em>Change the way you play.</em></>}</h1><p className="library-description">{page==='lab'?'A real futbo pathion. A clear choice. Feedback that makes the next decision easier.':'Short, visual lessons that turn football ideas into instincts. Start anywhere. Go at your own pace.'}</p><div className="library-tools"><div className="filters">{['All lessons','Possession','Attacking','Defending'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><label className="search"><Icon name="search" size={17}/><input placeholder="Find a concept" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search lessons"/></label></div><div className="lesson-cards">{list.map(l=><button key={l.id} className={'catalog-card tone-'+l.category.toLowerCase()} onClick={()=>start(l,page==='lab')}><div className="catalog-art"><span>{l.number}</span><Icon name={l.category==='Defending'?'people':l.category==='Attacking'?'arrow':'globe'} size={58}/>{progress[l.id]&&<i><Icon name="check" size={18}/></i>}</div><div className="catalog-info"><span className="eyebrow">{l.category} · {l.minutes} MIN</span><h3>{l.title}</h3><p>{l.description}</p><div><span>{l.difficulty}</span><Icon name="arrow" size={19}/></div></div></button>)}</div>{!list.length&&<div className="empty-state"><Icon name="search" size={28}/><h3>No lessons match that search.</h3><button className="text-button" onClick={()=>{setQuery('');setFilter('All lessons');}}>Clear filters</button></div>}</section>}
    </main>
    {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className={`about-modal ${shell.shell}`} role="dialog" aria-modal="true" aria-labelledby="about-title" onClick={e=>e.stopPropagation()}><header className={shell.header}><h2 id="about-title">Football, understood</h2><DoneButton autoFocus onDone={()=>setSettings(false)}/></header><div className={shell.body}><p>Futbol Island is a new, independent learning experience. Watch a short play, make a decision, and learn the reason behind it.</p><p>Your progress stays in this browser. There’s no account, subscription, or connection to the original app.</p><div className="about-detail"><Icon name="heart" size={20}/><span>Built for curiosity. Designed for your pace.</span></div><button className="primary full" onClick={()=>setSettings(false)}>Back to the island<Icon name="arrow" size={17}/></button></div></section></div>}
  </div>;
}
