'use client';
import {useEffect,useState} from 'react';
import {Icon} from './Icon';
import { LessonPhase } from '@/lib/town/learning';
import {PASS_COPY,LESSON_FORMATS,LESSON_ATTEMPTS,REPLAY_SPEED,attemptsLeft,attemptMessage,type AttemptState,type LessonFormat} from '@/lib/town/learningPass';
type Props={phase:LessonPhase;open:boolean;feedback:string;onWatch:()=>void;onPractice:()=>void;onPass:()=>void;onExit:()=>void;
  format:LessonFormat;onFormat:(f:LessonFormat)=>void;attempts:AttemptState;aimStatus:'none'|'clear'|'threat'|'nobody';onStraight:()=>void;onPlay:()=>void;onCancel:()=>void;onReplay:()=>void};
function Formats({format,onFormat}:{format:LessonFormat;onFormat:(f:LessonFormat)=>void}){
  return <div className="lesson-formats"><span className="lesson-caption">EXPLAIN IT FOR</span><div className="lesson-steps" role="group" aria-label="Explain it for">{LESSON_FORMATS.map(f=><button key={f} type="button" aria-pressed={f===format} className={f===format?'current':''} onClick={()=>onFormat(f)}>{f.toUpperCase()}</button>)}</div></div>;
}
export default function CoachLesson({phase,open,feedback,onWatch,onPractice,onPass,onExit,format,onFormat,attempts,aimStatus,onStraight,onPlay,onCancel,onReplay}:Props){
  const copy=PASS_COPY[format],[askedHint,setAskedHint]=useState(false);
  useEffect(()=>{if(phase==='intro'||attempts.used===0&&phase==='watch')setAskedHint(false);},[phase,attempts.used]);
  const hint=attempts.hint||askedHint,tries=`ATTEMPT ${Math.min(LESSON_ATTEMPTS,attempts.used+1)} OF ${LESSON_ATTEMPTS}`;
  const missed=phase==='practice'&&(attempts.result==='miss'||attempts.result==='spent');
  return <section className={'coach-lesson phase-'+phase} aria-label="Find a passing lane lesson">
    <div className="lesson-strip"><span>PALM COAST / FIRST TOUCH CLUB</span><button onClick={onExit} aria-label="Leave lesson">EXIT <Icon name="close"/></button></div>
    <div className="lesson-heading"><p>01 / OFF THE BALL</p><h1>MAKE YOURSELF<br/><em>AN OPTION.</em></h1><div className="lesson-steps"><span className={phase==='intro'||phase==='watch'?'current':''}>01 WATCH</span><span className={phase==='practice'||phase==='aim'||phase==='passing'||phase==='replay'?'current':''}>02 PLAY</span><span className={phase==='complete'?'current':''}>03 UNDERSTAND</span></div></div>
    <div className="lesson-coach-card" aria-live="polite"><div className="coach-identity"><span className="coach-portrait">R</span><div>COACH RAFA<small>FIRST TOUCH CLUB</small></div><span className="coach-status"><Icon name={phase==='complete'?'check':phase==='watch'||phase==='replay'?'play':'ball'}/></span></div>
    {phase==='intro'?<><h2>The ball can’t reach you through a defender.</h2><p>Don’t run toward the ball. Move sideways until your teammate has a clear passing lane. Then call for it and draw the pass yourself.</p><div className="lesson-key"><span className="you-dot"/> YOU <span className="friend-dot"/> TEAMMATE <span className="opponent-dot"/> DEFENDER</div><Formats format={format} onFormat={onFormat}/><button className="pixel-button" onClick={onWatch}>SHOW ME THE MOVEMENT <Icon name="arrow"/></button><button className="lesson-secondary" onClick={onPractice}>I want to try it myself</button></>
    :phase==='watch'?<><span className="lesson-caption">WATCH THE GOLD SHIRT</span><h2>A few steps change everything.</h2><p>Your teammate stays put. You move across the defender’s line. The passing lane opens.</p><button className="pixel-button" onClick={onPractice}>MY TURN <Icon name="arrow"/></button></>
    :missed?<><span className="lane-status">{attempts.result==='spent'?`ALL ${LESSON_ATTEMPTS} ATTEMPTS USED`:`${attemptsLeft(attempts)} ${attemptsLeft(attempts)===1?'ATTEMPT':'ATTEMPTS'} LEFT`}</span><h2>{attempts.result==='spent'?'Let’s watch how it’s done.':attemptMessage(attempts)}</h2>{hint&&<p className="lesson-hint"><strong>HINT </strong>{copy.hint}</p>}{attempts.result==='spent'?<button className="pixel-button" onClick={onWatch}>SHOW ME THE MOVEMENT <Icon name="arrow"/></button>:<button className="pixel-button" onClick={onPass}>CALL FOR THE PASS <span>SPACE <Icon name="external"/></span></button>}<button className="lesson-secondary" onClick={onReplay}>Watch again in slow motion</button></>
    :phase==='practice'?<><span className={'lane-status '+(open?'is-open':'')}><Icon name="dot" size={12}/>{open?'PASSING LANE OPEN':'DEFENDER BLOCKING THE LANE'}</span><h2>{open?'You’ve given them an option.':'Find an angle. Not just space.'}</h2><p>{feedback||'Move sideways with WASD or the joystick. When you can receive, call for the pass.'}</p><button className="pixel-button" onClick={onPass}>CALL FOR THE PASS <span>SPACE <Icon name="external"/></span></button><button className="lesson-secondary" onClick={onWatch}>Watch the example again</button></>
    :phase==='aim'?<><span className="lesson-caption">{tries} · PLAY IS FROZEN</span><h2>{copy.brief}</h2><span className={'lane-status '+(aimStatus==='clear'?'is-open':'')} role="status">{aimStatus!=='none'&&<Icon name="dot" size={12}/>}{aimStatus==='threat'?copy.threat:aimStatus==='clear'?copy.clear:aimStatus==='nobody'?copy.rest:feedback||'Your teammate is waving: they are ready for it.'}</span>{hint?<p className="lesson-hint"><strong>HINT </strong>{copy.hint}</p>:<button className="lesson-secondary" onClick={()=>setAskedHint(true)}>Give me a hint</button>}<Formats format={format} onFormat={onFormat}/><button className="pixel-button" disabled={aimStatus==='none'} onClick={onPlay}>PLAY THIS PASS <span>SPACE <Icon name="external"/></span></button><button className="lesson-secondary" onClick={onStraight}>Aim straight at me</button><button className="lesson-secondary" onClick={onCancel}>Move again first</button></>
    :phase==='passing'?<><h2>Here comes the ball.</h2><p>Watch the line. Does the defender reach it in time?</p></>
    :phase==='replay'?<><span className="lesson-caption">{`SLOW MOTION · ${REPLAY_SPEED}×`}</span><h2>{attempts.last?.prediction.end==='receive'?'Watch the lane stay open.':'Watch the defender close the lane.'}</h2><p>{attempts.last?.prediction.end==='receive'?'The line stayed outside the defender’s reach, so the ball got there first.':'The red ring marks the defender who could reach the line before the ball.'}</p></>
    :<><span className="lesson-caption">CONCEPT COMPLETED / FINDING AN ANGLE</span><h2>You made the pass possible.</h2><p>{copy.success} <strong>Being open means your teammate can reach you.</strong></p><div className="lesson-takeaway">NEXT TIME YOU PLAY<br/><b>Before asking for the ball, check the line between you and your teammate.</b></div><button className="pixel-button" onClick={onPractice}>TRY IT ON THE OTHER SIDE <Icon name="external"/></button><button className="lesson-secondary" onClick={onReplay}>Watch it again in slow motion</button><button className="lesson-secondary" onClick={onExit}>Back to the neighborhood</button></>}
    </div>
  </section>;
}
