'use client';
import {Icon} from './Icon';
import { LessonPhase } from '@/lib/town/learning';
type Props={phase:LessonPhase;open:boolean;feedback:string;onWatch:()=>void;onPractice:()=>void;onPass:()=>void;onExit:()=>void};
export default function CoachLesson({phase,open,feedback,onWatch,onPractice,onPass,onExit}:Props){
  return <section className={'coach-lesson phase-'+phase} aria-label="Find a passing lane lesson">
    <div className="lesson-strip"><span>PALM COAST / FIRST TOUCH CLUB</span><button onClick={onExit} aria-label="Leave lesson">EXIT <Icon name="close"/></button></div>
    <div className="lesson-heading"><p>01 / OFF THE BALL</p><h1>MAKE YOURSELF<br/><em>AN OPTION.</em></h1><div className="lesson-steps"><span className={phase==='intro'||phase==='watch'?'current':''}>01 WATCH</span><span className={phase==='practice'||phase==='passing'?'current':''}>02 PLAY</span><span className={phase==='complete'?'current':''}>03 UNDERSTAND</span></div></div>
    <div className="lesson-coach-card" aria-live="polite"><div className="coach-identity"><span className="coach-portrait">R</span><div>COACH RAFA<small>FIRST TOUCH CLUB</small></div><span className="coach-status"><Icon name={phase==='complete'?'check':phase==='watch'?'play':'ball'}/></span></div>
    {phase==='intro'?<><h2>The ball can’t reach you through a defender.</h2><p>Don’t run toward the ball. Move sideways until your teammate has a clear passing lane.</p><div className="lesson-key"><span className="you-dot"/> YOU <span className="friend-dot"/> TEAMMATE <span className="opponent-dot"/> DEFENDER</div><button className="pixel-button" onClick={onWatch}>SHOW ME THE MOVEMENT <Icon name="arrow"/></button><button className="lesson-secondary" onClick={onPractice}>I want to try it myself</button></>:phase==='watch'?<><span className="lesson-caption">WATCH THE GOLD SHIRT</span><h2>A few steps change everything.</h2><p>Your teammate stays put. You move across the defender’s line. The passing lane opens.</p><button className="pixel-button" onClick={onPractice}>MY TURN <Icon name="arrow"/></button></>:phase==='practice'?<><span className={'lane-status '+(open?'is-open':'')}><Icon name="dot" size={12}/>{open?'PASSING LANE OPEN':'DEFENDER BLOCKING THE LANE'}</span><h2>{open?'You’ve given them an option.':'Find an angle. Not just space.'}</h2><p>{feedback||'Move sideways with WASD or the joystick. When you can receive, call for the pass.'}</p><button className="pixel-button" onClick={onPass}>CALL FOR THE PASS <span>SPACE <Icon name="external"/></span></button><button className="lesson-secondary" onClick={onWatch}>Watch the example again</button></>:phase==='passing'?<><h2>Here comes the ball.</h2><p>Watch the green line. Your movement took the defender out of the passing lane.</p></>:<><span className="lesson-caption">CONCEPT COMPLETED / FINDING AN ANGLE</span><h2>You made the pass possible.</h2><p>The defender was between you and the ball. Moving sideways opened a route around them. <strong>Being open means your teammate can reach you.</strong></p><div className="lesson-takeaway">NEXT TIME YOU PLAY<br/><b>Before asking for the ball, check the line between you and your teammate.</b></div><button className="pixel-button" onClick={onPractice}>TRY IT ON THE OTHER SIDE <Icon name="external"/></button><button className="lesson-secondary" onClick={onExit}>Back to the neighborhood</button></>}
    </div>
  </section>;
}
