'use client';
import {readArcadeRecord,saveArcadeRecord} from '@/lib/arcade/arcadeRecords';
import {arcadeFeedback} from '@/lib/arcade/arcadeFeedback';
import {createStrikerMatch,strikerInput,STRIKER_SECONDS,STRIKER_ROUNDS} from '@/lib/arcade/strikerMatch';
import {createStrikerScene} from '@/lib/arcade/strikerScene';
import {paintJoystick} from '@/lib/town/joystickFeedback';
import {frameCapSlot} from '@/lib/town/frameCap';
import {isSoundEnabled,getSoundVolume} from '@/lib/games/sound';
import {Icon} from './Icon';
import {BackButton} from './BackButton';
import {useArcadeEntry} from '@/lib/arcade/useArcadeEntry';
import {creditRun,arcadeCoinTarget} from '@/lib/arcade/arcadeWallet';
import {recordExploreActivity} from '@/lib/town/exploreActivity';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {neutralLiveInput} from '@/lib/arcade/liveMatchInput';
import styles from './LiveArcadeMatch.module.css';

export default function LiveArcadeMatch({onExit}:{onExit:()=>void}){
 const host=useRef<HTMLDivElement>(null),local=useRef(neutralLiveInput()),keys=useRef(new Set<string>()),phaseRef=useRef<'ready'|'playing'|'paused'|'finished'>('ready');
 const [phase,setPhase]=useState<typeof phaseRef.current>('ready'),[view,setView]=useState({gold:0,blue:0,seconds:0,message:'Pass, move, receive.',charge:0,stamina:1,passes:0,shots:0,level:1}),[failed,setFailed]=useState(false);
 const [rotate,setRotate]=useState(false),[portrait,setPortrait]=useState(false),joy=useRef<HTMLDivElement>(null),joyId=useRef<number|null>(null),joyRect=useRef<DOMRect|null>(null),stickPaint=useRef<{x:number;y:number}|null>(null),restart=useRef(()=>{});
 const [unlocked,setUnlocked]=useState(1),chooseRound=useRef((level:number)=>{});
 const entry=useArcadeEntry('live');
 const coinRun=useRef(''),coinTarget=useRef(0),coinActiveSeconds=useRef(0);
 const shootId=useRef<number|null>(null),sprintId=useRef<number|null>(null);
 const wake=useRef(()=>{}),charging=useRef(false),chargePower=useRef(0),audio=useRef<AudioContext|null>(null);
 const unlock=()=>{if(!isSoundEnabled())return;try{audio.current??=new AudioContext();void audio.current.resume();}catch{}};
 const startCharge=(id=-1)=>{if(shootId.current!==null)return;shootId.current=id;chargePower.current=0;charging.current=true;unlock();};
 const cancelCharge=()=>{shootId.current=null;charging.current=false;chargePower.current=0;};
 const fire=()=>{if(!charging.current)return;shootId.current=null;charging.current=false;local.current.power=chargePower.current;local.current.shoot=true;};
 const release=()=>{cancelCharge();sprintId.current=null;keys.current.clear();local.current=neutralLiveInput();stickPaint.current=null;joyRect.current=null;paintJoystick(joy.current,0,0);joyId.current=null;};
 const changePhase=async(next:typeof phase)=>{if(next==='playing'&&(phaseRef.current==='ready'||phaseRef.current==='finished')){const id=await entry.enter();if(!id)return;if(phaseRef.current==='finished')restart.current();coinRun.current=id;coinTarget.current=0;coinActiveSeconds.current=0;}release();phaseRef.current=next;setPhase(next);if(next==='playing'){unlock();recordExploreActivity('arcade');host.current?.focus({preventScroll:true});}wake.current();};
 useEffect(()=>{const check=()=>{const blocked=window.matchMedia('(pointer:coarse)').matches&&window.innerHeight>window.innerWidth;setRotate(blocked);if(blocked&&phaseRef.current==='playing'){release();phaseRef.current='paused';setPhase('paused');wake.current();}};check();window.addEventListener('resize',check);window.addEventListener('orientationchange',check);return()=>{window.removeEventListener('resize',check);window.removeEventListener('orientationchange',check);};},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{
  const node=host.current;if(!node)return;const canvas=document.createElement('canvas');node.appendChild(canvas);const match=createStrikerMatch();const saved=readArcadeRecord('live');setUnlocked(Math.min(4,saved.unlocked));match.state.level=Math.min(4,saved.unlocked);chooseRound.current=(level)=>{match.state.level=level;match.reset();setView(v=>({...v,level}));};setView(v=>({...v,level:match.state.level}));let visual:ReturnType<typeof createStrikerScene>;
  try{visual=createStrikerScene(canvas,match);}catch{canvas.remove();setFailed(true);return;}
  let frame=0,last=0,slot=0,lastHud=0,disposed=false,lastEvent=0,chargeTone=0;const input=strikerInput(),interval=1000/(visual.stage.mobile?30:60);
  const cue=(event:string)=>arcadeFeedback(audio.current,event);
  const fit=()=>{visual.fit();setPortrait(visual.portrait);wake.current();};setPortrait(visual.portrait);const resize=new ResizeObserver(fit);resize.observe(node);
  restart.current=()=>{match.reset(true);visual.stage.resetPlayers();setView({gold:0,blue:0,seconds:0,message:'Pass, move, receive.',charge:0,stamina:1,passes:0,shots:0,level:match.state.level});visual.update(0);};
  const blur=()=>{release();if(phaseRef.current==='playing'){phaseRef.current='paused';setPhase('paused');}if(frame)cancelAnimationFrame(frame);frame=0;last=0;slot=0;};
  const hidden=()=>{if(document.hidden)blur();else wake.current();};
  const down=(event:KeyboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.closest('input,textarea,select,a,button'))return;if(event.code==='Escape'){event.preventDefault();blur();return;}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space','KeyJ','KeyK','KeyL','KeyQ','ShiftLeft','ShiftRight'].includes(event.code))return;event.preventDefault();if(phaseRef.current!=='playing')return;keys.current.add(event.code);unlock();if(!event.repeat){if(event.code==='Space'||event.code==='KeyJ')local.current.pass=true;if(event.code==='KeyK')startCharge();if(event.code==='KeyL')local.current.through=true;if(event.code==='KeyQ')local.current.switchPlayer=true;}};
  const up=(event:KeyboardEvent)=>{keys.current.delete(event.code);if(event.code==='KeyK'&&shootId.current===-1)fire();};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);
  const animate=(now:number)=>{frame=0;if(disposed||document.hidden)return;const nextSlot=frameCapSlot(now,slot,interval);if(nextSlot<0){frame=requestAnimationFrame(animate);return;}slot=nextSlot;const dt=last?Math.min(.05,(now-last)/1000):1/60;last=now;const active=phaseRef.current==='playing',k=keys.current,l=local.current;
   if(active){const keyboardX=Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),keyboardZ=Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW'));
    const axes=visual.screenAxes(keyboardX||l.mx,keyboardZ||-l.my);input.x=axes.x;input.z=axes.z;
    input.pass=l.pass;input.shoot=l.shoot;input.through=l.through;input.switchPlayer=l.switchPlayer;input.sprint=l.sprint||k.has('ShiftLeft')||k.has('ShiftRight');input.charge=charging.current;input.power=l.power;
    if(Math.hypot(input.x,input.z)>.1||input.pass||input.shoot||input.through||input.charge)coinActiveSeconds.current+=dt;
    match.step(dt,input);const tone=Math.floor(match.state.charge*3);if(tone>chargeTone)cue('charge'+tone);chargeTone=tone;chargePower.current=match.state.charge;l.shoot=l.pass=l.through=l.switchPlayer=false;
    if(match.state.event!==lastEvent){lastEvent=match.state.event;if(['shot','goal','hit','save','post','pass','touch'].includes(match.state.eventKind))cue(match.state.eventKind);}
   }
   visual.update(active?dt:0);visual.stage.render();if(stickPaint.current){paintJoystick(joy.current,stickPaint.current.x,stickPaint.current.y);stickPaint.current=null;}canvas.dataset.frames=String(Number(canvas.dataset.frames??0)+1);
   const s=match.state;if(active&&coinRun.current){const coins=arcadeCoinTarget('live',{goals:s.score[0],passes:s.passes[0],finished:s.finished,won:s.score[0]>s.score[1],engaged:coinActiveSeconds.current>=Math.min(15,s.time*.15)});if(coins>coinTarget.current){coinTarget.current=coins;void creditRun(coinRun.current,'live',coins,'Team passing, goals and full time');}}if(s.finished&&active){const saved=saveArcadeRecord('live',s.score[0],Math.min(4,s.level+(s.score[0]>s.score[1]?1:0)));setUnlocked(saved.unlocked);phaseRef.current='finished';setPhase('finished');release();}
   if(now-lastHud>100||s.finished){setView({gold:s.score[0],blue:s.score[1],seconds:s.time,message:s.message,charge:s.charge,stamina:s.players[s.selected].stamina,passes:s.passes[0],shots:s.shots[0],level:s.level});lastHud=now;}
   if(phaseRef.current==='playing')frame=requestAnimationFrame(animate);else{last=0;slot=0;}
  };wake.current=()=>{if(!disposed&&!document.hidden&&!frame)frame=requestAnimationFrame(animate);};wake.current();
  (window as unknown as {__fi2Live?:unknown}).__fi2Live={match,sim:match.state,scene:visual.stage.scene,camera:visual.stage.camera,renderer:visual.stage.renderer,local,phaseRef,charging,visual,getElapsed:()=>match.state.time};
  return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);release();wake.current=()=>{};visual.stage.dispose();canvas.remove();void audio.current?.close();audio.current=null;delete (window as unknown as {__fi2Live?:unknown}).__fi2Live;};
 // Refs preserve controller and match state without recreating the renderer.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 // Heat pass 4 (audit F13): the rect is read once per gesture and the thumb paints on the next game frame, not on every move event.
 const moveStick=(event:PointerEvent<HTMLDivElement>)=>{if(event.pointerId!==joyId.current||!joy.current)return;const r=joyRect.current??(joyRect.current=joy.current.getBoundingClientRect()),x=(event.clientX-r.x-r.width/2)/40,y=(event.clientY-r.y-r.height/2)/40,d=Math.max(1,Math.hypot(x,y));local.current.mx=x/d;local.current.my=-y/d;stickPaint.current={x:x/d*36,y:y/d*36};};
 const releaseStick=(event?:{pointerId:number})=>{if(event&&event.pointerId!==joyId.current)return;joyId.current=null;joyRect.current=null;stickPaint.current=null;local.current.mx=local.current.my=0;paintJoystick(joy.current,0,0);};
 const remaining=Math.max(0,STRIKER_SECONDS-Math.floor(view.seconds)),clock=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;
 return <section className={styles.root} data-fullscreen-game data-rotate={rotate||undefined} aria-label="Island Strikers arcade match">
  <header className={styles.header}><BackButton label="Arcade" onBack={()=>{release();onExit();}}/><div className={styles.score}><span>GOLD <b>{view.gold}</b></span><time>{clock}</time><span><b>{view.blue}</b> BLUE</span></div><button className={styles.pause} aria-label={phase==='paused'?'Resume':'Pause'} data-tip={phase==='paused'?'Resume':'Pause'} disabled={rotate||phase==='ready'||phase==='finished'||failed} onClick={()=>changePhase(phase==='playing'?'paused':'playing')}><Icon name={phase==='paused'?'play':'pause'} size={22}/></button></header>
  <div className={styles.body}><div className={styles.direction}>{portrait?'GOLD ATTACKS ↑':'GOLD ATTACKS →'}<span>Tap Pass before receiving for a one-two.</span></div><div className={styles.stage} ref={host} tabIndex={-1} onPointerDown={()=>host.current?.focus({preventScroll:true})}/>
   {rotate&&<div className={styles.rotate} role="status"><div><svg className={styles.rotatePhone} viewBox="0 0 80 80" aria-hidden="true"><rect x="24" y="10" width="32" height="60" rx="6" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M35 17h10M36 62h8" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg><h2>Turn sideways to play</h2><p>A wider pitch makes passes easier to see and puts both thumbs on the controls.</p><small>Rotate your phone to landscape.</small></div></div>}
   {!rotate&&phase!=='playing'&&<div className={styles.overlay}><div className={styles.card}><small>ROUND {view.level} · {STRIKER_ROUNDS[view.level-1]}</small><h2>{failed?'The pitch could not load':phase==='ready'?'Fast feet. Big finishes.':phase==='paused'?'Match paused.':'Full time.'}</h2><p>{failed?'Return to the Arcade and try again.':phase==='ready'?['Pass and move to draw a defender out. Tap Pass before receiving for a one-two. Hold and release Shoot for power.','They press your receiver. Use a one-two or through ball before the second defender arrives.','They protect the middle. Switch to the wide player, then attack the gap.','Pressure and cover together. Move the ball early, change sides, and time your finish.'][view.level-1]:phase==='paused'?'Your score and match time are held.':`Gold ${view.gold} – ${view.blue} Blue · ${view.passes} completed passes · ${view.shots} shots · ${view.gold>view.blue?(view.level<4?'Round cleared. The next team presses smarter.':'Neon Final won! Defend your title.'):'Find the free player and try this round again.'}`}</p>{!failed&&phase==='ready'&&<label>Round <select aria-label="Choose Strikers round" value={view.level} onChange={e=>chooseRound.current(Number(e.target.value))}>{STRIKER_ROUNDS.map((name,i)=><option key={name} value={i+1} disabled={i+1>unlocked}>{i+1}. {name}{i+1>unlocked?' · win to unlock':''}</option>)}</select></label>}{entry.message&&<p role="status">{entry.message}</p>}{!failed&&phase!=='paused'&&<p>3 coins per match</p>}{!failed&&<button className={styles.primary} disabled={entry.pending} onClick={()=>{unlock();void changePhase('playing');}}>{phase==='ready'?'Kick off':phase==='paused'?'Resume match':view.gold>view.blue&&view.level<4?'Next round':'Play again'}</button>}<p className={styles.instructions}>WASD / arrows move · Space or J pass / tackle · Hold K, release to shoot · L through ball · Q switch · Shift sprint</p></div></div>}
  </div>
  <footer className={styles.footer}><p>{view.message}</p><div className={styles.meters}><label>Sprint <meter min="0" max="1" value={view.stamina}/></label><label>Shot power <meter min="0" max="1" value={view.charge}/></label></div><div className={styles.touchControls} aria-label="Touch match controls"><div className={`touch-controls ${styles.movement}`}><div ref={joy} className="joystick" role="group" aria-label="Move player" onPointerDown={event=>{if(phase!=='playing'||joyId.current!==null)return;event.preventDefault();joyId.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);moveStick(event);}} onPointerMove={moveStick} onPointerUp={releaseStick} onPointerCancel={releaseStick} onLostPointerCapture={releaseStick}><i className="joystick-contact" aria-hidden="true"><i className="joystick-contact-arc"/></i><span/></div></div><div className={styles.actions}>{(['pass','through','switchPlayer'] as const).map(action=><button key={action} data-action={action} disabled={rotate||phase!=='playing'} onClick={event=>{if(event.detail===0)local.current[action]=true;}} onPointerDown={event=>{event.preventDefault();local.current[action]=true;}}>{({pass:'Pass / tackle',through:'Through',switchPlayer:'Switch'})[action]}</button>)}<button data-action="shoot" disabled={rotate||phase!=='playing'} onKeyDown={event=>{if((event.code==='Space'||event.code==='Enter')&&!event.repeat){event.preventDefault();startCharge();}}} onKeyUp={event=>{if(event.code==='Space'||event.code==='Enter'){event.preventDefault();if(shootId.current===-1)fire();}}} onBlur={()=>{if(shootId.current===-1)cancelCharge();}} onPointerDown={event=>{if(shootId.current!==null)return;event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);startCharge(event.pointerId);}} onPointerUp={event=>{if(shootId.current===event.pointerId)fire();}} onPointerCancel={event=>{if(shootId.current===event.pointerId)cancelCharge();}} onLostPointerCapture={event=>{if(shootId.current===event.pointerId)cancelCharge();}}>Hold / Shoot</button><button data-action="sprint" disabled={rotate||phase!=='playing'} onPointerDown={event=>{if(sprintId.current!==null)return;event.preventDefault();sprintId.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);local.current.sprint=true;}} onPointerUp={event=>{if(sprintId.current===event.pointerId){sprintId.current=null;local.current.sprint=false;}}} onPointerCancel={event=>{if(sprintId.current===event.pointerId){sprintId.current=null;local.current.sprint=false;}}} onLostPointerCapture={event=>{if(sprintId.current===event.pointerId){sprintId.current=null;local.current.sprint=false;}}}>Sprint</button></div></div></footer>
 </section>;
}
