'use client';
import {createStrikerMatch,strikerInput,STRIKER_SECONDS} from '@/lib/arcade/strikerMatch';
import {createStrikerScene} from '@/lib/arcade/strikerScene';
import {frameCapSlot} from '@/lib/town/frameCap';
import {isSoundEnabled,getSoundVolume} from '@/lib/games/sound';
import {Icon} from './Icon';
import {BackButton} from './BackButton';
import {beginArcadeRun,creditRun,arcadeCoinTarget} from '@/lib/arcade/arcadeWallet';
import {recordExploreActivity} from '@/lib/town/exploreActivity';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {neutralLiveInput} from '@/lib/arcade/liveMatchInput';
import styles from './LiveArcadeMatch.module.css';

export default function LiveArcadeMatch({onExit}:{onExit:()=>void}){
 const host=useRef<HTMLDivElement>(null),local=useRef(neutralLiveInput()),keys=useRef(new Set<string>()),phaseRef=useRef<'ready'|'playing'|'paused'|'finished'>('ready');
 const [phase,setPhase]=useState<typeof phaseRef.current>('ready'),[view,setView]=useState({gold:0,blue:0,seconds:0,message:'Pass, move, receive.',charge:0,stamina:1,passes:0,shots:0}),[failed,setFailed]=useState(false);
 const [rotate,setRotate]=useState(false),[portrait,setPortrait]=useState(false),joy=useRef<HTMLDivElement>(null),joyId=useRef<number|null>(null),joyRect=useRef<DOMRect|null>(null),stickPaint=useRef<string|null>(null),restart=useRef(()=>{});
 const coinRun=useRef(''),coinTarget=useRef(0),coinActiveSeconds=useRef(0);
 const wake=useRef(()=>{}),charging=useRef(false),chargePower=useRef(0),audio=useRef<AudioContext|null>(null);
 const unlock=()=>{if(!isSoundEnabled())return;try{audio.current??=new AudioContext();void audio.current.resume();}catch{}};
 const fire=()=>{if(!charging.current)return;charging.current=false;local.current.power=chargePower.current;local.current.shoot=true;};
 const release=()=>{charging.current=false;chargePower.current=0;keys.current.clear();local.current=neutralLiveInput();stickPaint.current=null;joyRect.current=null;joy.current?.style.setProperty('--stick','translate(0,0)');joyId.current=null;};
 const changePhase=(next:typeof phase)=>{if(next==='playing'&&(phaseRef.current==='ready'||phaseRef.current==='finished')){coinRun.current=beginArcadeRun('live');coinTarget.current=0;coinActiveSeconds.current=0;}release();phaseRef.current=next;setPhase(next);if(next==='playing'){unlock();recordExploreActivity('arcade');host.current?.focus({preventScroll:true});}wake.current();};
 useEffect(()=>{const check=()=>{const blocked=window.matchMedia('(pointer:coarse)').matches&&window.innerHeight>window.innerWidth;setRotate(blocked);if(blocked&&phaseRef.current==='playing'){release();phaseRef.current='paused';setPhase('paused');wake.current();}};check();window.addEventListener('resize',check);window.addEventListener('orientationchange',check);return()=>{window.removeEventListener('resize',check);window.removeEventListener('orientationchange',check);};},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{
  const node=host.current;if(!node)return;const canvas=document.createElement('canvas');node.appendChild(canvas);const match=createStrikerMatch();let visual:ReturnType<typeof createStrikerScene>;
  try{visual=createStrikerScene(canvas,match);}catch{canvas.remove();setFailed(true);return;}
  let frame=0,last=0,slot=0,lastHud=0,disposed=false,lastEvent=0;const input=strikerInput(),interval=1000/(visual.stage.mobile?30:60);
  const cue=(goal:boolean)=>{const ctx=audio.current;if(!ctx||ctx.state!=='running'||!isSoundEnabled())return;const o=ctx.createOscillator(),g=ctx.createGain(),now=ctx.currentTime;o.type='sine';o.frequency.setValueAtTime(goal?520:180,now);o.frequency.exponentialRampToValueAtTime(goal?880:70,now+.15);g.gain.setValueAtTime(Math.max(.0001,getSoundVolume()*.075),now);g.gain.exponentialRampToValueAtTime(.0001,now+.22);o.connect(g);g.connect(ctx.destination);o.start();o.stop(now+.23);o.onended=()=>{o.disconnect();g.disconnect();};};
  const fit=()=>{visual.fit();setPortrait(visual.portrait);wake.current();};setPortrait(visual.portrait);const resize=new ResizeObserver(fit);resize.observe(node);
  restart.current=()=>{match.reset();visual.stage.resetPlayers();setView({gold:0,blue:0,seconds:0,message:'Pass, move, receive.',charge:0,stamina:1,passes:0,shots:0});visual.update(0);};
  const blur=()=>{release();if(phaseRef.current==='playing'){phaseRef.current='paused';setPhase('paused');}if(frame)cancelAnimationFrame(frame);frame=0;last=0;slot=0;};
  const hidden=()=>{if(document.hidden)blur();else wake.current();};
  const down=(event:KeyboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.closest('input,textarea,select,a,button'))return;if(event.code==='Escape'){event.preventDefault();blur();return;}if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space','KeyJ','KeyK','KeyL','KeyQ','ShiftLeft','ShiftRight'].includes(event.code))return;event.preventDefault();if(phaseRef.current!=='playing')return;keys.current.add(event.code);unlock();if(!event.repeat){if(event.code==='Space'||event.code==='KeyJ')local.current.pass=true;if(event.code==='KeyK')charging.current=true;if(event.code==='KeyL')local.current.through=true;if(event.code==='KeyQ')local.current.switchPlayer=true;}};
  const up=(event:KeyboardEvent)=>{keys.current.delete(event.code);if(event.code==='KeyK')fire();};
  window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',hidden);
  const animate=(now:number)=>{frame=0;if(disposed||document.hidden)return;const nextSlot=frameCapSlot(now,slot,interval);if(nextSlot<0){frame=requestAnimationFrame(animate);return;}slot=nextSlot;const dt=last?Math.min(.05,(now-last)/1000):1/60;last=now;const active=phaseRef.current==='playing',k=keys.current,l=local.current;
   if(active){const keyboardX=Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),keyboardZ=Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW'));
    const axes=visual.screenAxes(keyboardX||l.mx,keyboardZ||-l.my);input.x=axes.x;input.z=axes.z;
    input.pass=l.pass;input.shoot=l.shoot;input.through=l.through;input.switchPlayer=l.switchPlayer;input.sprint=l.sprint||k.has('ShiftLeft')||k.has('ShiftRight');input.charge=charging.current;input.power=l.power;
    if(Math.hypot(input.x,input.z)>.1||input.pass||input.shoot||input.through||input.charge)coinActiveSeconds.current+=dt;
    match.step(dt,input);chargePower.current=match.state.charge;l.shoot=l.pass=l.through=l.switchPlayer=false;
    if(match.state.event!==lastEvent){lastEvent=match.state.event;if(['shot','goal','hit','save','post','pass'].includes(match.state.eventKind))cue(match.state.eventKind==='goal');}
   }
   visual.update(active?dt:0);visual.stage.render();if(stickPaint.current){joy.current?.style.setProperty('--stick',stickPaint.current);stickPaint.current=null;}canvas.dataset.frames=String(Number(canvas.dataset.frames??0)+1);
   const s=match.state;if(active&&coinRun.current){const coins=arcadeCoinTarget('live',{goals:s.score[0],passes:s.passes[0],finished:s.finished,won:s.score[0]>s.score[1],engaged:coinActiveSeconds.current>=Math.min(15,s.time*.15)});if(coins>coinTarget.current){coinTarget.current=coins;void creditRun(coinRun.current,'live',coins,'Team passing, goals and full time');}}if(s.finished&&active){phaseRef.current='finished';setPhase('finished');release();}
   if(now-lastHud>100||s.finished){setView({gold:s.score[0],blue:s.score[1],seconds:s.time,message:s.message,charge:s.charge,stamina:s.players[s.selected].stamina,passes:s.passes[0],shots:s.shots[0]});lastHud=now;}
   if(phaseRef.current==='playing')frame=requestAnimationFrame(animate);else{last=0;slot=0;}
  };wake.current=()=>{if(!disposed&&!document.hidden&&!frame)frame=requestAnimationFrame(animate);};wake.current();
  (window as unknown as {__fi2Live?:unknown}).__fi2Live={match,sim:match.state,scene:visual.stage.scene,camera:visual.stage.camera,renderer:visual.stage.renderer,local,phaseRef,charging,visual,getElapsed:()=>match.state.time};
  return()=>{disposed=true;cancelAnimationFrame(frame);resize.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',hidden);release();wake.current=()=>{};visual.stage.dispose();canvas.remove();void audio.current?.close();audio.current=null;delete (window as unknown as {__fi2Live?:unknown}).__fi2Live;};
 // Refs preserve controller and match state without recreating the renderer.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[]);
 // Heat pass 4 (audit F13): the rect is read once per gesture and the thumb paints on the next game frame, not on every move event.
 const moveStick=(event:PointerEvent<HTMLDivElement>)=>{if(event.pointerId!==joyId.current||!joy.current)return;const r=joyRect.current??(joyRect.current=joy.current.getBoundingClientRect()),x=(event.clientX-r.x-r.width/2)/40,y=(event.clientY-r.y-r.height/2)/40,d=Math.max(1,Math.hypot(x,y));local.current.mx=x/d;local.current.my=-y/d;stickPaint.current=`translate(${x/d*28}px,${y/d*28}px)`;};
 const releaseStick=()=>{joyId.current=null;joyRect.current=null;stickPaint.current=null;local.current.mx=local.current.my=0;joy.current?.style.setProperty('--stick','translate(0,0)');};
 const remaining=Math.max(0,STRIKER_SECONDS-Math.floor(view.seconds)),clock=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;
 return <section className={styles.root} data-fullscreen-game aria-label="Island Strikers arcade match">
  <header className={styles.header}><BackButton onBack={()=>{release();onExit();}}/><div className={styles.score}><span>GOLD <b>{view.gold}</b></span><time>{clock}</time><span><b>{view.blue}</b> BLUE</span></div><button className={styles.pause} aria-label={phase==='paused'?'Resume':'Pause'} data-tip={phase==='paused'?'Resume':'Pause'} disabled={rotate||phase==='ready'||phase==='finished'||failed} onClick={()=>changePhase(phase==='playing'?'paused':'playing')}><Icon name={phase==='paused'?'play':'pause'} size={22}/></button></header>
  <div className={styles.body}><div className={styles.direction}>{portrait?'GOLD ATTACKS ↑':'GOLD ATTACKS →'}<span>Pass into space. Move again.</span></div><div className={styles.stage} ref={host} tabIndex={-1} onPointerDown={()=>host.current?.focus({preventScroll:true})}/>
   {rotate&&<div className={styles.rotate} role="status"><div><svg className={styles.rotatePhone} viewBox="0 0 80 80" aria-hidden="true"><rect x="24" y="10" width="32" height="60" rx="6" fill="none" stroke="currentColor" strokeWidth="3"/><path d="M35 17h10M36 62h8" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg><h2>Turn sideways to play</h2><p>A wider pitch makes passes easier to see and puts both thumbs on the controls.</p><small>Rotate your phone to landscape.</small></div></div>}
   {!rotate&&phase!=='playing'&&<div className={styles.overlay}><div className={styles.card}><small>ISLAND STRIKERS · 4 A SIDE</small><h2>{failed?'The pitch could not load':phase==='ready'?'Fast feet. Big finishes.':phase==='paused'?'Match paused.':'Full time.'}</h2><p>{failed?'Return to the Arcade and try again.':phase==='ready'?'Three minutes of fast arcade football. Follow the receiver ring to build a passing move. Sprint into space, then hold and release your shot.':phase==='paused'?'Your score and match time are held.':`Gold ${view.gold} – ${view.blue} Blue · ${view.passes} completed passes · ${view.shots} shots`}</p>{!failed&&<button className={styles.primary} onClick={()=>{if(phase==='finished')restart.current();changePhase('playing');}}>{phase==='ready'?'Kick off':phase==='paused'?'Resume match':'Play again'}</button>}<p className={styles.instructions}>WASD / arrows move · Space or J pass / tackle · Hold K, release to shoot · L through ball · Q switch · Shift sprint</p></div></div>}
  </div>
  <footer className={styles.footer}><p>{view.message}</p><div className={styles.meters}><label>Sprint <meter min="0" max="1" value={view.stamina}/></label><label>Shot power <meter min="0" max="1" value={view.charge}/></label></div><div className={styles.touchControls} aria-label="Touch match controls"><div ref={joy} className={styles.joystick} role="group" aria-label="Move player" onPointerDown={event=>{if(phase!=='playing'||joyId.current!==null)return;event.preventDefault();joyId.current=event.pointerId;event.currentTarget.setPointerCapture(event.pointerId);moveStick(event);}} onPointerMove={moveStick} onPointerUp={releaseStick} onPointerCancel={releaseStick} onLostPointerCapture={releaseStick}><span/></div><div className={styles.actions}>{(['pass','through','switchPlayer'] as const).map(action=><button key={action} data-action={action} disabled={rotate||phase!=='playing'} onClick={event=>{if(event.detail===0)local.current[action]=true;}} onPointerDown={event=>{event.preventDefault();local.current[action]=true;}}>{({pass:'Pass / tackle',through:'Through',switchPlayer:'Switch'})[action]}</button>)}<button data-action="shoot" disabled={rotate||phase!=='playing'} onKeyDown={event=>{if((event.code==='Space'||event.code==='Enter')&&!event.repeat){event.preventDefault();unlock();charging.current=true;}}} onKeyUp={event=>{if(event.code==='Space'||event.code==='Enter'){event.preventDefault();fire();}}} onBlur={()=>charging.current=false} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);unlock();charging.current=true;}} onPointerUp={fire} onPointerCancel={()=>{charging.current=false;}} onLostPointerCapture={()=>{charging.current=false;}}>Hold / Shoot</button><button data-action="sprint" disabled={rotate||phase!=='playing'} onPointerDown={event=>{event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);local.current.sprint=true;}} onPointerUp={()=>local.current.sprint=false} onPointerCancel={()=>local.current.sprint=false} onLostPointerCapture={()=>local.current.sprint=false}>Sprint</button></div></div></footer>
 </section>;
}
