'use client';
import {useState} from 'react';
import styles from './NpcConversation.module.css';
const players=['Lionel Messi','Cristiano Ronaldo','Pelé','Diego Maradona','Johan Cruyff','Zinedine Zidane','Ronaldinho','Marta','Mia Hamm','Franz Beckenbauer'];
const teams=['Brazil 1970','Barcelona 2008–12','Spain 2008–12','Ajax 1971–73','AC Milan 1988–94','Real Madrid 2016–18','France 1998–2000','Arsenal 2003–04','Manchester United 1998–99','US Women 2015–19'];
type Mode='ten'|'five'|'duel'|'teams';
export default function NpcRanking(){
 const [mode,setMode]=useState<Mode>('ten'),[order,setOrder]=useState(players),[teamOrder,setTeamOrder]=useState(teams),[pick,setPick]=useState(''),[reason,setReason]=useState('');
 const list=mode==='teams'?teamOrder:order;
 const move=(index:number,delta:number)=>{const next=[...list],to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];if(mode==='teams')setTeamOrder(next);else setOrder(next);};
 return <section className={styles.ranking} aria-label="Noor’s ranking conversation"><p><strong>Your list, your reasons.</strong> These are conversation starters, not an official ranking. Different roles and eras make this an interesting debate.</p>
 <div className={styles.rankTabs}>{([['ten','Rank ten players'],['five','All-time top five'],['duel','Messi or Ronaldo?'],['teams','All-time teams']] as const).map(([id,label])=><button key={id} type="button" aria-pressed={mode===id} onClick={()=>{setMode(id);setReason('');}}>{label}</button>)}</div>
 {mode==='duel'?<><p>Would you take Cristiano Ronaldo or Lionel Messi for your team? What job would you want them to do?</p><div className={styles.rankTabs}>{['Lionel Messi','Cristiano Ronaldo','Depends on my team'].map(name=><button key={name} aria-pressed={pick===name} onClick={()=>setPick(name)}>{name}</button>)}</div>{pick&&<p role="status">{pick==='Depends on my team'?'Then start with what your team needs.':'You chose '+pick+'.'} Would you build around finishing, creating chances, or combining with teammates?</p>}</>:<><p>{mode==='five'?'Move your favourites into the first five places. The rest remain available below.':mode==='teams'?'Arrange these team eras in your preferred order. Think about their style and opponents, not only trophies.':'Move players up or down. Which strengths matter most in your list?'}</p><ol className={styles.rankList}>{list.map((name,index)=><li key={name} data-top={mode==='five'&&index<5}><span><b>{index+1}</b> {name}</span><div><button type="button" disabled={index===0} aria-label={`Move ${name} up`} onClick={()=>move(index,-1)}>↑</button><button type="button" disabled={index===list.length-1} aria-label={`Move ${name} down`} onClick={()=>move(index,1)}>↓</button></div></li>)}</ol></>}
 <p><strong>What matters most to you?</strong></p><div className={styles.rankTabs}>{['Skill and creativity','Helping the team','Big-game impact','Consistency'].map(value=><button key={value} aria-pressed={reason===value} onClick={()=>setReason(value)}>{value}</button>)}</div>
 {reason&&<p className={styles.rankResponse} role="status">{reason==='Skill and creativity'?'Name a move or decision that changed what a defender could do. Can you spot the same idea in a play lesson?':reason==='Helping the team'?'Who creates space, recovers possession or makes others better? Those actions can be easy to miss in a goals compilation.':reason==='Big-game impact'?'Pick a particular match moment. What did the player actually do, and who helped make it possible?':'Compare more than one game. A highlight shows a moment; consistency means repeating useful actions over time.'}</p>}
 <small>Friendly debate—there is no correct order. Your list resets when you leave this conversation.</small></section>;
}
