#!/usr/bin/env python3
"""Generate lib/graphics/shirtDigits.ts: the 0-9 outlines of Barlow Condensed Bold.

Barlow Condensed is (c) 2017 The Barlow Project Authors, SIL Open Font License 1.1
(see lib/graphics/shirtDigits.OFL.txt). Only the ten figure outlines are embedded,
so the shirt-number atlas can be drawn with Path2D without a web-font load race,
and the outlines can be checked in Node tests.

Usage (fontTools is only needed to regenerate; the output is committed):
  curl -L -o /tmp/BarlowCondensed-Bold.ttf \
    https://github.com/google/fonts/raw/main/ofl/barlowcondensed/BarlowCondensed-Bold.ttf
  python3 -m pip install fonttools
  python3 scripts/gen-shirt-digits.py /tmp/BarlowCondensed-Bold.ttf
"""
import os, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

src = sys.argv[1] if len(sys.argv) > 1 else 'BarlowCondensed-Bold.ttf'
out = os.path.join(os.path.dirname(__file__), '..', 'lib', 'graphics', 'shirtDigits.ts')
font = TTFont(src)
cmap, glyphs, glyf = font.getBestCmap(), font.getGlyphSet(), font['glyf']
units = font['head'].unitsPerEm
top = font['OS/2'].sCapHeight  # figures sit on the baseline and reach the cap height (700)

def fmt(v):
    v = round(v, 1)
    return str(int(v)) if v == int(v) else str(v)

rows = []
for ch in '0123456789':
    name = cmap[ord(ch)]
    g = glyf[name]
    pen = SVGPathPen(glyphs, ntos=fmt)
    # Font units, y flipped so +y runs down from the cap line (canvas convention).
    glyphs[name].draw(TransformPen(pen, (1, 0, 0, -1, 0, top)))
    rows.append((ch, glyphs[name].width, g.xMin, g.xMax, top - g.yMax, top - g.yMin, g.numberOfContours, pen.getCommands()))

lines = [
    '// GENERATED by scripts/gen-shirt-digits.py from Barlow Condensed Bold (v1.4).',
    '// Copyright 2017 The Barlow Project Authors (https://github.com/jpt/barlow).',
    '// Licensed under the SIL Open Font License 1.1: see ./shirtDigits.OFL.txt. Do not edit by hand.',
    '',
    '/** Font units per em, and the figure (cap) height every digit is drawn against. */',
    f'export const DIGIT_UNITS = {units}, DIGIT_HEIGHT = {top};',
    'export type DigitGlyph = {',
    '  /** Advance width in font units. */ advance: number;',
    '  /** Ink bounds in font units; y runs down from the cap line (0) to the baseline (DIGIT_HEIGHT). */',
    '  xMin: number; xMax: number; yMin: number; yMax: number;',
    '  /** Closed contours; counters (the holes in 0 4 6 8 9) wind opposite to the outer contour. */ contours: number;',
    '  /** SVG path data (M/L/Q/Z) in the same units; fill with the nonzero rule. */ path: string;',
    '};',
    'export const DIGIT_GLYPHS: readonly DigitGlyph[] = [',
]
for ch, adv, x0, x1, y0, y1, n, d in rows:
    lines.append(f'  /* {ch} */ {{advance:{adv},xMin:{x0},xMax:{x1},yMin:{y0},yMax:{y1},contours:{n},path:\'{d}\'}},')
lines.append('];')
lines.append('')
with open(out, 'w') as fh:
    fh.write('\n'.join(lines))
print('wrote', os.path.normpath(out))
