/* AUTO-GENERATED by scripts/gen-book-registry.cjs — do not edit by hand. */
import type {BookData} from './types';
import type {SpreadDef} from './popupEngine';
import {MESSI_BOOK} from './messi';
import {BRONZE_BOOK as b_bronze} from './stories/bronze';
import {BUFFON_BOOK as b_buffon} from './stories/buffon';
import {CRISTIANO_BOOK as b_cristiano} from './stories/cristiano';
import {CRUYFF_BOOK as b_cruyff} from './stories/cruyff';
import {DAVIES_BOOK as b_davies} from './stories/davies';
import {DEBRUYNE_BOOK as b_debruyne} from './stories/debruyne';
import {DROGBA_BOOK as b_drogba} from './stories/drogba';
import {ERIKSEN_BOOK as b_eriksen} from './stories/eriksen';
import {EUSEBIO_BOOK as b_eusebio} from './stories/eusebio';
import {FALCAO_BOOK as b_falcao} from './stories/falcao';
import {GARRINCHA_BOOK as b_garrincha} from './stories/garrincha';
import {HEGERBERG_BOOK as b_hegerberg} from './stories/hegerberg';
import {IBRAHIMOVIC_BOOK as b_ibrahimovic} from './stories/ibrahimovic';
import {INIESTA_BOOK as b_iniesta} from './stories/iniesta';
import {ISLAND_BOOK as b_island} from './stories/island';
import {KANE_BOOK as b_kane} from './stories/kane';
import {KERR_BOOK as b_kerr} from './stories/kerr';
import {LUKAKU_BOOK as b_lukaku} from './stories/lukaku';
import {MALDINI_BOOK as b_maldini} from './stories/maldini';
import {MANE_BOOK as b_mane} from './stories/mane';
import {MARTA_BOOK as b_marta} from './stories/marta';
import {MODRIC_BOOK as b_modric} from './stories/modric';
import {PELE_BOOK as b_pele} from './stories/pele';
import {PUTELLAS_BOOK as b_putellas} from './stories/putellas';
import {RASHFORD_BOOK as b_rashford} from './stories/rashford';
import {RONALDINHO_BOOK as b_ronaldinho} from './stories/ronaldinho';
import {RONALDO_BOOK as b_ronaldo} from './stories/ronaldo';
import {SAKA_BOOK as b_saka} from './stories/saka';
import {SALAH_BOOK as b_salah} from './stories/salah';
import {VARDY_BOOK as b_vardy} from './stories/vardy';
import {WEAH_BOOK as b_weah} from './stories/weah';
import {ZIDANE_BOOK as b_zidane} from './stories/zidane';
import v_b_messi from '../../public/voice/books/messi/narration.json';
import v_b_bronze from '../../public/voice/books/bronze/narration.json';
import v_b_buffon from '../../public/voice/books/buffon/narration.json';
import v_b_cristiano from '../../public/voice/books/cristiano/narration.json';
import v_b_cruyff from '../../public/voice/books/cruyff/narration.json';
import v_b_davies from '../../public/voice/books/davies/narration.json';
import v_b_debruyne from '../../public/voice/books/debruyne/narration.json';
import v_b_drogba from '../../public/voice/books/drogba/narration.json';
import v_b_eriksen from '../../public/voice/books/eriksen/narration.json';
import v_b_eusebio from '../../public/voice/books/eusebio/narration.json';
import v_b_falcao from '../../public/voice/books/falcao/narration.json';
import v_b_garrincha from '../../public/voice/books/garrincha/narration.json';
import v_b_hegerberg from '../../public/voice/books/hegerberg/narration.json';
import v_b_ibrahimovic from '../../public/voice/books/ibrahimovic/narration.json';
import v_b_iniesta from '../../public/voice/books/iniesta/narration.json';
import v_b_island from '../../public/voice/books/island/narration.json';
import v_b_kane from '../../public/voice/books/kane/narration.json';
import v_b_kerr from '../../public/voice/books/kerr/narration.json';
import v_b_lukaku from '../../public/voice/books/lukaku/narration.json';
import v_b_maldini from '../../public/voice/books/maldini/narration.json';
import v_b_mane from '../../public/voice/books/mane/narration.json';
import v_b_marta from '../../public/voice/books/marta/narration.json';
import v_b_modric from '../../public/voice/books/modric/narration.json';
import v_b_pele from '../../public/voice/books/pele/narration.json';
import v_b_putellas from '../../public/voice/books/putellas/narration.json';
import v_b_rashford from '../../public/voice/books/rashford/narration.json';
import v_b_ronaldinho from '../../public/voice/books/ronaldinho/narration.json';
import v_b_ronaldo from '../../public/voice/books/ronaldo/narration.json';
import v_b_saka from '../../public/voice/books/saka/narration.json';
import v_b_salah from '../../public/voice/books/salah/narration.json';
import v_b_vardy from '../../public/voice/books/vardy/narration.json';
import v_b_weah from '../../public/voice/books/weah/narration.json';
import v_b_zidane from '../../public/voice/books/zidane/narration.json';
/** Book text (Messi keeps its legacy action→steps mapping). */
export const REGISTRY_BOOKS:Record<string,BookData>={
 messi:{...MESSI_BOOK,player:'Lionel Messi',pages:MESSI_BOOK.pages.map(p=>({...p,steps:p.action==='touch'?3:1}))},
 "bronze":b_bronze,
 "buffon":b_buffon,
 "cristiano":b_cristiano,
 "cruyff":b_cruyff,
 "davies":b_davies,
 "debruyne":b_debruyne,
 "drogba":b_drogba,
 "eriksen":b_eriksen,
 "eusebio":b_eusebio,
 "falcao":b_falcao,
 "garrincha":b_garrincha,
 "hegerberg":b_hegerberg,
 "ibrahimovic":b_ibrahimovic,
 "iniesta":b_iniesta,
 "island":b_island,
 "kane":b_kane,
 "kerr":b_kerr,
 "lukaku":b_lukaku,
 "maldini":b_maldini,
 "mane":b_mane,
 "marta":b_marta,
 "modric":b_modric,
 "pele":b_pele,
 "putellas":b_putellas,
 "rashford":b_rashford,
 "ronaldinho":b_ronaldinho,
 "ronaldo":b_ronaldo,
 "saka":b_saka,
 "salah":b_salah,
 "vardy":b_vardy,
 "weah":b_weah,
 "zidane":b_zidane,
};
/** Narration manifests (Coach Bella sentence cues). */
export const REGISTRY_NARRATION:Record<string,unknown>={
 "messi":v_b_messi,
 "bronze":v_b_bronze,
 "buffon":v_b_buffon,
 "cristiano":v_b_cristiano,
 "cruyff":v_b_cruyff,
 "davies":v_b_davies,
 "debruyne":v_b_debruyne,
 "drogba":v_b_drogba,
 "eriksen":v_b_eriksen,
 "eusebio":v_b_eusebio,
 "falcao":v_b_falcao,
 "garrincha":v_b_garrincha,
 "hegerberg":v_b_hegerberg,
 "ibrahimovic":v_b_ibrahimovic,
 "iniesta":v_b_iniesta,
 "island":v_b_island,
 "kane":v_b_kane,
 "kerr":v_b_kerr,
 "lukaku":v_b_lukaku,
 "maldini":v_b_maldini,
 "mane":v_b_mane,
 "marta":v_b_marta,
 "modric":v_b_modric,
 "pele":v_b_pele,
 "putellas":v_b_putellas,
 "rashford":v_b_rashford,
 "ronaldinho":v_b_ronaldinho,
 "ronaldo":v_b_ronaldo,
 "saka":v_b_saka,
 "salah":v_b_salah,
 "vardy":v_b_vardy,
 "weah":v_b_weah,
 "zidane":v_b_zidane,
};
/** Paper spreads, each in its own lazily loaded chunk. */
export const REGISTRY_SPREADS:Record<string,()=>Promise<{SPREADS:Record<string,SpreadDef>}>>={
 "messi":()=>import('./bookDiorama'),
 "bronze":()=>import('./spreads/bronze'),
 "buffon":()=>import('./spreads/buffon'),
 "cristiano":()=>import('./spreads/cristiano'),
 "cruyff":()=>import('./spreads/cruyff'),
 "davies":()=>import('./spreads/davies'),
 "debruyne":()=>import('./spreads/debruyne'),
 "drogba":()=>import('./spreads/drogba'),
 "eriksen":()=>import('./spreads/eriksen'),
 "eusebio":()=>import('./spreads/eusebio'),
 "falcao":()=>import('./spreads/falcao'),
 "garrincha":()=>import('./spreads/garrincha'),
 "hegerberg":()=>import('./spreads/hegerberg'),
 "ibrahimovic":()=>import('./spreads/ibrahimovic'),
 "iniesta":()=>import('./spreads/iniesta'),
 "island":()=>import('./spreads/island'),
 "kane":()=>import('./spreads/kane'),
 "kerr":()=>import('./spreads/kerr'),
 "lukaku":()=>import('./spreads/lukaku'),
 "maldini":()=>import('./spreads/maldini'),
 "mane":()=>import('./spreads/mane'),
 "marta":()=>import('./spreads/marta'),
 "modric":()=>import('./spreads/modric'),
 "pele":()=>import('./spreads/pele'),
 "putellas":()=>import('./spreads/putellas'),
 "rashford":()=>import('./spreads/rashford'),
 "ronaldinho":()=>import('./spreads/ronaldinho'),
 "ronaldo":()=>import('./spreads/ronaldo'),
 "saka":()=>import('./spreads/saka'),
 "salah":()=>import('./spreads/salah'),
 "vardy":()=>import('./spreads/vardy'),
 "weah":()=>import('./spreads/weah'),
 "zidane":()=>import('./spreads/zidane'),
};
