'use client';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {BackButton} from '../BackButton';
import {Icon} from '../Icon';
import {createArcadeGame,type ArcadeKind,type ArcadeInput,type ArcadeHUD} from '@/lib/arcade/arcadeGames';
import {isSoundEnabled,getSoundVolume} from '@/lib/games/sound';
import {recordExploreActivity} from '@/lib/town/exploreActivity';
import styles from './ArcadeGame3D.module.css';
const descriptions={tennis:{name:'Futbol Tennis',tag:'FIND YOUR ANGLE',copy:'One bounce. One clean return. Move into position, then send the ball into open space.',help:'Move: WASD / arrows or drag the court. Space: kick. J: lob. K: drop shot.',learn:'Get beside the ball before you kick. A balanced touch gives you more control.'},pinball:{name:'Futbol Pinball',tag:'PLAY THE ANGLES',copy:'Work the flippers, beat the keeper, and keep the ball in play. Every goal brings a new defender.',help:'A / ←: left flipper. D / →: right flipper. Hold Space to launch.',learn:'Time the contact. A late touch changes the angle of your next shot.'},runner:{name:'Breakaway Run',tag:'READ THE OPEN LANE',copy:'Find space, dodge challenges, and finish through the open lane. Collect five touches for a burst of pace.',help:'A / D or swipe: change lanes. Space: jump. J / ↓: skill slide.',learn:'Look beyond the nearest defender. Plan your next move before the challenge.'}};
export default function ArcadeGame3D({kind,onExit}:{kind:ArcadeKind;onExit:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef<ReturnType<typeof createArcadeGame>|null>(null),phaseRef=useRef<'ready'|'playing'|'paused'|'over'>('ready'),input=useRef<ArcadeInput>({x:0,y:0,left:false,right:false,charge:false}),keys=useRef(new Set<string>()),held=useRef(new Map<number,number>()),wake=useRef(()=>{}),audio=useRef<AudioContext|null>(null),stick=useRef<HTMLDivElement>(null),stickId=useRef<number|null>(null);
 const[phase,setPhase]=useState<typeof phaseRef.current>('ready'),[error,setError]=useState(false),[hud,setHud]=useState<ArcadeHUD>({score:'0',detail:'',message:'',over:false,ready:true});
 const info=descriptions[kind];
 const release=()=>{keys.current.clear();held.current.clear();Object.assign(input.current,{x:0,y:0,left:false,right:false,charge:false});stickId.current=null;if(stick.current)stick.current.style.setProperty('--stick','translate(0,0)');};
 const unlock=()=>{if(!isSoundEnabled()||getSoundVolume()===0)return;try{audio.current??=new AudioContext();void audio.current.resume();}catch{}};
 const sound=(goal:boolean)=>{const ctx=audio.current;if(!ctx||ctx.state!=='running'||!isSoundEnabled())return;const oscillator=ctx.createOscillator(),gain=ctx.createGain(),now=ctx.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(goal?660:230,now);oscillator.frequency.exponentialRampToValueAtTime(goal?990:95,now+.1);gain.gain.setValueAtTime(Math.max(.0001,.08*getSoundVolume()),now);gain.gain.exponentialRampToValueAtTime(.0001,now+.16);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start();oscillator.stop(now+.17);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};};
 const change=(next:typeof phase)=>{release();phaseRef.current=next;setPhase(next);wake.current();};
 const start=()=>{unlock();if(phaseRef.current!=='paused')game.current?.reset();recordExploreActivity('arcade');change('playing');canvas.current?.focus({preventScroll:true});};
 const action=(id:number)=>{if(phaseRef.current!=='playing')return;unlock();game.current?.action(id);wake.current();};
 const recompute=()=>{const vals=[...held.current.values()],k=keys.current;input.current.left=vals.includes(0)||k.has('KeyA')||k.has('ArrowLeft');input.current.right=vals.includes(1)||k.has('KeyD')||k.has('ArrowRight');input.current.charge=vals.includes(2)||k.has('Space');};
 const hold=(id:number)=>({onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{e.preventDefault();if(phaseRef.current!=='playing')return;unlock();e.currentTarget.setPointerCapture(e.pointerId);held.current.set(e.pointerId,id);recompute();wake.current();},onPointerUp:(e:PointerEvent<HTMLButtonElement>)=>{const was=held.current.get(e.pointerId);held.current.delete(e.pointerId);recompute();if(was===2)action(2);},onPointerCancel:(e:PointerEvent<HTMLButtonElement>)=>{held.current.delete(e.pointerId);recompute();},onLostPointerCapture:(e:PointerEvent<HTMLButtonElement>)=>{held.current.delete(e.pointerId);recompute();}});
 const moveStick=(e:PointerEvent<HTMLDivElement>)=>{if(stickId.current!==e.pointerId)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left-rect.width/2)/(rect.width*.35),y=(e.clientY-rect.top-rect.height/2)/(rect.height*.35),len=Math.max(1,Math.hypot(x,y));input.current.x=x/len;input.current.y=y/len;e.currentTarget.style.setProperty('--stick',`translate(${x/len*24}px,${y/len*24}px)`);wake.current();};
 useEffect(()=>{
  const el=canvas.current;if(!el)return;let runtime:ReturnType<typeof createArcadeGame>;try{runtime=createArcadeGame(el,kind,sound);game.current=runtime;}catch{setError(true);return;}
  let frame=0,last=0,lastHud=0,disposed=false,drag:number|null=null,dragX=0,dragY=0;const interval=1000/(runtime.stage.mobile?30:60);
  const draw=(now:number)=>{frame=0;if(disposed||document.hidden)return;if(last&&now-last<interval-1){frame=requestAnimationFrame(draw);return;}const dt=last?Math.min((now-last)/1000,.05):1/60;last=now;
   if(phaseRef.current==='playing'){const k=keys.current;let x=Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),y=Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW'));const activeInput={...input.current,x:kind==='runner'?input.current.x:x||input.current.x,y:y||input.current.y};runtime.update(dt,activeInput);const view=runtime.hud();if(now-lastHud>100||view.ready||view.over){setHud(view);lastHud=now;}if(view.over){if(kind==='runner')try{const best=Number(localStorage.getItem('fi.game.runner.best')||0);if(runtime.state.runner.score>best)localStorage.setItem('fi.game.runner.best',String(runtime.state.runner.score));}catch{}phaseRef.current='over';setPhase('over');setHud(view);release();}}
   runtime.stage.render();el.dataset.frames=String(Number(el.dataset.frames??0)+1);if(phaseRef.current==='playing'&&(runtime.needsFrames()||keys.current.size>0||held.current.size>0||input.current.x!==0||input.current.y!==0))frame=requestAnimationFrame(draw);else last=0;
  };
  wake.current=()=>{if(!disposed&&!document.hidden&&!frame)frame=requestAnimationFrame(draw);};
  const pause=()=>{if(phaseRef.current==='playing'){release();phaseRef.current='paused';setPhase('paused');}if(frame)cancelAnimationFrame(frame);frame=0;last=0;};
  const visibility=()=>{if(document.hidden)pause();else wake.current();};
  const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('button,input,select,textarea,a'))return;if(e.code==='Escape'||e.code==='KeyP'){e.preventDefault();if(phaseRef.current==='playing')change('paused');else if(phaseRef.current==='paused')change('playing');return;}if(!['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyJ','KeyK'].includes(e.code))return;e.preventDefault();if(phaseRef.current!=='playing')return;keys.current.add(e.code);unlock();if(kind==='pinball')recompute();else if(!e.repeat){if(e.code==='Space')action(0);if(e.code==='KeyJ'||kind==='runner'&&e.code==='ArrowDown')action(1);if(e.code==='KeyK')action(2);if(kind==='runner'&&(e.code==='KeyA'||e.code==='ArrowLeft'))runtime.state.runner.lane=Math.max(-1,runtime.state.runner.lane-1);if(kind==='runner'&&(e.code==='KeyD'||e.code==='ArrowRight'))runtime.state.runner.lane=Math.min(1,runtime.state.runner.lane+1);}wake.current();};
  const up=(e:KeyboardEvent)=>{const pressed=keys.current.delete(e.code);recompute();if(kind==='pinball'&&e.code==='Space'&&pressed)action(2);};
  const pointerDown=(e:globalThis.PointerEvent)=>{if(phaseRef.current!=='playing'||drag!==null)return;drag=e.pointerId;dragX=e.clientX;dragY=e.clientY;el.setPointerCapture(e.pointerId);el.focus({preventScroll:true});if(kind==='tennis')runtime.target(e.clientX,e.clientY);wake.current();};
  const pointerMove=(e:globalThis.PointerEvent)=>{if(e.pointerId===drag&&kind==='tennis'){runtime.target(e.clientX,e.clientY);wake.current();}};
  const pointerUp=(e:globalThis.PointerEvent)=>{if(e.pointerId!==drag)return;drag=null;if(kind==='tennis')action(0);if(kind==='runner'){const x=e.clientX-dragX,y=e.clientY-dragY;if(Math.abs(x)>25&&Math.abs(x)>Math.abs(y))runtime.state.runner.lane=Math.max(-1,Math.min(1,runtime.state.runner.lane+Math.sign(x)));else if(y<-25)action(0);else if(y>25)action(1);}};
  const cancel=()=>{drag=null;};const observer=new ResizeObserver(()=>{runtime.fit();wake.current();});observer.observe(el);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);el.addEventListener('pointerdown',pointerDown);el.addEventListener('pointermove',pointerMove);el.addEventListener('pointerup',pointerUp);el.addEventListener('pointercancel',cancel);el.addEventListener('lostpointercapture',cancel);
  if(process.env.NODE_ENV!=='production')(window as unknown as {__arcade3d:unknown}).__arcade3d={runtime,phaseRef,input};wake.current();
  return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility);el.removeEventListener('pointerdown',pointerDown);el.removeEventListener('pointermove',pointerMove);el.removeEventListener('pointerup',pointerUp);el.removeEventListener('pointercancel',cancel);el.removeEventListener('lostpointercapture',cancel);release();runtime.stage.dispose();game.current=null;wake.current=()=>{};void audio.current?.close();audio.current=null;delete (window as unknown as {__arcade3d?:unknown}).__arcade3d;};
 // The controller lives for this game mount; refs hold changing input and phase.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[kind]);
 return <div className={styles.game} data-arcade-kind={kind}><canvas ref={canvas} tabIndex={0} aria-label={`${info.name} game field`}/><header className={styles.header}><BackButton onBack={onExit}/><div><small>{info.tag}</small><h2>{info.name}</h2></div><button className={styles.pause} onClick={()=>phase==='playing'?change('paused'):phase==='paused'?start():null} disabled={phase==='ready'||phase==='over'} aria-label={phase==='paused'?'Resume game':'Pause game'}><Icon name={phase==='paused'?'play':'pause'} size={22}/></button></header>
 {phase!=='ready'&&<div className={styles.score} aria-live="polite"><strong>{hud.score}</strong><span>{hud.detail}</span></div>}
 {phase==='playing'&&<><p className={styles.message}>{hud.message}</p><footer className={styles.controls}>{kind==='pinball'?<><button {...hold(0)} aria-label="Left flipper"><Icon name="back" size={28}/><span>Left</span></button><button {...hold(2)} disabled={!hud.ready}>Launch</button><button {...hold(1)} aria-label="Right flipper"><Icon name="arrow" size={28}/><span>Right</span></button></>:<><div ref={stick} className={styles.stick} role="group" aria-label="Movement joystick" onPointerDown={e=>{if(stickId.current!==null)return;e.preventDefault();stickId.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveStick(e);}} onPointerMove={moveStick} onPointerUp={e=>{if(stickId.current===e.pointerId){stickId.current=null;input.current.x=input.current.y=0;e.currentTarget.style.setProperty('--stick','translate(0,0)');}}} onPointerCancel={()=>{stickId.current=null;input.current.x=input.current.y=0;}} onLostPointerCapture={()=>{stickId.current=null;input.current.x=input.current.y=0;}}><i/></div><div className={styles.actions}><button onClick={()=>action(1)}>{kind==='tennis'?'Lob':'Slide'}</button>{kind==='tennis'&&<button onClick={()=>action(2)}>Drop</button>}<button onClick={()=>action(0)}>{kind==='tennis'?(hud.ready?'Serve':'Kick'):'Jump'}</button></div></>}</footer></>}
 {(phase!=='playing'||error)&&<div className={styles.overlay}><section className={styles.card}><span className={styles.badge}>{error?'TAKE A BREATHER':phase==='over'?'FULL TIME':phase==='paused'?'TIME OUT':info.tag}</span><h3>{error?'The pitch couldn’t load.':phase==='over'?'One more game?':phase==='paused'?'Ready when you are.':info.name}</h3><p>{error?'Return to the arcade and try again.':phase==='ready'?info.copy:phase==='over'?`${hud.score} · ${hud.detail}`:info.learn}</p>{!error&&<button className={styles.primary} onClick={start}>{phase==='paused'?'Resume':phase==='over'?'Play again':'Play'}</button>}<button className={styles.exit} onClick={onExit}>Back to arcade</button><small>{info.help}</small></section></div>}
 </div>;
}
