'use client';
import {readArcadeRecord,saveArcadeRecord} from '@/lib/arcade/arcadeRecords';
import {TENNIS_COURTS} from '@/lib/games/soccerTennis';
import {arcadeFeedback} from '@/lib/arcade/arcadeFeedback';
import {useEffect,useRef,useState,type PointerEvent,type KeyboardEvent as ReactKeyboardEvent} from 'react';
import {BackButton} from '../BackButton';
import {Icon} from '../Icon';
import {createArcadeGame,type ArcadeKind,type ArcadeInput,type ArcadeHUD} from '@/lib/arcade/arcadeGames';
import {useArcadeEntry} from '@/lib/arcade/useArcadeEntry';
import {paintJoystick} from '@/lib/town/joystickFeedback';
import {frameCapSlot} from '@/lib/town/frameCap';
import {isSoundEnabled,getSoundVolume} from '@/lib/games/sound';
import {creditRun,arcadeCoinTarget} from '@/lib/arcade/arcadeWallet';
import {recordExploreActivity} from '@/lib/town/exploreActivity';
import styles from './ArcadeGame3D.module.css';
const descriptions={tennis:{name:'Futbol Tennis',tag:'FIND YOUR ANGLE',copy:'One bounce. One clean return. Move into position, then send the ball into open space.',help:'Move: WASD / arrows or drag. Left/right aims your return. Plant and hit just after the bounce for a Perfect Return. Release to plant. Space: kick · J: lob · K: drop · H: header · L: scissor.',learn:'Get beside the ball before you kick. A balanced touch gives you more control.'},pinball:{name:'Futbol Pinball',tag:'PLAY THE ANGLES',copy:'Build with one flipper. Switch to the other to light the goal, then finish before the chance closes.',help:'A / ←: left flipper. D / →: right flipper. Hold Space to launch; tap Space during play to nudge. Switch flippers to recharge.',learn:'Use both feet to build the move; aim beyond the keeper for a corner finish.'},runner:{name:'Breakaway Run',tag:'READ THE OPEN LANE',copy:'Collect footballs, dribble into space, then shoot to knock obstacles aside or finish for bonus points.',help:'A / D or swipe: change lanes. Hold Space or Shoot: charge, release: blast. ↑ / W / J / swipe up: jump; shoot in the air for a volley. ↓ / S / K / swipe down: slide.',learn:'Look beyond the nearest defender. Plan your next move before the challenge.'}};
export default function ArcadeGame3D({kind,onExit}:{kind:ArcadeKind;onExit:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef<ReturnType<typeof createArcadeGame>|null>(null),phaseRef=useRef<'ready'|'playing'|'paused'|'over'>('ready'),input=useRef<ArcadeInput>({x:0,y:0,left:false,right:false,charge:false}),keys=useRef(new Set<string>()),held=useRef(new Map<number,number>()),wake=useRef(()=>{}),audio=useRef<AudioContext|null>(null),stick=useRef<HTMLDivElement>(null),stickId=useRef<number|null>(null),dragId=useRef<number|null>(null),shootPointer=useRef<number|null>(null);
 const[phase,setPhase]=useState<typeof phaseRef.current>('ready'),[error,setError]=useState(false),[hud,setHud]=useState<ArcadeHUD>({score:'0',detail:'',message:'',over:false,ready:true});
 const [record,setRecord]=useState({best:0,unlocked:1});
 const coinRun=useRef(''),coinTarget=useRef(0),entry=useArcadeEntry(kind);
 const pinballPressMode=useRef<'launch'|'nudge'|null>(null);
 const chargeSound=useRef<{osc:OscillatorNode;gain:GainNode}|null>(null);
 const stopChargeSound=()=>{const voice=chargeSound.current;if(!voice)return;chargeSound.current=null;const now=voice.osc.context.currentTime;voice.gain.gain.cancelScheduledValues(now);voice.gain.gain.setTargetAtTime(.0001,now,.015);voice.osc.stop(now+.06);};
 const pinballSound=(cue:'left'|'right'|'charge'|'launch')=>{
  const ctx=audio.current,volume=getSoundVolume();if(!ctx||!isSoundEnabled()||volume===0)return;
  const now=ctx.currentTime,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=cue==='charge'?'triangle':'sine';osc.connect(gain);gain.connect(ctx.destination);
  const frequency=cue==='left'?380:cue==='right'?470:cue==='launch'?760:90,duration=cue==='charge'?4:cue==='launch'?.3:.075;
  osc.frequency.setValueAtTime(frequency,now);osc.frequency.exponentialRampToValueAtTime(cue==='charge'?330:cue==='launch'?115:95,now+(cue==='charge'?1.12:duration));
  gain.gain.setValueAtTime(.0001,now);gain.gain.linearRampToValueAtTime(volume*(cue==='charge'?.055:.13),now+.008);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.start();osc.stop(now+duration+.02);
  if(cue==='charge')chargeSound.current={osc,gain};osc.onended=()=>{osc.disconnect();gain.disconnect();if(chargeSound.current?.osc===osc)chargeSound.current=null;};
 };
 const goalRattle=useRef<AudioBuffer|null>(null);
 const info=descriptions[kind];
 const [touchDevice,setTouchDevice]=useState(false);
 useEffect(()=>{setTouchDevice(matchMedia('(pointer:coarse)').matches);},[]);
 const touchHelp={tennis:'Left thumb: move and aim. Release to plant. Right thumb: Kick, Lob or Drop. High ball: blue Header or coral Scissor for extra power. Gold ring aims. Plant your feet and return just after the bounce for a Perfect Return.',pinball:'Hold Launch, then release. Watch the flipper lights as the ball drops. Tap left or right to build, switch and finish. Nudge rescues a falling ball; switching flippers recharges it.',runner:'Tap arrows or swipe to change lanes. Tap Shoot for a quick kick. Hold and release for a power blast. Jump then Shoot for an aerial volley, or Slide past defenders.'}[kind];
 const release=()=>{if(kind==='pinball')game.current?.state.pinball.flipperPulse.fill(0);pinballPressMode.current=null;stopChargeSound();if(kind==='runner')game.current?.action(5);shootPointer.current=null;const pointer=dragId.current;dragId.current=null;if(pointer!==null&&canvas.current?.hasPointerCapture(pointer))canvas.current.releasePointerCapture(pointer);keys.current.clear();held.current.clear();Object.assign(input.current,{x:0,y:0,left:false,right:false,charge:false});stickId.current=null;paintJoystick(stick.current,0,0);if(stick.current)stick.current.style.setProperty('--stick','translate(0,0)');};
 const unlock=()=>{if(!isSoundEnabled()||getSoundVolume()===0)return;try{audio.current??=new AudioContext();void audio.current.resume();}catch{}};
 const sound=(goal:boolean,cue?:string)=>{
  arcadeFeedback(audio.current,cue??(goal?'goal':'touch'));
  const ctx=audio.current,volume=getSoundVolume();if(!ctx||ctx.state!=='running'||!isSoundEnabled()||volume===0)return;
  const now=ctx.currentTime;
  if(kind==='runner'&&goal){
   // Short, gesture-unlocked frame thump and net rattle. No sustained source.
   const thump=ctx.createOscillator(),body=ctx.createGain();thump.frequency.setValueAtTime(135,now);thump.frequency.exponentialRampToValueAtTime(45,now+.18);body.gain.setValueAtTime(.13*volume,now);body.gain.exponentialRampToValueAtTime(.0001,now+.22);thump.connect(body);body.connect(ctx.destination);thump.start(now);thump.stop(now+.23);thump.onended=()=>{thump.disconnect();body.disconnect();};
   if(!goalRattle.current){const buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.24),ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.exp(-i/data.length*4);goalRattle.current=buffer;}
   const rattle=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),air=ctx.createGain();rattle.buffer=goalRattle.current;filter.type='bandpass';filter.frequency.value=1700;filter.Q.value=.6;air.gain.setValueAtTime(.09*volume,now);air.gain.exponentialRampToValueAtTime(.0001,now+.24);rattle.connect(filter);filter.connect(air);air.connect(ctx.destination);rattle.start(now);rattle.onended=()=>{rattle.disconnect();filter.disconnect();air.disconnect();};
  }
 };
 const change=(next:typeof phase)=>{release();phaseRef.current=next;setPhase(next);wake.current();};
 const start=async()=>{unlock();if(phaseRef.current!=='paused'){const id=await entry.enter();if(!id)return;game.current?.reset();coinRun.current=id;coinTarget.current=0;}recordExploreActivity('arcade');change('playing');canvas.current?.focus({preventScroll:true});};
 const action=(id:number)=>{if(phaseRef.current!=='playing')return;unlock();if(kind==='pinball'&&id===2&&game.current?.state.pinball.phase==='ready'){stopChargeSound();pinballSound('launch');}game.current?.action(id);wake.current();};
 // Nudge is immediate; only a press begun at the plunger can launch on release.
 const finishPinballPress=()=>{if(input.current.charge)return;const mode=pinballPressMode.current;pinballPressMode.current=null;if(mode==='launch'&&game.current?.state.pinball.phase==='ready')action(2);};
 const releaseStick=(event?:{pointerId:number})=>{if(event&&event.pointerId!==stickId.current)return;paintJoystick(stick.current,0,0);stickId.current=null;input.current.x=input.current.y=0;stick.current?.style.setProperty('--stick','translate(0,0)');};
 const runnerShootHold={onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{e.preventDefault();if(phaseRef.current!=='playing'||shootPointer.current!==null)return;shootPointer.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);action(3);},onPointerUp:(e:PointerEvent<HTMLButtonElement>)=>{if(shootPointer.current!==e.pointerId)return;shootPointer.current=null;action(4);},onPointerCancel:(e:PointerEvent<HTMLButtonElement>)=>{if(shootPointer.current!==e.pointerId)return;shootPointer.current=null;action(5);},onLostPointerCapture:(e:PointerEvent<HTMLButtonElement>)=>{if(shootPointer.current!==e.pointerId)return;shootPointer.current=null;action(5);},onKeyDown:(e:ReactKeyboardEvent<HTMLButtonElement>)=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(!e.repeat&&shootPointer.current===null){shootPointer.current=-1;action(3);}}},onKeyUp:(e:ReactKeyboardEvent<HTMLButtonElement>)=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();if(shootPointer.current===-1){shootPointer.current=null;action(4);}}},onBlur:()=>{shootPointer.current=null;action(5);},onClick:(e:{detail:number})=>{if(e.detail===0&&!game.current?.state.runner.charging)action(0);}};
 const pressAction=(id:number)=>({onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{e.preventDefault();action(id);},onClick:(e:{detail:number})=>{if(e.detail===0)action(id);}});
 const pressLane=(direction:number)=>({onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{e.preventDefault();changeLane(direction);},onClick:(e:{detail:number})=>{if(e.detail===0)changeLane(direction);}});
 const changeLane=(direction:number)=>{if(phaseRef.current!=='playing'||!game.current)return;game.current.state.runner.lane=Math.max(-1,Math.min(1,game.current.state.runner.lane+direction));wake.current();};
 const recompute=()=>{const wasLeft=input.current.left,wasRight=input.current.right,wasCharge=input.current.charge;const vals=[...held.current.values()],k=keys.current;input.current.left=vals.includes(0)||k.has('KeyA')||k.has('ArrowLeft');input.current.right=vals.includes(1)||k.has('KeyD')||k.has('ArrowRight');input.current.charge=vals.includes(2)||k.has('Space');if(kind==='pinball'&&phaseRef.current==='playing'){if(input.current.left&&!wasLeft){pinballSound('left');game.current?.action(0);}if(input.current.right&&!wasRight){pinballSound('right');game.current?.action(1);}if(input.current.charge&&!wasCharge){pinballPressMode.current=game.current?.state.pinball.phase==='ready'?'launch':'nudge';if(pinballPressMode.current==='launch')pinballSound('charge');else action(2);}if(!input.current.charge&&wasCharge)stopChargeSound();}};
 const hold=(id:number)=>({onKeyDown:(e:ReactKeyboardEvent<HTMLButtonElement>)=>{if(e.code!=='Space'&&e.code!=='Enter')return;e.preventDefault();if(e.repeat||phaseRef.current!=='playing')return;unlock();held.current.set(-id-1,id);recompute();wake.current();},onKeyUp:(e:ReactKeyboardEvent<HTMLButtonElement>)=>{if(e.code!=='Space'&&e.code!=='Enter')return;e.preventDefault();const was=held.current.delete(-id-1);recompute();if(was&&id===2)finishPinballPress();},onBlur:()=>{if(id===2)pinballPressMode.current=null;held.current.delete(-id-1);recompute();},onPointerDown:(e:PointerEvent<HTMLButtonElement>)=>{e.preventDefault();if(phaseRef.current!=='playing')return;unlock();e.currentTarget.setPointerCapture(e.pointerId);held.current.set(e.pointerId,id);recompute();wake.current();},onPointerUp:(e:PointerEvent<HTMLButtonElement>)=>{const was=held.current.get(e.pointerId);held.current.delete(e.pointerId);recompute();if(was===2)finishPinballPress();},onPointerCancel:(e:PointerEvent<HTMLButtonElement>)=>{const canceled=held.current.get(e.pointerId);if(canceled!==undefined&&canceled<2&&game.current)game.current.state.pinball.flipperPulse[canceled]=0;if(held.current.get(e.pointerId)===2)pinballPressMode.current=null;held.current.delete(e.pointerId);recompute();},onLostPointerCapture:(e:PointerEvent<HTMLButtonElement>)=>{const canceled=held.current.get(e.pointerId);if(canceled!==undefined&&canceled<2&&game.current)game.current.state.pinball.flipperPulse[canceled]=0;if(held.current.get(e.pointerId)===2)pinballPressMode.current=null;held.current.delete(e.pointerId);recompute();}});
 const moveStick=(e:PointerEvent<HTMLDivElement>)=>{if(stickId.current!==e.pointerId)return;const rect=e.currentTarget.getBoundingClientRect(),x=(e.clientX-rect.left-rect.width/2)/(rect.width*.35),y=(e.clientY-rect.top-rect.height/2)/(rect.height*.35),len=Math.max(1,Math.hypot(x,y));input.current.x=x/len;input.current.y=y/len;paintJoystick(e.currentTarget,x/len*36,y/len*36);e.currentTarget.style.setProperty('--stick',`translate(${x/len*24}px,${y/len*24}px)`);wake.current();};
 useEffect(()=>{
  const el=canvas.current;if(!el)return;let runtime:ReturnType<typeof createArcadeGame>;try{runtime=createArcadeGame(el,kind,sound);game.current=runtime;const saved=readArcadeRecord(kind);setRecord(saved);if(kind==='tennis')runtime.state.tennis.level=Math.min(5,saved.unlocked);}catch{setError(true);return;}
  let frame=0,last=0,slot=0,lastHud=0,disposed=false,dragX=0,dragY=0,dragHandled=false;const interval=1000/(runtime.stage.mobile?30:60);
  const draw=(now:number)=>{frame=0;if(disposed||document.hidden)return;const nextSlot=frameCapSlot(now,slot,interval);if(nextSlot<0){frame=requestAnimationFrame(draw);return;}slot=nextSlot;const dt=last?Math.min((now-last)/1000,.05):1/60;last=now;
   if(phaseRef.current==='playing'){const k=keys.current;let x=Number(k.has('ArrowRight')||k.has('KeyD'))-Number(k.has('ArrowLeft')||k.has('KeyA')),y=Number(k.has('ArrowDown')||k.has('KeyS'))-Number(k.has('ArrowUp')||k.has('KeyW'));const activeInput={...input.current,x:kind==='runner'?input.current.x:x||input.current.x,y:y||input.current.y};runtime.update(dt,activeInput);const coins=kind==='runner'?arcadeCoinTarget('runner',runtime.state.runner):kind==='pinball'?arcadeCoinTarget('pinball',runtime.state.pinball):arcadeCoinTarget('tennis',{cleanReturns:runtime.state.tennis.cleanReturns,points:runtime.state.tennis.score.you,won:runtime.state.tennis.winner==='you'});if(coinRun.current&&coins>coinTarget.current){coinTarget.current=coins;void creditRun(coinRun.current,kind,coins,kind==='runner'?'Goals and collected footballs':kind==='pinball'?'Goals and passing moves':'Clean returns and points');}const view=runtime.hud();if(now-lastHud>100||view.ready||view.over){setHud(view);lastHud=now;}if(view.over){setRecord(saveArcadeRecord(kind,kind==='tennis'?runtime.state.tennis.bestRally:kind==='runner'?runtime.state.runner.score:runtime.state.pinball.score,kind==='tennis'?Math.min(5,runtime.state.tennis.level+(runtime.state.tennis.winner==='you'?1:0)):kind==='runner'?Math.min(6,runtime.state.runner.level):runtime.state.pinball.level));if(kind==='runner')try{const best=Number(localStorage.getItem('fi.game.runner.best')||0);if(runtime.state.runner.score>best)localStorage.setItem('fi.game.runner.best',String(runtime.state.runner.score));}catch{}phaseRef.current='over';setPhase('over');setHud(view);release();}}
   runtime.stage.render();el.dataset.frames=String(Number(el.dataset.frames??0)+1);if(phaseRef.current==='playing'&&(runtime.needsFrames()||keys.current.size>0||held.current.size>0||input.current.x!==0||input.current.y!==0))frame=requestAnimationFrame(draw);else{last=0;slot=0;}
  };
  wake.current=()=>{if(!disposed&&!document.hidden&&!frame)frame=requestAnimationFrame(draw);};
  const pause=()=>{if(phaseRef.current==='playing'){release();phaseRef.current='paused';setPhase('paused');}if(frame)cancelAnimationFrame(frame);frame=0;last=0;slot=0;};
  const visibility=()=>{if(document.hidden)pause();else wake.current();};
  const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&e.target.closest('button,input,select,textarea,a'))return;if(e.code==='Escape'||e.code==='KeyP'){e.preventDefault();if(phaseRef.current==='playing')change('paused');else if(phaseRef.current==='paused')change('playing');return;}if(!['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyJ','KeyK',...(kind==='tennis'?['KeyH','KeyL']:[])].includes(e.code))return;e.preventDefault();if(phaseRef.current!=='playing')return;keys.current.add(e.code);unlock();if(kind==='pinball')recompute();else if(!e.repeat){if(e.code==='Space')action(kind==='runner'?3:0);if(kind==='tennis'&&e.code==='KeyH')action(3);if(kind==='tennis'&&e.code==='KeyL')action(4);if(e.code==='KeyJ'||kind==='runner'&&(e.code==='ArrowUp'||e.code==='KeyW'))action(1);if(e.code==='KeyK'||kind==='runner'&&(e.code==='ArrowDown'||e.code==='KeyS'))action(2);if(kind==='runner'&&(e.code==='KeyA'||e.code==='ArrowLeft'))runtime.state.runner.lane=Math.max(-1,runtime.state.runner.lane-1);if(kind==='runner'&&(e.code==='KeyD'||e.code==='ArrowRight'))runtime.state.runner.lane=Math.min(1,runtime.state.runner.lane+1);}wake.current();};
  const up=(e:KeyboardEvent)=>{const pressed=keys.current.delete(e.code);recompute();if(kind==='pinball'&&e.code==='Space'&&pressed)finishPinballPress();if(kind==='runner'&&e.code==='Space'&&pressed)action(4);};
  const pointerDown=(e:globalThis.PointerEvent)=>{if(phaseRef.current!=='playing'||dragId.current!==null)return;dragId.current=e.pointerId;dragHandled=false;dragX=e.clientX;dragY=e.clientY;el.setPointerCapture(e.pointerId);el.focus({preventScroll:true});if(kind==='tennis')runtime.target(e.clientX,e.clientY);wake.current();};
  // Commit as the swipe crosses its threshold, not after the thumb lifts.
  // One gesture is one decision; holding/returning the finger cannot double-cut.
  const runnerGesture=(x:number,y:number)=>{if(dragHandled||Math.max(Math.abs(x),Math.abs(y))<=25)return;dragHandled=true;if(Math.abs(x)>Math.abs(y))changeLane(Math.sign(x));else action(y<0?1:2);};
  const pointerMove=(e:globalThis.PointerEvent)=>{if(e.pointerId!==dragId.current)return;if(kind==='tennis')runtime.target(e.clientX,e.clientY);else if(kind==='runner')runnerGesture(e.clientX-dragX,e.clientY-dragY);wake.current();};
  const pointerUp=(e:globalThis.PointerEvent)=>{if(e.pointerId!==dragId.current)return;dragId.current=null;if(kind==='tennis')action(0);if(kind==='runner'){const x=e.clientX-dragX,y=e.clientY-dragY;runnerGesture(x,y);if(!dragHandled&&Math.hypot(x,y)<15)action(0);}};
  const cancel=()=>{dragId.current=null;};const observer=new ResizeObserver(()=>{runtime.fit();wake.current();});observer.observe(el);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',visibility);el.addEventListener('pointerdown',pointerDown);el.addEventListener('pointermove',pointerMove);el.addEventListener('pointerup',pointerUp);el.addEventListener('pointercancel',cancel);el.addEventListener('lostpointercapture',cancel);
  if(process.env.NODE_ENV!=='production')(window as unknown as {__arcade3d:unknown}).__arcade3d={runtime,phaseRef,input};wake.current();
  return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',visibility);el.removeEventListener('pointerdown',pointerDown);el.removeEventListener('pointermove',pointerMove);el.removeEventListener('pointerup',pointerUp);el.removeEventListener('pointercancel',cancel);el.removeEventListener('lostpointercapture',cancel);release();runtime.stage.dispose();game.current=null;wake.current=()=>{};void audio.current?.close();audio.current=null;delete (window as unknown as {__arcade3d?:unknown}).__arcade3d;};
 // The controller lives for this game mount; refs hold changing input and phase.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[kind]);
 return <div className={styles.game} data-arcade-kind={kind}><canvas ref={canvas} tabIndex={0} aria-label={`${info.name} game field`}/><header className={styles.header}><BackButton onBack={onExit} label="Arcade"/><div className={styles.headerScore} aria-live="polite"><strong>{hud.score}</strong><span>{hud.detail||(kind==='tennis'?'Ready to serve':kind==='runner'?'3 chances · 0 m':'0 goals · 3 balls')}</span></div><button className={styles.pause} onClick={()=>phase==='playing'?change('paused'):phase==='paused'?start():null} disabled={phase==='ready'||phase==='over'} aria-label={phase==='paused'?'Resume game':'Pause game'}><Icon name={phase==='paused'?'play':'pause'} size={22}/></button></header>
 {phase==='playing'&&<><p className={styles.message}>{hud.message}</p><footer className={styles.controls}>{kind==='pinball'?<><button {...hold(0)} aria-label="Left flipper" data-ready={hud.leftReady||undefined}><Icon name="back" size={28}/><span>Left</span></button><button {...hold(2)} disabled={!hud.ready&&!hud.nudgeReady}>{hud.ready?'Launch':'Nudge'}</button><button {...hold(1)} aria-label="Right flipper" data-ready={hud.rightReady||undefined}><Icon name="arrow" size={28}/><span>Right</span></button></>:<>{kind==='runner'?<div className={styles.lanes} aria-label="Change lane"><button aria-label="Move one lane left" {...pressLane(-1)}><Icon name="back" size={24}/></button><button aria-label="Move one lane right" {...pressLane(1)}><Icon name="arrow" size={24}/></button></div>:<div className={`touch-controls ${styles.tennisMovement}`}><div ref={stick} className="joystick" role="group" aria-label="Movement joystick" onPointerDown={e=>{if(stickId.current!==null)return;e.preventDefault();stickId.current=e.pointerId;e.currentTarget.setPointerCapture(e.pointerId);moveStick(e);}} onPointerMove={moveStick} onPointerUp={e=>{if(stickId.current===e.pointerId)releaseStick();}} onPointerCancel={releaseStick} onLostPointerCapture={releaseStick}><i className="joystick-contact" aria-hidden="true"><i className="joystick-contact-arc"/></i><span aria-hidden="true"/></div></div>}<div className={`${styles.actions} ${kind==='tennis'?styles.tennisActions:''}`}>{kind==='tennis'?<><button data-tennis-action="header" data-ready={hud.headerReady||undefined} {...pressAction(3)}>Header</button><button data-tennis-action="scissor" data-ready={hud.scissorReady||undefined} {...pressAction(4)}>Scissor</button><button data-tennis-action="kick" {...pressAction(0)}>{hud.ready?'Serve':'Kick'}</button><button data-tennis-action="lob" {...pressAction(1)}>Lob</button><button data-tennis-action="drop" {...pressAction(2)}>Drop</button></>:<><button {...pressAction(1)}>Jump</button><button {...pressAction(2)}>Slide</button><button {...runnerShootHold}>Shoot</button></>}</div></>}</footer></>}
 {(phase!=='playing'||error)&&<div className={styles.overlay}><section className={styles.card}><span className={styles.badge}>{error?'TAKE A BREATHER':phase==='over'?'FULL TIME':phase==='paused'?'TIME OUT':info.tag}</span><h3>{error?'The pitch couldn’t load.':phase==='over'?'One more game?':phase==='paused'?'Ready when you are.':info.name}</h3><p>{error?'Return to the arcade and try again.':phase==='ready'?info.copy:phase==='over'?`${hud.score} · ${hud.detail}`:info.learn}</p>{record.best>0&&<p>Personal best: {record.best}{kind==='tennis'?' touch rally':' points'}</p>}{!error&&kind==='tennis'&&phase==='ready'&&<label className={styles.courtSelect}>Choose court <select defaultValue={Math.min(5,record.unlocked)} key={record.unlocked} onChange={e=>{if(game.current)game.current.state.tennis.level=Number(e.target.value);}}>{TENNIS_COURTS.map((court,i)=><option key={court.name} value={i+1} disabled={i+1>record.unlocked}>{i+1}. {court.name}{i+1>record.unlocked?' · win to unlock':''}</option>)}</select></label>}{entry.message&&<p role="status">{entry.message}</p>}{!error&&phase!=='paused'&&<p>3 coins per play</p>}{!error&&<button className={styles.primary} disabled={entry.pending} onClick={start}>{phase==='paused'?'Resume':phase==='over'?(hud.nextLabel??'Play again'):'Play'}</button>}<button className={styles.exit} onClick={onExit}>Back to arcade</button><small>{touchDevice?touchHelp:info.help}</small></section></div>}
 </div>;
}
